const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),read=n=>fs.readFileSync('app/src/main/assets/pos/'+n,'utf8'),tick=()=>new Promise(r=>setImmediate(r));
const html=read('pos.html'),config=read('Web/js/features/product-configuration.js'),ingredientSource=html.slice(html.indexOf('function productIngredients('),html.indexOf('function stockConsumptionFor(')),start=config.indexOf('function normalizeModifierGroup('),modifierSource=config.slice(start,config.indexOf('\nfunction ',config.indexOf('function validateModifierGroups(')+10));
const cases=JSON.parse(fs.readFileSync('tests/fixtures/recipe-edit.json'));
test('native editor fixtures remain exact reviewed recipe/modifier outputs and errors',()=>{for(const c of cases){const input=c.input,ctx={getProduct:id=>input.products.find(p=>p.id===id),uid:()=> 'generated'};vm.createContext(ctx);vm.runInContext(ingredientSource+'\n'+modifierSource,ctx);let expected;try{if(input.operation==='recipe')expected={allowed:true,ingredients:[...ctx.productIngredients(input.draft)].map(([productId,qty])=>({productId,qty}))};else{ctx.validateModifierGroups(input.groups,input.editingId);expected={allowed:true,groups:input.groups.map(ctx.normalizeModifierGroup)}}}catch(e){expected={allowed:false,message:e.message}}assert.deepEqual(JSON.parse(JSON.stringify(expected)),c.expected)}});
function host(){const recipeCalls=[],catalogCalls=[],events=[],nodes={'pf-name':{id:'pf-name',value:'New'},'pf-recipe-yield':{id:'pf-recipe-yield',value:'1'}};const root={querySelectorAll:()=>Object.values(nodes)};const products=[{id:'a',type:'simple',name:'Milk'}],groups=[{id:'g',name:'Size',min:0,max:1,options:[{id:'o',productId:'a',qty:1,priceDelta:0,posName:'Milk',default:true}]}];const ctx={state:{products,orders:[]},document:{getElementById:id=>id==='modal-root'?root:nodes[id]},_pmType:'composite',_pmComponents:[{productId:'a',qty:2}],_pmModifierGroups:groups,getProduct:id=>products.find(p=>p.id===id),uid:()=> 'new-id',flash:s=>events.push(s),MPosCore:{RecipeEdit:{calculate:input=>new Promise((resolve,reject)=>recipeCalls.push({input,resolve,reject}))},CatalogEdit:{calculate:input=>new Promise(resolve=>catalogCalls.push({input,resolve}))}}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(ingredientSource+'\n'+modifierSource,ctx);let fallbackIngredients=0,fallbackValidate=0,fallbackNormalize=0;for(const [name,count]of [['productIngredients',()=>fallbackIngredients++],['validateModifierGroups',()=>fallbackValidate++],['normalizeModifierGroup',()=>fallbackNormalize++]]){const original=ctx[name];ctx[name]=function(...a){count();return original.apply(this,a)}}ctx.saveProduct=async id=>{ctx.productIngredients({id:id||null,name:'New',type:ctx._pmType,components:ctx._pmComponents});ctx.validateModifierGroups(ctx._pmModifierGroups,id||'new-product');ctx.savedGroups=ctx._pmModifierGroups.map(ctx.normalizeModifierGroup);events.push('save');};vm.runInContext(read('native-catalog-edit.js'),ctx);vm.runInContext(read('native-recipe-edit.js'),ctx);return{ctx,nodes,recipeCalls,catalogCalls,events,counts:()=>[fallbackIngredients,fallbackValidate,fallbackNormalize]};}
const normalized=()=>[{id:'g',name:'Size',min:0,max:1,options:[{id:'o',productId:'a',qty:1,priceDelta:0,posName:'Milk'}]}];
test('recipe then type policy then modifier decisions replace synchronous validators and normalization before save',async()=>{const h=host(),p=h.ctx.saveProduct(null);assert.equal(h.recipeCalls[0].input.operation,'recipe');h.recipeCalls[0].resolve({allowed:true,ingredients:[{productId:'a',qty:2}]});await tick();assert.equal(h.catalogCalls.length,1);h.catalogCalls[0].resolve({allowed:true});await tick();assert.equal(h.recipeCalls[1].input.operation,'modifiers');h.recipeCalls[1].resolve({allowed:true,groups:normalized()});await p;assert.deepEqual(h.counts(),[0,0,0]);assert.deepEqual(JSON.parse(JSON.stringify(h.ctx.savedGroups)),normalized());assert.deepEqual(h.events,['save']);});
test('invalid recipe prevents type lookup and save; edited draft discards late result',async()=>{for(const stale of [false,true]){const h=host(),p=h.ctx.saveProduct(null);if(stale)h.nodes['pf-name'].value='Changed';h.recipeCalls[0].resolve(stale?{allowed:true,ingredients:[{productId:'a',qty:2}]}:{allowed:false,message:'Циклический состав: New'});await p;assert.equal(h.catalogCalls.length,0);assert.ok(!h.events.includes('save'));}});
test('invalid modifiers prevent save after successful type gate',async()=>{const h=host(),p=h.ctx.saveProduct(null);h.recipeCalls[0].resolve({allowed:true,ingredients:[{productId:'a',qty:2}]});await tick();h.catalogCalls[0].resolve({allowed:true});await tick();h.recipeCalls[1].resolve({allowed:false,message:'Выберите существующий товар для каждого модификатора'});await p;assert.ok(!h.events.includes('save'));});
test('explicit recipe rollback uses source validators and normalization',async()=>{const h=host();h.ctx.MPosNativeRecipeEditEnabled=false;const p=h.ctx.saveProduct(null);h.catalogCalls[0].resolve({allowed:true});await p;assert.equal(h.recipeCalls.length,0);assert.ok(h.counts()[0]>0);assert.ok(h.counts()[1]>0);assert.ok(h.counts()[2]>0);assert.ok(h.events.includes('save'));});
test('late transport failure after context close and malformed modifier result cannot reach save',async()=>{const h=host();let generation=0;h.ctx.MPosCore.OrderContext={generation:()=>generation,hasPending:()=>false};const p=h.ctx.saveProduct(null);generation++;h.recipeCalls[0].reject(Error('late'));await p;assert.equal(h.events.length,0);const r=host(),q=r.ctx.saveProduct(null);r.recipeCalls[0].resolve({allowed:true,ingredients:[{productId:'a',qty:2}]});await tick();r.catalogCalls[0].resolve({allowed:true});await tick();r.recipeCalls[1].resolve({allowed:true,groups:[{name:'bad',options:null}]});await q;assert.ok(!r.events.includes('save'));});
test('legacy non-finite modifier normalization remains explicit reviewed compatibility',async()=>{const h=host();h.ctx._pmModifierGroups[0].max='Infinity';const p=h.ctx.saveProduct(null);h.recipeCalls[0].resolve({allowed:true,ingredients:[{productId:'a',qty:2}]});await tick();h.catalogCalls[0].resolve({allowed:true});await p;assert.equal(h.recipeCalls.length,1);assert.ok(h.events.includes('save'));assert.equal(h.ctx.savedGroups[0].max,Infinity);});
