const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const root='app/src/main/assets/pos/',read=name=>fs.readFileSync(root+name,'utf8'),source=read('Web/js/features/payment.js'),cases=JSON.parse(fs.readFileSync('tests/fixtures/split-amount.json'));
const plain=v=>JSON.parse(JSON.stringify(v)),tick=()=>new Promise(r=>setImmediate(r));
function reference(input){const ctx={state:{_splitPayments:structuredClone(input.parts)},cartTotal:()=>input.total};vm.createContext(ctx);vm.runInContext(source,ctx);ctx.syncSplitPaymentUI=()=>ctx.changed=true;ctx.updateSplitAmountLive(input.index,input.raw);return {changed:!!ctx.changed,parts:plain(ctx.state._splitPayments),index:input.index};}
test('amount fixtures reproduce actual reviewed parsing, paid locks, cap and last-row redistribution',()=>{for(const c of cases){const r=reference(c.input);delete r.index;assert.deepEqual(r,c.expected)}});
function host(){const calls=[],messages=[];const ctx={state:{cart:[{productId:'p',qty:1}],paymentPage:'split',_splitPayments:[{amount:2,paid:true,method:'card',cashGiven:null,change:null},{amount:4,paid:false,method:'cash',cashGiven:5,change:1},{amount:4,paid:false,method:'card',cashGiven:null,change:null}]},cartTotal:()=>10,flash:s=>messages.push(s),MPosCore:{SplitCount:{calculate:input=>new Promise((resolve,reject)=>calls.push({kind:'count',input,resolve,reject}))},SplitAmountRead:{calculate:input=>new Promise((resolve,reject)=>calls.push({kind:'amount',input,resolve,reject}))}}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(source,ctx);ctx.syncSplitPaymentUI=()=>ctx.synced=(ctx.synced||0)+1;ctx.renderSplitPayment=()=>ctx.rendered=true;ctx.closeModal=()=>{};ctx.closePaymentPage=()=>{};ctx.returnFromSplitPayment=()=>{};vm.runInContext(read('native-split-count.js'),ctx);vm.runInContext(read('native-split-amount.js'),ctx);return {ctx,calls,messages};}
function resolve(call){call.resolve(reference(call.input));}
test('consecutive queued keystrokes coalesce; in-flight edit then latest value preserve row references',async()=>{const h=host(),parts=h.ctx.state._splitPayments,paid=parts[0],first=h.ctx.updateSplitAmountLive(1,'1');await tick();const second=h.ctx.updateSplitAmountLive(1,'2'),third=h.ctx.updateSplitAmountLive(1,'3');assert.equal(second,third);assert.equal(h.calls.length,1);resolve(h.calls[0]);await first;await tick();assert.equal(h.calls.length,2);assert.equal(h.calls[1].input.raw,'3');resolve(h.calls[1]);await third;assert.equal(parts[1].amount,3);assert.equal(parts[2].amount,5);assert.equal(parts[1].cashGiven,null);assert.equal(parts[1].change,null);assert.equal(h.ctx.state._splitPayments,parts);assert.equal(parts[0],paid);assert.equal(paid.amount,2);assert.equal(h.ctx.MPosCore.SplitPayments.hasPending(),false)});
test('last unpaid edit follows source even when redistributing to previous unpaid rows',async()=>{const h=host(),p=h.ctx.updateSplitAmountLive(2,'1');await tick();resolve(h.calls[0]);await p;assert.equal(h.ctx.state._splitPayments[1].amount,7);assert.equal(h.ctx.state._splitPayments[1].cashGiven,5);assert.equal(h.ctx.state._splitPayments[2].amount,1)});
test('count operations are FIFO barriers between amount edits',async()=>{const h=host(),a=h.ctx.updateSplitAmountLive(1,'1'),b=h.ctx.adjustSplitCount(1),c=h.ctx.updateSplitAmountLive(1,'3');await tick();assert.equal(h.calls[0].input.raw,'1');resolve(h.calls[0]);await a;await tick();assert.equal(h.calls[1].kind,'count');const input=h.calls[1].input;h.calls[1].resolve({allowed:true,changed:true,count:4,indices:[0,1,2,-1],parts:[input.parts[0],{...input.parts[1],amount:2.67},{...input.parts[2],amount:2.67},{method:'cash',amount:2.66,paid:false,cashGiven:null,change:null}]});await b;await tick();assert.equal(h.calls[2].input.raw,'3');assert.equal(h.calls[2].input.parts.length,4);resolve(h.calls[2]);await c;assert.equal(h.ctx.state._splitPayments[1].amount,3);assert.equal(h.ctx.state._splitPayments[2].amount,2.5)});
test('invalid input and paid target do not read; native errors and modified paid rows do not apply',async()=>{const h=host();for(const raw of ['','-','1.234'])h.ctx.updateSplitAmountLive(1,raw);h.ctx.updateSplitAmountLive(0,'1');assert.equal(h.calls.length,0);for(const fail of [true,false]){const x=host(),before=plain(x.ctx.state._splitPayments),p=x.ctx.updateSplitAmountLive(1,'2');await tick();if(fail)x.calls[0].reject(Error('bridge'));else{const r=reference(x.calls[0].input);r.parts[0].amount=99;x.calls[0].resolve(r)}await p;assert.deepEqual(plain(x.ctx.state._splitPayments),before);assert.equal(x.messages.length,1)}});
test('close, replacement, method/context change and rollback discard a late edit',async()=>{for(const edit of [h=>h.ctx.closeModal(),h=>h.ctx.state.cart=[],h=>h.ctx.state._splitPayments[1].method='card',h=>h.ctx.state.customer={id:'changed'},h=>h.ctx.MPosNativeSplitAmountEnabled=false]){const h=host(),p=h.ctx.updateSplitAmountLive(1,'2');await tick();edit(h);const before=plain(h.ctx.state._splitPayments);resolve(h.calls[0]);await p;assert.deepEqual(plain(h.ctx.state._splitPayments),before)}const h=host();h.ctx.MPosNativeSplitAmountEnabled=false;h.ctx.updateSplitAmountLive(1,'3');assert.equal(h.ctx.state._splitPayments[1].amount,3);assert.equal(h.calls.length,0)});

test('a cancelled queued edit releases its coalescing slot so the next input can retry',async()=>{const h=host(),a=h.ctx.updateSplitAmountLive(1,'1');await tick();const b=h.ctx.updateSplitAmountLive(1,'2');h.ctx.state.busy=true;resolve(h.calls[0]);await a;await b;assert.equal(h.calls.length,1);h.ctx.state.busy=false;const retry=h.ctx.updateSplitAmountLive(1,'3');await tick();assert.equal(h.calls.length,2);resolve(h.calls[1]);await retry;assert.equal(h.ctx.state._splitPayments[1].amount,3)});
test('paid and draft are untouched until the engine response; disabling only count retains the amount queue',async()=>{const h=host(),before=plain(h.ctx.state._splitPayments);h.ctx.MPosNativeSplitCountEnabled=false;const p=h.ctx.updateSplitAmountLive(1,'3');assert.deepEqual(plain(h.ctx.state._splitPayments),before);assert.equal(h.ctx.MPosCore.SplitPayments.hasPending(),true);await tick();resolve(h.calls[0]);await p;assert.equal(h.ctx.state._splitPayments[1].amount,3);assert.equal(h.ctx.state._splitPaymentTotalCents,undefined)});

test('context changes cancel both in-flight and already queued old inputs; a new input starts afresh',async()=>{const h=host(),first=h.ctx.updateSplitAmountLive(1,'1');await tick();const old=h.ctx.updateSplitAmountLive(1,'2');h.ctx.state.customer={id:'new'};const fresh=h.ctx.updateSplitAmountLive(1,'3');resolve(h.calls[0]);await first;await old;await tick();assert.equal(h.calls.length,2);assert.equal(h.calls[1].input.raw,'3');resolve(h.calls[1]);await fresh;assert.equal(h.ctx.state._splitPayments[1].amount,3)});
