const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('app/src/main/assets/pos/native-loyalty-authorization.js','utf8');
function host(){const sent=[],network=[],events=[],timers=new Map();let seq=0,required=false,allowed=true;
 const nodes={'la-progress':{value:'1'},'la-rewards':{value:'0'},'la-reason':{value:'Correction'},'la-admin-password':{value:'synthetic-dom-value',closest:()=>({remove:()=>events.push('remove-password')})},'modal-root':{querySelector:()=>({after:note=>events.push(note.textContent)})}};
 const c={state:{theme:'light'},document:{getElementById:id=>nodes[id],createElement:()=>({})},openLoyaltyAdjustment:()=>events.push('open'),saveLoyaltyAdjustment:()=>events.push('legacy-save'),openCustomerAdminCard:()=>events.push('customer'),flash:x=>events.push(x),setTimeout:fn=>{timers.set(++seq,fn);return seq},clearTimeout:id=>timers.delete(id),MPosCore:{Storage:{get:async()=>null},AdminAccess:{check:async()=>({allowed})},LoyaltyVerification:{status:async()=>({required})}},webkit:{messageHandlers:{settingsScreen:{postMessage:p=>sent.push(p)},network:{postMessage:p=>network.push(p)}}}};c.window=c;vm.createContext(c);vm.runInContext(source,c);const ready=async()=>{for(let i=0;i<16;i++)await Promise.resolve()};return {c,sent,network,events,nodes,ready,setRequired:v=>required=v,setAllowed:v=>allowed=v};}
test('form removes reviewed DOM password before display and sends only nonsecret adjustment fields',async()=>{const h=host();await h.c.openLoyaltyAdjustment('c','program','Program');assert.equal(h.nodes['la-admin-password'].value,'');const p=h.c.saveLoyaltyAdjustment('c','program');await h.ready();assert.equal(h.sent.length,1);assert.equal(h.sent[0].command.progressDelta,1);assert.equal(JSON.stringify(h.sent).includes('synthetic-dom-value'),false);assert.equal(JSON.stringify(h.sent).includes('adminPassword'),false);h.c.__mposLoyaltyAuthorizationResult({requestId:h.sent[0].requestId,ok:true});assert.equal(await p,true);assert.equal(h.events.at(-1),'customer');});
test('native denial and cancellation cause no adjustment or success notification',async()=>{const h=host();h.setAllowed(false);assert.equal(await h.c.saveLoyaltyAdjustment('c','program'),false);assert.equal(h.sent.length,0);h.setAllowed(true);const p=h.c.saveLoyaltyAdjustment('c','program');await h.ready();h.c.__mposLoyaltyAuthorizationResult({requestId:h.sent[0].requestId,cancelled:true});assert.equal(await p,false);assert.equal(h.events.includes('customer'),false);});
test('unknown prior adjustment requires native balance read and resets form instead of resending correction',async()=>{const h=host();h.setRequired(true);const p=h.c.saveLoyaltyAdjustment('c','program');await h.ready();assert.equal(h.sent.length,0);assert.equal(h.network[0].action,'loyaltyBalanceVerification');h.c.__nativeNetworkResult({requestId:h.network[0].requestId,ok:true,authoritative:true,program:{id:'program',progress:3,rewards:1}});assert.equal(await p,false);assert.equal(h.events.some(x=>String(x).includes('подарков 1')),true);assert.equal(h.sent.length,0);});
test('failed balance verification leaves prior operation blocked without opening editable correction',async()=>{const h=host();h.setRequired(true);const p=h.c.openLoyaltyAdjustment('c','program','Program');await h.ready();h.c.__nativeNetworkResult({requestId:h.network[0].requestId,ok:false,message:'Offline'});assert.equal(await p,false);assert.equal(h.events.includes('open'),false);assert.equal(h.sent.length,0);});
test('duplicate submit and stale results never resend a correction',async()=>{const h=host(),p=h.c.saveLoyaltyAdjustment('c','program');await h.ready();assert.equal(await h.c.saveLoyaltyAdjustment('c','program'),false);h.c.__mposLoyaltyAuthorizationResult({requestId:'stale',ok:true});assert.equal(h.events.includes('customer'),false);h.c.__mposLoyaltyAuthorizationResult({requestId:h.sent[0].requestId,ok:false,message:'Сервер не ответил вовремя'});assert.equal(await p,false);assert.equal(h.sent.length,1);});
