const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const root='app/src/main/assets/pos/',read=n=>fs.readFileSync(root+n,'utf8');
const source=read('Web/js/features/cart-presentation.js')+'\n'+read('Web/js/features/loyalty.js')+'\n'+read('pos.html').match(/function cartTotal\(\)\{[\s\S]*?\n\}/)[0];
class Node {
 constructor(className='',text=''){this.className=className;this.textContent=text;this.children=[];this.parent=null;this.classList={contains:c=>this.className.split(' ').includes(c)};}
 append(...nodes){for(const node of nodes){node.parent=this;this.children.push(node)}}
 querySelector(selector){const cls=selector.slice(1);for(const node of this.children){if(node.classList.contains(cls))return node;const child=node.querySelector(selector);if(child)return child;}return null;}
 querySelectorAll(selector){const nodes=[];for(const node of this.children){if(node.classList.contains(selector.slice(1)))nodes.push(node);nodes.push(...node.querySelectorAll(selector));}return nodes;}
 insertBefore(node,before){node.parent=this;this.children.splice(this.children.indexOf(before),0,node)}
 remove(){this.parent.children.splice(this.parent.children.indexOf(this),1)}
}
function host(){const requests=[],timers=[];const panel=new Node('cart-panel'),line=new Node('cart-row-linetotal','reviewed'),foot=new Node('cart-foot'),row=new Node('total-row'),value=new Node('value','reviewed'),label=new Node('label','Итого');row.append(label,value);foot.append(row);panel.append(line,foot);const delivery=new Node('delivery-total-value','reviewed');let shown=panel;const document={querySelector:s=>s==='.cart-panel'?shown:s==='.delivery-total-value'?delivery:null,createElement:()=>new Node()};const ctx={state:{tab:'pos',cart:[{productId:'p',price:10,qty:1}],discounts:[],orderType:'На месте',deliveryFee:0,loyaltyPrograms:[],loyaltyRedemptions:{}},document,setTimeout:fn=>timers.push(fn),money:v=>String(v),fullMoney:v=>String(v),MPosCore:{CartTotals:{calculate:input=>new Promise((resolve,reject)=>requests.push({input,resolve,reject}))}}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(source,ctx);ctx.renderCartPanel=()=>'<existing markup>';vm.runInContext(read('native-cart-totals.js'),ctx);vm.runInContext(read('native-cart-preview.js'),ctx);return {ctx,requests,timers,panel,line,foot,value,delivery,hide:()=>shown=null,flush:()=>timers.shift()?.()};}
function answer(total=10,discount=0){return {pricing:{lines:[{discount:0,total}],subtotal:total,total,productDiscountTotal:0,subtotalBeforeDiscounts:total},loyalty:{discount,allocations:{},programDiscounts:{},snapshot:{programs:[]}}};}
test('preview patches native numbers without replacing markup, focus or scroll nodes',async()=>{const h=host();h.panel.scrollTop=77;const original=h.panel;assert.equal(h.ctx.renderCartPanel(),'<existing markup>');const p=h.flush();h.requests[0].resolve(answer(123.45));await p;assert.equal(h.value.textContent,'123.45');assert.equal(h.line.textContent,'123.45');assert.equal(h.delivery.textContent,'123.45');assert.equal(h.panel,original);assert.equal(h.panel.scrollTop,77);assert.equal(h.requests.length,1)});
test('unchanged renders and payment preparation share a pending pure quote',async()=>{const h=host();h.ctx.renderCartPanel();h.ctx.renderCartPanel();assert.equal(h.timers.length,1);const preview=h.flush(),payment=h.ctx.MPosCore.PaymentTotals.prepare();assert.equal(h.requests.length,1);h.requests[0].resolve(answer());await preview;await payment;h.ctx.renderCartPanel();await h.flush();assert.equal(h.requests.length,1)});
test('all financial inputs invalidate preview; only matching latest quote may be shown',async()=>{for(const edit of [s=>s.cart[0].qty=2,s=>s.cart[0].price=20,s=>s.cart[0].discountId='d',s=>s.discounts=[{id:'d',type:'percent',value:10}],s=>s.orderType='Доставка',s=>s.deliveryFee=2,s=>s.loyaltyPrograms=[{id:'g',type:'gift'}],s=>s.loyaltyRedemptions={g:1}]){const h=host();h.ctx.renderCartPanel();const first=h.flush();edit(h.ctx.state);h.ctx.renderCartPanel();h.requests[0].resolve(answer(999));await first;assert.equal(h.value.textContent,'reviewed');assert.equal(h.timers.length,1);const second=h.flush();h.requests[1].resolve(answer(21));await second;assert.equal(h.value.textContent,'21')}});
test('quote failure, navigation, hidden panel and rollback preserve the reviewed preview',async()=>{for(const mode of ['error','tab','hide','disabled']){const h=host();h.ctx.renderCartPanel();const p=h.flush();if(mode==='error')h.requests[0].reject(Error('read'));else{if(mode==='tab')h.ctx.state.tab='products';if(mode==='hide')h.hide();if(mode==='disabled')h.ctx.MPosNativeCartPreviewEnabled=false;h.requests[0].resolve(answer(99));}await p;assert.equal(h.value.textContent,'reviewed');assert.equal(h.timers.length,0)}});
test('loyalty financial row appears and disappears using the existing POS classes',async()=>{const h=host();h.ctx.renderCartPanel();const first=h.flush();h.requests[0].resolve(answer(10,2));await first;let row=h.foot.children.find(r=>r.querySelector('.label')?.textContent==='Программа лояльности');assert.equal(row.className,'total-row cart-total-meta');assert.equal(row.querySelector('.value').textContent,'−2');h.ctx.state.cart[0].qty=2;h.ctx.renderCartPanel();const second=h.flush();h.requests[1].resolve(answer(20,0));await second;assert.equal(h.foot.children.length,1)});

test('a late plain preview cannot evict tender calculated for a concurrent cash confirmation',async()=>{for(const cashFirst of [true,false]){const h=host();h.ctx.renderCartPanel();const preview=h.flush(),cash=h.ctx.MPosCore.PaymentTotals.prepare(20);assert.equal(h.requests.length,2);const tender=answer(10);tender.cash={allowed:true,cashGiven:20,change:10};if(cashFirst){h.requests[1].resolve(tender);await cash;h.requests[0].resolve(answer(10));await preview;}else{h.requests[0].resolve(answer(10));await preview;h.requests[1].resolve(tender);await cash;}assert.equal(h.ctx.MPosCore.PaymentTotals.cash(20).change,10);}});
