const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function host(){
 const events=[],requests=[];
 const ctx={state:{cart:[{productId:'p',qty:1,selectedModifiers:[]}],products:[],customer:{},loyaltyRedemptions:{},deliveryRates:[],orderType:'На месте',paymentPage:'main',_paymentCashGiven:10,_splitPayments:[{method:'card',amount:10,paid:false}]},console,document:{getElementById:()=>null},flash:x=>events.push(x),currentShift:()=>({id:'s'}),canFulfillCart:()=>{throw Error('legacy stock must not run')},cartTotal:()=>10,paymentGivenValue:()=>10,renderPaymentScreen:()=>events.push('screen'),hasPaidSplitPayment:()=>false,setTimeout:()=>{},closeModal:()=>events.push('close'),openOrderSettings:()=>events.push('settings'),MPosCore:{StockPreflight:{check:x=>new Promise((resolve,reject)=>requests.push({x,resolve,reject}))},CartOperations:{hasPending:()=>false}}};ctx.window=ctx;vm.createContext(ctx);
 vm.runInContext(fs.readFileSync('app/src/main/assets/pos/Web/js/features/payment.js','utf8'),ctx);
 ctx.renderPaymentScreen=()=>events.push('screen');ctx.finalizePayment=x=>events.push(x);ctx.openCardPartConfirmation=(amount,action)=>{events.push('card');ctx.cardAction=action};ctx.openSplitCashPayment=()=>events.push('split-cash');ctx.completeSplitPayment=()=>events.push('split-complete');
 vm.runInContext(fs.readFileSync('app/src/main/assets/pos/native-payment-preflight.js','utf8'),ctx);
 return {ctx,events,requests};
}
test('payment opening uses Room without deducting or invoking legacy stock',async()=>{const h=host(),legacy=h.ctx.canFulfillCart;const p=h.ctx.openPaymentModal();assert.equal(h.events.length,0);assert.equal(h.requests[0].x.items[0].qty,1);h.requests[0].resolve({allowed:true});await p;assert.deepEqual(h.events,['screen']);assert.equal(h.ctx.canFulfillCart,legacy);assert.equal(h.ctx.state.cart.length,1)});
test('cash and card preserve confirmation sequence after Room approval',async()=>{for(const method of ['cash','card']){const h=host(),p=h.ctx.confirmPaymentScreen(method);h.requests[0].resolve({allowed:true});await p;if(method==='cash')assert.equal(h.events[0][0].amount,10);else{assert.deepEqual(h.events,['card']);h.ctx.cardAction();assert.equal(h.events[1][0].method,'card')}}});
test('split cash/card uses approved stock before opening confirmation',async()=>{for(const method of ['cash','card']){const h=host();h.ctx.state._splitPayments[0].method=method;const p=h.ctx.paySplitPart(0);h.requests[0].resolve({allowed:true});await p;assert.deepEqual(h.events,[method==='cash'?'split-cash':'card']);assert.equal(h.ctx.state._splitPayments[0].paid,false)}});
test('shortage, unavailable or malformed native verdict never starts payment',async()=>{for(const result of [{allowed:false,reason:'Нет ингредиента'}, {},null]){const h=host(),p=h.ctx.confirmPaymentScreen('cash');h.requests[0].resolve(result);await p;assert.equal(h.events.length,1);assert.equal(typeof h.events[0],'string')}const h=host(),p=h.ctx.openPaymentModal();h.requests[0].reject(Error('timeout'));await p;assert.equal(h.events.length,1)});
test('cancel, cart mutation, cash edit and pending cart operation invalidate reply',async()=>{for(const change of [h=>h.ctx.closeModal(),h=>h.ctx.closePaymentPage(),h=>h.ctx.state.cart[0].qty++,h=>h.ctx.state._paymentCashGiven=20,h=>h.ctx.MPosCore.CartOperations.hasPending=()=>true]){const h=host(),p=h.ctx.confirmPaymentScreen('card');change(h);h.requests[0].resolve({allowed:true});await p;assert.ok(!h.events.includes('card'))}});
test('duplicate taps and pending quantity do not start competing payment reads',async()=>{const h=host(),p=h.ctx.openPaymentModal();await h.ctx.openPaymentModal();assert.equal(h.requests.length,1);h.requests[0].resolve({allowed:true});await p;const b=host();b.ctx.MPosCore.CartOperations.hasPending=()=>true;await b.ctx.paySplitPart(0);assert.equal(b.requests.length,0)});
test('gift server guard runs after stock and its callback obtains a fresh stock check',async()=>{const h=host();h.ctx.state.loyaltyRedemptions={g:1};let callback;h.ctx.beginPaymentWithLoyaltyGuard=action=>{h.events.push('gift');callback=action};const p=h.ctx.confirmPaymentScreen('card');h.requests[0].resolve({allowed:true});await p;assert.deepEqual(h.events,['gift']);const next=callback();assert.equal(h.requests.length,2);h.requests[1].resolve({allowed:true});await next;assert.deepEqual(h.events,['gift','card'])});
test('delivery, empty cart and closed shift fail before requesting stock',async()=>{for(const setup of [h=>{h.ctx.state.orderType='Доставка'},h=>{h.ctx.state.cart=[]},h=>{h.ctx.currentShift=()=>null}]){const h=host();setup(h);await h.ctx.openPaymentModal();assert.equal(h.requests.length,0);assert.ok(h.events.length>0)}});
test('rollback restores reviewed stock check and synchronous override is restored on handler error',async()=>{const h=host();h.ctx.MPosNativePaymentPreflightEnabled=false;h.ctx.canFulfillCart=()=>{h.events.push('legacy');return false};await h.ctx.openPaymentModal();assert.deepEqual(h.events,['legacy']);assert.equal(h.requests.length,0);const b=host(),legacy=b.ctx.canFulfillCart;b.ctx.renderPaymentScreen=()=>{throw Error('render failed')};const p=b.ctx.openPaymentModal();b.requests[0].resolve({allowed:true});await assert.rejects(p,/render failed/);assert.equal(b.ctx.canFulfillCart,legacy)});
test('payment waits for quote after stock and confirms using the native displayed total',async()=>{const h=host(),requests=[];h.ctx.state.discounts=[];h.ctx.state.loyaltyPrograms=[];h.ctx.state._paymentCashGiven=20;h.ctx.paymentGivenValue=()=>20;h.ctx.MPosCore.CartTotals={calculate:input=>new Promise(resolve=>requests.push({input,resolve}))};vm.runInContext(fs.readFileSync('app/src/main/assets/pos/native-cart-totals.js','utf8'),h.ctx);const p=h.ctx.confirmPaymentScreen('cash');h.requests[0].resolve({allowed:true});for(let n=0;n<10&&!requests.length;n++)await Promise.resolve();assert.equal(h.events.length,0);assert.equal(requests.length,1);requests[0].resolve({pricing:{total:12.5,subtotal:12.5,productDiscountTotal:0,subtotalBeforeDiscounts:12.5,lines:[{total:12.5,discount:0}]},loyalty:{discount:0,allocations:{},programDiscounts:{},snapshot:{discount:0,programs:[]}}});await p;assert.equal(h.events[0][0].amount,12.5);assert.equal(h.events[0][0].change,7.5)});
test('quote errors and cancellation cannot confirm a payment after successful stock read',async()=>{for(const cancel of [true,false]){const h=host();let resolve,reject;h.ctx.MPosCore.PaymentTotals={enabled:()=>true,prepare:()=>new Promise((a,b)=>{resolve=a;reject=b})};const p=h.ctx.confirmPaymentScreen('card');h.requests[0].resolve({allowed:true});for(let n=0;n<10&&!resolve;n++)await Promise.resolve();if(cancel){h.ctx.closeModal();resolve(true)}else reject(Error('timeout'));await p;assert.ok(!h.events.includes('card'))}});

test('payment waits for pending split redistribution before any stock or quote read',async()=>{for(const name of ['openPaymentModal','confirmPaymentScreen','paySplitPart']){const h=host();h.ctx.MPosCore.SplitPayments={hasPending:()=>true};await h.ctx[name](name==='confirmPaymentScreen'?'card':0);assert.equal(h.requests.length,0);assert.equal(h.events.length,1);}});
