const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('app/src/main/assets/pos/Web/js/features/employees.js','utf8'),adapter=fs.readFileSync('app/src/main/assets/pos/native-employee-command.js','utf8');
function host(){const calls=[],native=[],legacy=[],events=[],nodes={'ef-name':{value:' Name '},'ef-phone':{value:' +123 '},'ef-admin':{checked:false},'employee-save-confirm':{},'employee-delete-confirm':{}};const timers=new Map();let timerId=0;
 const c={state:{employees:[]},document:{getElementById:id=>nodes[id]||{value:''}},storageSnapshot:x=>JSON.parse(JSON.stringify(x)),uid:()=> 'new',currentShift:()=>({id:'s',employeeId:'self'}),criticalStorageRecoveryPending:false,closeModal:()=>events.push('close'),render:()=>events.push('render'),flash:x=>events.push(x),markStorageBroken:()=>events.push('broken'),setTimeout:fn=>{timers.set(++timerId,fn);return timerId},clearTimeout:id=>timers.delete(id),webkit:{messageHandlers:{settingsScreen:{postMessage:p=>native.push(p)}}},PrilavokCore:{Storage:Object.freeze({set:async(k,v)=>legacy.push({k,v})})},MPosCore:{EmployeeCommands:{commit:input=>new Promise((resolve,reject)=>calls.push({input,resolve,reject}))}}};c.window=c;vm.createContext(c);vm.runInContext(source,c);vm.runInContext(adapter,c);return{c,calls,native,legacy,events,nodes,timers}}
test('create applies only after native acknowledgement and carries no credentials or authority marker',async()=>{const h=host(),p=h.c.saveEmployee();assert.equal(h.calls.length,1);assert.equal(h.c.state.employees.length,0);assert.equal(h.calls[0].input.next[0].name,'Name');assert.equal(h.calls[0].input.next[0].phone,'+123');assert.equal(Object.keys(h.calls[0].input).some(k=>/password|credential|authorization/i.test(k)),false);h.calls[0].resolve();assert.equal(await p,true);assert.equal(h.c.state.employees.length,1);assert.deepEqual(h.events.slice(0,2),['close','render']);assert.equal(h.legacy.length,0)});
test('role change uses a native confirmation with no password from mounted fields',async()=>{const h=host();h.nodes['ef-admin'].checked=true;const p=h.c.saveEmployee();assert.equal(h.calls.length,0);assert.equal(h.native.length,1);assert.equal(h.native[0].action,'employeeAuthorize');assert.equal(JSON.stringify(h.native[0]).includes('credential'),false);assert.equal(h.c.state.employees.length,0);h.c.__mposEmployeeCommandResult({requestId:h.native[0].requestId,ok:true});assert.equal(await p,true);assert.equal(h.c.state.employees[0].role,'admin');});
test('failed and uncertain commits preserve memory and release buttons',async()=>{const h=host(),p=h.c.saveEmployee();h.calls[0].reject(Error('commit status is uncertain'));assert.equal(await p,false);assert.equal(h.c.state.employees.length,0);assert.equal(h.c.criticalStorageRecoveryPending,true);assert.equal(h.nodes['employee-save-confirm'].disabled,false);await h.c.saveEmployee();assert.equal(h.calls.length,1)});
test('import uses existing owned storage and rollback invokes the reviewed handler',async()=>{const h=host();await h.c.PrilavokCore.Storage.set('employees',[]);assert.equal(h.legacy.length,1);h.c.MPosNativeEmployeeCommandsEnabled=false;assert.equal(await h.c.saveEmployee(),true);assert.equal(h.legacy.length,2);assert.equal(h.calls.length,0)});
test('deletion preserves self/admin guards but confirms an ordinary employee through native input',async()=>{const h=host();h.c.state.employees=[{id:'self',role:'employee'},{id:'a',role:'admin'},{id:'other',role:'employee'}];await h.c.confirmDeleteEmployee('self');await h.c.confirmDeleteEmployee('a');assert.equal(h.native.length,0);const p=h.c.confirmDeleteEmployee('other');assert.equal(h.native.length,1);h.c.__mposEmployeeCommandResult({requestId:h.native[0].requestId,ok:true});assert.equal(await p,true);assert.equal(h.c.state.employees.length,2)});
test('cancel and credential retry do not change employees or mark storage broken; timeout starts at commit',async()=>{
 const h=host();h.nodes['ef-admin'].checked=true;const p=h.c.saveEmployee(),id=h.native[0].requestId;assert.equal(h.timers.size,0);
 h.c.__mposEmployeeCommandResult({requestId:id,action:'committing'});assert.equal(h.timers.size,1);
 h.c.__mposEmployeeCommandResult({requestId:id,action:'retry'});assert.equal(h.timers.size,0);
 h.c.__mposEmployeeCommandResult({requestId:id,cancelled:true});assert.equal(await p,false);assert.equal(h.c.state.employees.length,0);assert.equal(h.events.includes('broken'),false);assert.equal(h.nodes['employee-save-confirm'].disabled,false);
});
test('double submit and late results cannot apply an old employee update',async()=>{
 const h=host();h.nodes['ef-admin'].checked=true;const p=h.c.saveEmployee();assert.equal(await h.c.saveEmployee(),false);assert.equal(h.native.length,1);
 const id=h.native[0].requestId;h.c.__mposEmployeeCommandResult({requestId:id,cancelled:true});assert.equal(await p,false);
 h.c.__mposEmployeeCommandResult({requestId:id,ok:true});assert.equal(h.c.state.employees.length,0);
});
test('native commit timeout preserves memory and ignores a late success',async()=>{
 const h=host();h.nodes['ef-admin'].checked=true;const p=h.c.saveEmployee(),id=h.native[0].requestId;
 h.c.__mposEmployeeCommandResult({requestId:id,action:'committing'});[...h.timers.values()][0]();assert.equal(await p,false);
 assert.equal(h.c.criticalStorageRecoveryPending,true);h.c.__mposEmployeeCommandResult({requestId:id,ok:true});assert.equal(h.c.state.employees.length,0);
});
