const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const root='app/src/main/assets/pos/',read=n=>fs.readFileSync(root+n,'utf8'),source=read('Web/js/features/payment.js'),cart=read('Web/js/features/cart-presentation.js'),cases=JSON.parse(fs.readFileSync('tests/fixtures/delivery.json')),tick=()=>new Promise(r=>setImmediate(r)),plain=v=>JSON.parse(JSON.stringify(v));
function reference(input){let changed=false;const s=input.state,ctx={state:{orderType:s.orderType,deliveryFee:s.fee,deliveryTariffSelected:s.selected,deliveryRates:structuredClone(s.rates)},saveCurrentOrderSession:()=>changed=true,render(){}};vm.createContext(ctx);vm.runInContext(source+'\n'+cart,ctx);ctx.openOrderSettings=()=>{};if(input.operation==='check')return {allowed:ctx.hasDeliveryTariff()};ctx[input.operation==='type'?'setOrderType':'selectDeliveryFee'](input.operation==='type'?input.orderType:input.amount);return {changed,...(changed?{fee:ctx.state.deliveryFee,selected:ctx.state.deliveryTariffSelected,...(input.operation==='type'?{orderType:ctx.state.orderType}:{})}:{})};}
test('delivery golden fixtures are the actual reviewed selection and tariff policy',()=>{for(const c of cases)assert.deepEqual(plain(reference(c.input)),c.expected)});
function host(){const calls=[],events=[];const ctx={state:{cart:[{productId:'p',price:10,qty:1}],customer:{},orderType:'На месте',deliveryFee:0,deliveryTariffSelected:false,deliveryRates:[{amount:0},{amount:2},{amount:5}],discounts:[],loyaltyPrograms:[],loyaltyRedemptions:{}},saveCurrentOrderSession:()=>events.push('save'),render:()=>events.push('render'),flash:s=>events.push(s),closeModal(){},closePaymentPage(){},showModal:()=>events.push('modal'),MPosCore:{DeliveryRead:{calculate:input=>new Promise((resolve,reject)=>calls.push({input,resolve,reject}))}}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(source+'\n'+cart,ctx);ctx.openOrderSettings=()=>ctx.showModal();vm.runInContext(read('native-order-context-queue.js'),ctx);vm.runInContext(read('native-delivery.js'),ctx);return {ctx,calls,events};}
test('type then tariff apply in order through acknowledged continuity and preserve save/render/modal order',async()=>{const h=host(),first=h.ctx.setOrderType('Доставка'),second=h.ctx.selectDeliveryFee(2);await tick();assert.equal(h.calls.length,1);h.calls[0].resolve(reference(h.calls[0].input));await first;await tick();assert.equal(h.calls[1].input.state.orderType,'Доставка');h.calls[1].resolve(reference(h.calls[1].input));await second;assert.equal(h.ctx.state.deliveryFee,2);assert.equal(h.ctx.state.deliveryTariffSelected,true);assert.deepEqual(h.events,['save','render','modal','save','render','modal']);assert.equal(h.ctx.MPosCore.OrderContext.hasPending(),false)});
test('no matching rate, failed read or malformed response cannot save or mutate delivery',async()=>{for(const mode of ['missing','error','malformed']){const h=host(),before=plain(h.ctx.state),p=h.ctx.selectDeliveryFee(mode==='missing'?99:2);await tick();if(mode==='error')h.calls[0].reject(Error('bridge'));else h.calls[0].resolve(mode==='malformed'?{changed:true,selected:true,fee:Infinity}:reference(h.calls[0].input));await p;assert.deepEqual(plain(h.ctx.state),before);assert.ok(!h.events.includes('save'))}});
test('closing, external context changes and rollback discard late and already queued actions',async()=>{for(const edit of [h=>h.ctx.closeModal(),h=>h.ctx.showModal(),h=>h.ctx.state.customer={id:'new'},h=>h.ctx.state.cart=[],h=>h.ctx.MPosNativeDeliveryEnabled=false]){const h=host(),first=h.ctx.selectDeliveryFee(2),second=h.ctx.selectDeliveryFee(5);await tick();edit(h);const before=plain(h.ctx.state);h.calls[0].resolve(reference(h.calls[0].input));await first;await second;assert.deepEqual(plain(h.ctx.state),before);assert.equal(h.calls.length,1)}});
test('reviewed rollback and cached native predicate retain free delivery with strict selection flag',()=>{const h=host();h.ctx.MPosNativeDeliveryEnabled=false;h.ctx.setOrderType('Доставка');h.ctx.selectDeliveryFee(0);assert.equal(h.ctx.hasDeliveryTariff(),true);assert.equal(h.calls.length,0);h.ctx.MPosNativeDeliveryEnabled=true;h.ctx.MPosCore.PaymentTotals={delivery:()=>false};assert.equal(h.ctx.hasDeliveryTariff(),false);h.ctx.MPosCore.PaymentTotals.delivery=()=>true;assert.equal(h.ctx.hasDeliveryTariff(),true)});

test('delivery status is included in the existing quote and malformed status cannot be cached',async()=>{for(const malformed of [false,true]){const h=host(),quotes=[];h.ctx.MPosCore.CartTotals={calculate:input=>new Promise(resolve=>quotes.push({input,resolve}))};vm.runInContext(read('native-cart-totals.js'),h.ctx);h.ctx.state.orderType='Доставка';h.ctx.state.deliveryFee=2;h.ctx.state.deliveryTariffSelected=true;const p=h.ctx.MPosCore.PaymentTotals.prepare();assert.equal(quotes[0].input.deliveryState.rates[1].amount,2);const value={pricing:{lines:[{discount:0,total:10}],subtotal:10,total:12,productDiscountTotal:0,subtotalBeforeDiscounts:10},loyalty:{discount:0,allocations:{},programDiscounts:{},snapshot:{programs:[]}},delivery:{allowed:false}};if(malformed)delete value.delivery;quotes[0].resolve(value);if(malformed)await assert.rejects(p,/delivery status/);else{assert.equal(await p,true);assert.equal(h.ctx.hasDeliveryTariff(),false)}}});
