const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const read=n=>fs.readFileSync('app/src/main/assets/pos/'+n,'utf8'),tick=()=>new Promise(r=>setImmediate(r));
function host(){const nodes={},events=[],calls=[];for(const id of ['order-label','customer-name','customer-phone','customer-address'])nodes[id]={value:'  '+id+'  '};const ctx={state:{cart:[{id:'p'}],customer:{id:'customer-1',extension:{keep:true}},orderComment:'Комментарий WEB',loyaltyPrograms:[{id:1}],loyaltyRedemptions:{x:2}},document:{getElementById:id=>nodes[id]||null},saveCurrentOrderSession:()=>events.push('save'),closeModal:()=>events.push('close'),render:()=>events.push('render'),flash:s=>events.push(s),MPosCore:{OrderContextRead:{calculate:input=>new Promise((resolve,reject)=>calls.push({input,resolve,reject}))}}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(read('Web/js/features/cart-presentation.js'),ctx);vm.runInContext(read('native-order-context-queue.js'),ctx);vm.runInContext(read('native-order-settings.js'),ctx);return{ctx,nodes,events,calls};}
function result(c){return {orderLabel:c.input.fields.label.trim(),name:c.input.fields.name.trim(),phone:c.input.fields.phone.trim(),address:c.input.fields.address.trim()};}
test('local form preserves identity, extensions, loyalty and comment; same persistence/close/render order',async()=>{const h=host(),customer=h.ctx.state.customer,gifts=h.ctx.state.loyaltyPrograms,p=h.ctx.saveOrderSettings();await tick();assert.equal(h.events.length,0);h.calls[0].resolve(result(h.calls[0]));await p;assert.equal(h.ctx.state.customer,customer);assert.equal(customer.id,'customer-1');assert.equal(customer.extension.keep,true);assert.equal(h.ctx.state.loyaltyPrograms,gifts);assert.equal(h.ctx.state.orderComment,'Комментарий WEB');assert.equal(customer.phone,'customer-phone');assert.deepEqual(h.events,['save','close','render']);});
test('late form result is discarded after field edit, replacement, close, cart/customer/context change or rollback',async()=>{for(const change of [h=>h.nodes['customer-phone'].value='edited',h=>h.nodes['order-label']={value:'  order-label  '},h=>h.ctx.closeModal(),h=>h.ctx.state.cart=[],h=>h.ctx.state.customer={},h=>h.ctx.state.orderComment='new',h=>h.ctx.MPosNativeOrderSettingsEnabled=false]){const h=host(),p=h.ctx.saveOrderSettings();await tick();change(h);const snapshot=JSON.stringify(h.ctx.state);h.calls[0].resolve(result(h.calls[0]));await p;assert.equal(JSON.stringify(h.ctx.state),snapshot);assert.ok(!h.events.includes('save'));}});
test('failed or malformed reply keeps editable form and state',async()=>{for(const malformed of [false,true]){const h=host(),before=JSON.stringify(h.ctx.state),p=h.ctx.saveOrderSettings();await tick();if(malformed)h.calls[0].resolve({name:1});else h.calls[0].reject(Error('bridge'));await p;assert.equal(JSON.stringify(h.ctx.state),before);assert.ok(!h.events.includes('close'));assert.equal(h.ctx.MPosCore.OrderContext.hasPending(),false);}});
test('double save closes once and cancels queued obsolete form command; rollback uses reviewed function',async()=>{const h=host(),a=h.ctx.saveOrderSettings(),b=h.ctx.saveOrderSettings();await tick();h.calls[0].resolve(result(h.calls[0]));await a;await b;assert.equal(h.calls.length,1);assert.deepEqual(h.events,['save','close','render']);const r=host();r.ctx.MPosNativeOrderSettingsEnabled=false;r.ctx.saveOrderSettings();assert.equal(r.calls.length,0);assert.equal(r.ctx.state.customer.phone,'customer-phone');});
test('ECMAScript trim fixture comes from reviewed form, including BOM, NBSP, NEL and NUL',()=>{const cases=JSON.parse(fs.readFileSync('tests/fixtures/order-context.json'));for(const c of cases){const h=host();h.ctx.MPosNativeOrderSettingsEnabled=false;for(const [key,id] of Object.entries({label:'order-label',name:'customer-name',phone:'customer-phone',address:'customer-address'}))h.nodes[id].value=c.input.fields[key];h.ctx.saveOrderSettings();assert.deepEqual({orderLabel:h.ctx.state.orderLabel,name:h.ctx.state.customer.name,phone:h.ctx.state.customer.phone,address:h.ctx.state.customer.address},c.expected);}});
