const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const root='app/src/main/assets/pos/',source=fs.readFileSync(root+'Web/js/features/payment.js','utf8'),adapter=fs.readFileSync(root+'native-cart-totals.js','utf8');
const cases=JSON.parse(fs.readFileSync('tests/fixtures/split-plans.json'));
const plain=v=>JSON.parse(JSON.stringify(v));
test('initial split golden fixtures match the actual reviewed payment source',()=>{const ctx={};vm.createContext(ctx);vm.runInContext(source,ctx);for(const c of cases)assert.deepEqual(plain(ctx.buildSplitPayments(c.count,c.total)),c.expected)});
function host(){let resolve;const ctx={state:{cart:[{productId:'p',price:10.01,qty:1}],discounts:[],orderType:'',deliveryFee:0,loyaltyPrograms:[],loyaltyRedemptions:{}},MPosCore:{CartTotals:{calculate:()=>new Promise(r=>resolve=r)}}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(source,ctx);const original=ctx.buildSplitPayments;vm.runInContext(adapter,ctx);return {ctx,original,resolve:v=>resolve(v)}}
const quote=()=>({pricing:{lines:[{discount:0,total:10.01}],subtotal:10.01,total:10.01,productDiscountTotal:0,subtotalBeforeDiscounts:10.01},loyalty:{discount:0,allocations:{},programDiscounts:{},snapshot:{}},splitPlans:Object.fromEntries(cases.filter(c=>c.total===10.01).map(c=>[c.count,c.expected]))});
test('matching native quote supplies independent parts; edits, disabled flags and missing plans preserve compatibility',async()=>{const h=host(),p=h.ctx.MPosCore.PaymentTotals.prepare();h.resolve(quote());assert.equal(await p,true);assert.deepEqual(plain(h.ctx.buildSplitPayments(3,10.01)),cases.find(c=>c.total===10.01&&c.count===3).expected);let parts=h.ctx.buildSplitPayments(3,10.01);parts[0].paid=true;assert.equal(h.ctx.buildSplitPayments(3,10.01)[0].paid,false);for(const flag of ['MPosNativeSplitPlansEnabled','MPosNativeCartTotalsEnabled']){h.ctx[flag]=false;assert.equal(h.ctx.MPosCore.PaymentTotals.split(3,10.01),null);assert.deepEqual(plain(h.ctx.buildSplitPayments(3,10.01)),plain(h.original(3,10.01)));h.ctx[flag]=true;}h.ctx.state.cart[0].qty=2;assert.equal(h.ctx.MPosCore.PaymentTotals.split(3,10.01),null);assert.deepEqual(plain(h.ctx.buildSplitPayments(3,20.02)),plain(h.original(3,20.02)));});
test('malformed native parts and a different total never replace the original distribution',async()=>{for(const mutate of [v=>delete v.splitPlans,v=>v.splitPlans[3][0].paid=true,v=>v.splitPlans[3][0].amount=99]){const h=host(),v=quote();mutate(v);const p=h.ctx.MPosCore.PaymentTotals.prepare();h.resolve(v);await p;assert.equal(h.ctx.MPosCore.PaymentTotals.split(3,10.01),null);assert.deepEqual(plain(h.ctx.buildSplitPayments(3,10.01)),plain(h.original(3,10.01)));assert.equal(h.ctx.MPosCore.PaymentTotals.split(3,11),null)}});

test('the initial two-part plan comes from native quote rather than recomputing the source',async()=>{const h=host(),v=quote();v.splitPlans[2][0].nativeFixtureMarker='native';const p=h.ctx.MPosCore.PaymentTotals.prepare();h.resolve(v);await p;assert.equal(h.ctx.buildSplitPayments(2,10.01)[0].nativeFixtureMarker,'native');assert.equal(h.ctx.state._splitPayments,undefined);});
