const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const adapter=fs.readFileSync('app/src/main/assets/pos/native-loyalty-guard.js','utf8'),payment=fs.readFileSync('app/src/main/assets/pos/Web/js/features/payment.js','utf8'),cases=JSON.parse(fs.readFileSync('tests/fixtures/loyalty-eligibility.json'));
function host(){const sent=[],calls=[],events=[],timers=new Map();let timer=0;const c={state:{customer:{id:'c'},loyaltyRedemptions:{gift:1},loyaltyPrograms:[{id:'old'}]},webkit:{messageHandlers:{network:{postMessage:p=>sent.push(p)}}},networkConfigFromState:()=>({backendUrl:'https://example.invalid',deviceKey:'synthetic-test-key'}),setTimeout:fn=>{timers.set(++timer,fn);return timer},clearTimeout:id=>timers.delete(id),loyaltyApi:async()=>({legacy:true}),closeModal(){},render(){},flash:m=>events.push(m),showModal:html=>events.push(html),MPosCore:{LoyaltyEligibility:{calculate:input=>new Promise((resolve,reject)=>calls.push({input,resolve,reject}))}}};c.window=c;vm.createContext(c);vm.runInContext(payment,c);vm.runInContext(adapter,c);return{c,sent,calls,events,timers}}
function reply(h,data){const r=h.sent.findLast(p=>p.action==='loyaltyProfile');h.c.__nativeNetworkResult({requestId:r.requestId,ok:true,authoritative:true,data})}
const tick=()=>new Promise(r=>setImmediate(r));
test('gift decision requires native server read and model before program replacement',async()=>{const h=host(),p=h.c.revalidateSelectedLoyaltyReward();assert.equal(h.sent[0].customerId,'c');reply(h,{programs:[{id:'gift',rewards:1}]});await tick();assert.equal(h.c.state.loyaltyPrograms[0].id,'old');h.calls[0].resolve({valid:true});assert.equal(await p,true);assert.equal(h.c.state.loyaltyPrograms[0].id,'gift');assert.equal(h.timers.size,0)});
test('insufficient gift refuses and preserves previously loaded programs',async()=>{const h=host(),p=h.c.revalidateSelectedLoyaltyReward();reply(h,{programs:[]});await tick();h.calls[0].resolve({valid:false});assert.equal(await p,false);assert.equal(h.c.state.loyaltyPrograms[0].id,'old')});
test('timeout cancels native read and keeps explicit offline choice',async()=>{const h=host();let paid=0;const p=h.c.beginPaymentWithLoyaltyGuard(()=>++paid);h.timers.values().next().value();assert.equal(await p,false);assert.equal(h.sent.at(-1).action,'loyaltyProfileCancel');assert.equal(paid,0);assert.equal(h.c.state.loyaltyRedemptions.gift,1);h.c.continuePaymentWithoutLoyalty();assert.equal(paid,1);assert.deepEqual(JSON.parse(JSON.stringify(h.c.state.loyaltyRedemptions)),{});});
test('customer or redemption changes reject late response and never invoke payment',async()=>{for(const mutate of [h=>h.c.state.customer={id:'other'},h=>h.c.state.loyaltyRedemptions.gift=2]){const h=host(),p=h.c.revalidateSelectedLoyaltyReward();mutate(h);reply(h,{programs:[{id:'gift',rewards:9}]});assert.equal(await p,false);assert.equal(h.calls.length,0)}});
test('external cancellation propagates AbortError and ignores late callback',async()=>{const h=host(),controller=new AbortController(),p=h.c.loyaltyApi('/api/customers/c/loyalty',{signal:controller.signal});controller.abort();await assert.rejects(p,{name:'AbortError'});reply(h,{programs:[]});assert.equal(h.timers.size,0)});
test('non-profile routes and explicit rollback preserve reviewed API',async()=>{const h=host();assert.equal((await h.c.loyaltyApi('/api/customers/search?q=375')).legacy,true);h.c.MPosNativeLoyaltyGuardEnabled=false;assert.equal((await h.c.loyaltyApi('/api/customers/c/loyalty')).legacy,true);assert.equal(h.sent.length,0)});
test('no customer or selected gift skips network; non-authoritative reply cannot grant gift',async()=>{const h=host();h.c.state.customer=null;assert.equal(await h.c.revalidateSelectedLoyaltyReward(),true);assert.equal(h.sent.length,0);h.c.state.customer={id:'c'};const p=h.c.revalidateSelectedLoyaltyReward();h.c.__nativeNetworkResult({requestId:h.sent[0].requestId,ok:true,authoritative:false,data:{programs:[{rewards:9}]}});assert.equal(await p,null);assert.equal(h.calls.length,0)});
test('eligibility fixtures match actual reviewed payment guard',async()=>{for(const fixture of cases){const state={customer:{id:'c'},loyaltyRedemptions:fixture.input.redemptions,loyaltyPrograms:[]},c={state,loyaltyApi:async()=>({programs:fixture.input.programs})};c.window=c;vm.createContext(c);vm.runInContext(payment,c);assert.equal(c.hasSelectedLoyaltyReward(),fixture.expected.selected);const result=await c.revalidateSelectedLoyaltyReward();assert.equal(result,fixture.expected.selected?fixture.expected.valid:true)}});
test('changed context during native model cannot grant gift and offline cancel never pays',async()=>{const h=host(),p=h.c.revalidateSelectedLoyaltyReward();reply(h,{programs:[{id:'gift',rewards:1}]});await tick();h.c.state.loyaltyRedemptions={gift:2};h.calls[0].resolve({valid:true});assert.equal(await p,false);assert.equal(h.c.state.loyaltyPrograms[0].id,'old');let paid=0;h.c.__offlinePaymentAction=()=>++paid;h.c.cancelOfflinePayment();assert.equal(paid,0);assert.equal(h.c.__offlinePaymentAction,null)});
