const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('app/src/main/assets/pos/native-admin-settings.js','utf8');
function host(){const commits=[],events=[],network={backendUrl:'https://example.invalid',deviceKey:'synthetic-device-key',deviceName:'Tablet',lastSyncAt:null,lastSyncStatus:''};
 const c={state:{network,telegram:{enabled:false,botToken:'',chatId:''}},networkConfigFromState:()=>c.state.network,document:{getElementById:id=>({value:id==='network-backend-url'?'https://new.invalid':'',checked:false})},saveNetworkSettings:()=>events.push('legacy-network'),saveTelegramSettings:()=>events.push('legacy-telegram'),syncTelegramBackendSettings:async()=>{events.push('backend');return false},flash:x=>events.push(x),markStorageBroken:()=>events.push('broken'),closeModal:()=>events.push('close'),render:()=>events.push('render'),MPosCore:{AdminSettingsCommands:{commit:input=>new Promise((resolve,reject)=>commits.push({input,resolve,reject}))}}};c.window=c;vm.createContext(c);vm.runInContext(source,c);return{c,commits,events};}
test('network configuration changes memory only after native permission and durable acknowledgement',async()=>{const h=host(),p=h.c.saveNetworkSettings();assert.equal(h.c.state.network.backendUrl,'https://example.invalid');assert.equal(h.commits[0].input.fields.backendUrl,'https://new.invalid');h.commits[0].resolve({settings:{backendUrl:'https://new.invalid',deviceKey:'synthetic-device-key'}});assert.equal(await p,true);assert.equal(h.c.state.network.backendUrl,'https://new.invalid');});
test('telegram backend update follows local commit and preserves previous return semantics on backend failure',async()=>{const h=host(),p=h.c.saveTelegramSettings(true);assert.equal(h.events.length,0);h.commits[0].resolve({settings:{enabled:false,botToken:'synthetic-token'}});assert.equal(await p,false);assert.deepEqual(h.events.slice(0,3),['close','render','backend']);assert.equal(h.c.state.telegram.botToken,'synthetic-token');});
test('live permission rejection leaves settings and effects unchanged',async()=>{const h=host(),p=h.c.saveTelegramSettings(true);h.commits[0].reject(Error('Сетевые конфигурации доступны только администратору'));assert.equal(await p,false);assert.equal(h.c.state.telegram.botToken,'');assert.equal(h.events.includes('backend'),false);});
test('uncertain settings result blocks another save and a late acknowledgement',async()=>{const h=host(),p=h.c.saveNetworkSettings();h.commits[0].reject(Error('commit status is uncertain'));assert.equal(await p,false);h.commits[0].resolve({settings:{backendUrl:'https://late.invalid'}});assert.equal(await h.c.saveNetworkSettings(),false);assert.equal(h.commits.length,1);assert.equal(h.c.state.network.backendUrl,'https://example.invalid');});
test('explicit rollback uses reviewed handlers',async()=>{const h=host();h.c.MPosNativeAdminSettingsEnabled=false;await h.c.saveNetworkSettings();await h.c.saveTelegramSettings();assert.deepEqual(h.events,['legacy-network','legacy-telegram']);});
