const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('app/src/main/assets/pos/Web/js/features/product-persistence.js','utf8');
function host(){const commits=[],effects=[],legacy=[];
 const product={id:'p',name:'Old',category:'Drinks',price:2,type:'simple',cost:1,stock:5,availableOnline:false,availableInOnlineMenu:false,description:'',modifierGroups:[]};
 const fields={'pf-name':'New','pf-category':'Drinks','pf-price':'2','pf-stock':'5','pf-cost':'1','pf-symbol':'','pf-no-stock':''};
 const c={state:{products:[product]},_pmType:'simple',_pmComponents:[],_pmModifierGroups:[],_pmOnline:false,_pmOnlineMenu:false,_pmLocalImageId:null,criticalStorageRecoveryPending:false,getProduct:id=>id==='p'?c.state.products[0]:null,currentShiftEmployeeIsAdmin:()=>false,document:{getElementById:id=>id in fields?{value:fields[id],checked:false}:null,querySelector:()=>null},limitTileSymbol:x=>x,hasUnreturnedStockConsumption:()=>false,validateModifierGroups:()=>{},normalizeModifierGroup:x=>x,saveProductConfiguration:()=>{},storageSnapshot:x=>JSON.parse(JSON.stringify(x)),syncCategoryOrder:()=>effects.push('categories'),publishAvailability:()=>effects.push('availability'),closeModal:()=>effects.push('close'),render:()=>effects.push('render'),flash:x=>effects.push(x),markStorageBroken:()=>effects.push('broken'),PrilavokCore:{Storage:{set:async(k,v)=>legacy.push({k,v})}},MPosCore:{ProductEditorCommands:{enabled:()=>c.MPosNativeProductEditorCommitEnabled!==false,commit:input=>new Promise((resolve,reject)=>commits.push({input,resolve,reject}))},EditorAuthorization:{grants:()=>({stock:'synthetic-grant'}),clear:()=>effects.push('clear-grants')}}};c.window=c;vm.createContext(c);vm.runInContext(source,c);return{c,commits,effects,legacy};}
test('reviewed form submits native command with expected products and grants before memory and effects',async()=>{const h=host(),p=h.c.saveProduct('p');assert.equal(h.commits.length,1);assert.equal(h.commits[0].input.expected[0].name,'Old');assert.equal(h.commits[0].input.nextProducts[0].name,'New');assert.equal(h.commits[0].input.grants.stock,'synthetic-grant');assert.equal(h.c.state.products[0].name,'Old');assert.equal(h.effects.length,0);h.commits[0].resolve({ok:true});assert.equal(await p,true);assert.equal(h.c.state.products[0].name,'New');assert.equal(h.effects[0],'clear-grants');assert.equal(h.legacy.length,0);});
test('rejected durable write leaves product and post-commit effects unchanged',async()=>{const h=host(),p=h.c.saveProduct('p');h.commits[0].reject(Error('Изменение остатка требует разрешения администратора'));await p;assert.equal(h.c.state.products[0].name,'Old');assert.equal(h.effects.includes('categories'),false);assert.equal(h.effects.includes('availability'),false);assert.equal(h.effects.includes('clear-grants'),false);});
test('uncertain write raises restart recovery gate and does not apply a late result',async()=>{const h=host(),p=h.c.saveProduct('p');h.commits[0].reject(Error('commit status is uncertain'));await p;assert.equal(h.c.criticalStorageRecoveryPending,true);h.commits[0].resolve({ok:true});assert.equal(h.c.state.products[0].name,'Old');assert.equal(h.effects.includes('broken'),true);});
test('explicit rollback retains original storage boundary',async()=>{const h=host();h.c.MPosNativeProductEditorCommitEnabled=false;assert.equal(await h.c.saveProduct('p'),true);assert.equal(h.commits.length,0);assert.equal(h.legacy.length,1);});
