const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function host(){const calls=[],fallback=[],ctx={state:{parked:[{id:'p',items:[{qty:1}],extra:{x:1}}],cart:[]},criticalStorageRecoveryPending:false,MPosCore:{ParkedOrders:{commit:async c=>{calls.push(c);return{ok:true}}}},commitCriticalStorage:async(...a)=>fallback.push(a)};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync('app/src/main/assets/pos/native-parked-command.js','utf8'),ctx);return{ctx,calls,fallback};}
test('parked commands freeze expected/candidate data and identify removed receipt',async()=>{const h=host(),writes={parked:[],currentOrderSession:{items:[{qty:1}]}};await h.ctx.commitCriticalStorage('resume-parked',writes);assert.equal(h.calls[0].id,'p');assert.equal(h.calls[0].cartEmpty,true);writes.currentOrderSession.items[0].qty=7;h.ctx.state.parked[0].extra.x=9;assert.equal(h.calls[0].writes.currentOrderSession.items[0].qty,1);assert.equal(h.calls[0].expected[0].extra.x,1);assert.equal(h.fallback.length,0);});
test('unrelated commands and explicit rollback use original storage path',async()=>{const h=host();await h.ctx.commitCriticalStorage('payment',{});h.ctx.MPosNativeParkedCommandsEnabled=false;await h.ctx.commitCriticalStorage('delete-parked',{parked:[]});assert.equal(h.fallback.length,2);assert.equal(h.calls.length,0);});
test('pending context prevents cutover; uncertain acknowledgement blocks subsequent operations',async()=>{const h=host();h.ctx.MPosCore.OrderContext={hasPending:()=>true};await assert.rejects(h.ctx.commitCriticalStorage('delete-parked',{parked:[]}));assert.equal(h.calls.length,0);h.ctx.MPosCore.OrderContext.hasPending=()=>false;h.ctx.MPosCore.ParkedOrders.commit=async()=>{throw Error('commit status is uncertain')};await assert.rejects(h.ctx.commitCriticalStorage('delete-parked',{parked:[]}));assert.equal(h.ctx.criticalStorageRecoveryPending,true);await assert.rejects(h.ctx.commitCriticalStorage('park-order',{parked:[]}));});
function sourceHost(){const calls=[],events=[],ctx={state:{parked:[],cart:[{productId:'x',qty:2,price:3}],customer:{id:'c',name:'Name'},employees:[],orderLabel:'Table',orderType:'Доставка',deliveryFee:0,deliveryTariffSelected:true},criticalOperationBusy:false,criticalStorageRecoveryPending:false,uid:()=> 'p',currentShift:()=>null,getProduct:()=>({category:'Food'}),cartTotal:()=>6,cartSubtotal:()=>6,storageSnapshot:v=>JSON.parse(JSON.stringify(v)),emptyCurrentOrderSession:()=>({items:[]}),resetCurrentOrderState(){ctx.state.cart=[]},render:()=>events.push('render'),flash:s=>events.push(s),closeModal:()=>events.push('close'),openParkedModal:()=>events.push('list'),loadCustomerLoyalty:async()=>events.push('loyalty'),modifierSelectionSignature:()=>'',printKitchenOrderNow:()=>events.push('print'),MPosCore:{ParkedOrders:{commit:input=>new Promise((resolve,reject)=>calls.push({input,resolve,reject}))}},commitCriticalStorage:()=>{throw Error('unexpected legacy commit')}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync('app/src/main/assets/pos/Web/js/features/parked-orders.js','utf8'),ctx);vm.runInContext(fs.readFileSync('app/src/main/assets/pos/native-parked-command.js','utf8'),ctx);return{ctx,calls,events};}
const tick=()=>new Promise(r=>setImmediate(r));
test('reviewed park flow changes cart and prints only after native durable acknowledgement',async()=>{const h=sourceHost(),p=h.ctx.parkOrderNow();assert.equal(h.calls[0].input.operation,'park-order');assert.equal(h.ctx.state.cart.length,1);assert.equal(h.events.length,0);h.calls[0].resolve({ok:true});await tick();assert.equal(h.ctx.state.cart.length,0);assert.equal(h.events[0],'print');assert.equal(h.calls[1].input.operation,'park-order-print-state');h.calls[1].resolve({ok:true});assert.equal(await p,true);assert.equal(h.ctx.state.parked[0].kitchenPrinted,true);});
test('reviewed resume restores WEB/customer context and starts loyalty only after native commit',async()=>{const h=sourceHost();h.ctx.state.cart=[];h.ctx.state.parked=[{id:'p',items:[{productId:'x',qty:2}],customer:{id:'c',extra:7},comment:'WEB',source:'web',webOrderId:'w',deliveryTariffSelected:true,printedItems:[]}];const p=h.ctx.resumeParked('p');assert.equal(h.events.length,0);assert.equal(h.ctx.state.parked.length,1);h.calls[0].resolve({ok:true});assert.equal(await p,true);assert.equal(h.ctx.state.currentWebOrderId,'w');assert.equal(h.ctx.state.customer.extra,7);assert.deepEqual(h.events,['close','render','loyalty']);});
test('reviewed hold failure preserves current cart and parked list and suppresses kitchen printing',async()=>{const h=sourceHost(),p=h.ctx.parkOrderNow();h.calls[0].reject(Error('local write'));assert.equal(await p,false);assert.equal(h.ctx.state.cart.length,1);assert.equal(h.ctx.state.parked.length,0);assert.ok(!h.events.includes('print'));});
