const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const root='app/src/main/assets/pos/',read=p=>fs.readFileSync(root+p,'utf8'),source=read('Web/js/features/payment.js'),fixtures=JSON.parse(fs.readFileSync('tests/fixtures/split-recovery.json'));
const plain=v=>JSON.parse(JSON.stringify(v)),tick=()=>new Promise(r=>setImmediate(r));
function reference(input){const x={Date:{now:()=>123456},state:{_splitPayments:structuredClone(input.parts||[])}};vm.createContext(x);vm.runInContext(source,x);if(input.operation==='restore')return plain(x.validateSplitPaymentDraft(input.draft,input.expectedTotal));x.normalizeSplitPayments(input.total);return {parts:plain(x.state._splitPayments),count:x.state._splitCount??null};}
test('restart and normalization fixtures reflect the actual reviewed synchronous validators',()=>{for(const c of fixtures.normal)assert.deepEqual(reference(c.input),c.expected);for(const c of fixtures.restore)assert.deepEqual(reference(c.input),c.expected)});
function host(){const calls=[],messages=[];const ctx={Date:{now:()=>123456},state:{cart:[{productId:'p',price:10.01,qty:1}],paymentPage:'main',_splitPayments:[{method:'card',amount:2,paid:false,cashGiven:null,change:null},{method:'cash',amount:8.01,paid:false,cashGiven:10,change:1.99}]},cartTotal:()=>10.01,flash:s=>messages.push(s),MPosCore:{SplitCount:{calculate(){}},Storage:{get:async()=>[]},SplitRecoveryRead:{calculate:input=>new Promise((resolve,reject)=>calls.push({input,resolve,reject}))}}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(source,ctx);ctx.renderPaymentScreen=()=>ctx.screen=true;ctx.renderSplitPayment=()=>ctx.rendered=true;ctx.closeModal=()=>{};vm.runInContext(read('native-split-count.js'),ctx);vm.runInContext(read('native-split-recovery.js'),ctx);return {ctx,calls,messages};}
const session=()=>({items:[{productId:'p',price:10.01,qty:1}],orderType:'На месте',deliveryFee:0,paymentDraft:structuredClone(fixtures.restore[0].input.draft)});
test('open existing unpaid split waits for native normalization and retains tender/identity',async()=>{const h=host(),parts=h.ctx.state._splitPayments,first=parts[0],p=h.ctx.openSplitPayment();await tick();assert.equal(h.ctx.rendered,undefined);assert.equal(h.ctx.MPosCore.SplitPayments.hasPending(),true);const e=reference(h.calls[0].input);h.calls[0].resolve({changed:true,...e});assert.equal(await p,true);assert.equal(h.ctx.rendered,true);assert.equal(h.ctx.state._splitPayments,parts);assert.equal(parts[0],first);assert.equal(parts[0].amount,5.01);assert.equal(parts[1].amount,5);assert.equal(parts[1].cashGiven,10)});
test('paid split reopening preserves the original guard without any redistribution read',async()=>{const h=host();h.ctx.state._splitPayments[0].paid=true;assert.equal(await h.ctx.openSplitPayment(),true);assert.equal(h.calls.length,0);assert.equal(h.ctx.state._splitPayments[0].amount,2)});
test('normalization failure or stale response cannot open or mutate the payment page',async()=>{for(const mode of ['close','cart','error','paid']){const h=host(),p=h.ctx.openSplitPayment();await tick();const before=plain(h.ctx.state._splitPayments);if(mode==='close')h.ctx.closeModal();if(mode==='cart')h.ctx.state.cart=[];if(mode==='error')h.calls[0].reject(Error('bridge'));else{const e=reference(h.calls[0].input);if(mode==='paid')e.parts[0].paid=true;h.calls[0].resolve({changed:true,...e})}assert.equal(await p,false);assert.deepEqual(plain(h.ctx.state._splitPayments),before);assert.equal(h.ctx.rendered,undefined)}});
test('startup caches native validated draft only for matching source draft and current total',async()=>{const h=host(),s=session(),p=h.ctx.MPosCore.SplitRecovery.prepare(s);await tick();const draft=reference({...h.calls[0].input,expectedTotal:10.01});draft.nativeFixtureMarker=true;h.calls[0].resolve({valid:true,expectedTotal:10.01,draft});await p;const a=h.ctx.validateSplitPaymentDraft(s.paymentDraft,10.01);assert.equal(a.nativeFixtureMarker,true);a.parts[0].paid=false;assert.equal(h.ctx.validateSplitPaymentDraft(s.paymentDraft,10.01).parts[0].paid,true);assert.equal(h.ctx.validateSplitPaymentDraft(s.paymentDraft,11),null);h.ctx.MPosNativeSplitRecoveryEnabled=false;assert.equal(h.ctx.validateSplitPaymentDraft(s.paymentDraft,10.01).nativeFixtureMarker,undefined)});
test('read failure retains reviewed paid restoration and never clears or rewrites stored session',async()=>{const h=host(),s=session(),before=plain(s),p=h.ctx.MPosCore.SplitRecovery.prepare(s);await tick();h.calls[0].reject(Error('native unavailable'));await p;assert.equal(h.ctx.validateSplitPaymentDraft(s.paymentDraft,10.01).parts[0].paid,true);assert.deepEqual(s,before)});
test('native invalid draft is rejected while different draft uses the reviewed compatibility path',async()=>{const h=host(),s=session(),p=h.ctx.MPosCore.SplitRecovery.prepare(s);await tick();h.calls[0].resolve({valid:false,expectedTotal:10.01,draft:null});await p;assert.equal(h.ctx.validateSplitPaymentDraft(s.paymentDraft,10.01),null);const other=structuredClone(s.paymentDraft);other.updatedAt++;assert.ok(h.ctx.validateSplitPaymentDraft(other,10.01))});
