const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const adapter=fs.readFileSync('app/src/main/assets/pos/native-editor-authorization.js','utf8');
function host(){const sent=[],events=[],timers=new Map();let sequence=0;
 const product={id:'p',name:'Coffee',type:'simple',stock:5};
 const c={state:{theme:'light',categoryOrder:['Drinks']},_pmEditingId:'p',_pmType:'simple',_pmStockUnlocked:false,_pmNoStockUnlocked:false,getProduct:id=>id===product.id?product:null,openProductModal:()=>{c._pmSession=(c._pmSession||0)+1},closeModal:()=>events.push('close'),renderProductModal:()=>events.push('render'),flash:x=>events.push(x),requestStockUnlock:()=>events.push('legacy'),confirmStockUnlock:()=>events.push('legacy-confirm'),requestNoStockUnlock:()=>{},confirmNoStockUnlock:()=>{},setTimeout:fn=>{timers.set(++sequence,fn);return sequence},clearTimeout:id=>timers.delete(id),MPosCore:{Storage:{get:async()=>null}},webkit:{messageHandlers:{settingsScreen:{postMessage:p=>sent.push(p)}}}};c.window=c;vm.createContext(c);vm.runInContext(adapter,c);
 const ready=async()=>{for(let i=0;i<12;i++)await Promise.resolve()};
 const reply=r=>c.__mposEditorAuthorizationResult({requestId:sent[0].requestId,...r});return{c,sent,events,timers,product,ready,reply};}
test('native stock authorization exposes field-scoped grant only after correlated result',async()=>{const h=host(),p=h.c.requestStockUnlock();await h.ready();assert.equal(h.sent[0].command.operation,'stock');assert.equal(h.sent[0].command.expected.stock,5);assert.equal(h.c._pmStockUnlocked,false);assert.equal(h.timers.size,0);h.reply({ok:true,granted:true,operation:'stock',productId:'p',grant:'synthetic-grant'});assert.equal(await p,true);assert.equal(h.c._pmStockUnlocked,true);assert.equal(h.c.MPosCore.EditorAuthorization.grants().stock,'synthetic-grant');assert.equal(h.c._pmNoStockUnlocked,false);assert.equal(JSON.stringify(h.sent).includes('password'),false);});
test('grant cannot move to a changed product or a newly opened editor',async()=>{const h=host(),p=h.c.requestNoStockUnlock();await h.ready();h.reply({ok:true,granted:true,operation:'no-stock',productId:'p',grant:'synthetic-grant'});assert.equal(await p,true);h.product.stock=6;assert.equal(Object.keys(h.c.MPosCore.EditorAuthorization.grants()).length,0);h.product.stock=5;h.c.openProductModal('p');assert.equal(Object.keys(h.c.MPosCore.EditorAuthorization.grants()).length,0);});
test('cancel reconstructs existing editor without unlocking either field',async()=>{const h=host(),p=h.c.requestStockUnlock();await h.ready();h.reply({cancelled:true});assert.equal(await p,false);assert.equal(h.c._pmStockUnlocked,false);assert.deepEqual(h.events,['close','render']);});
test('stale and uncorrelated authorization cannot unlock current editor',async()=>{const h=host(),p=h.c.requestStockUnlock();await h.ready();h.c.__mposEditorAuthorizationResult({requestId:'stale',ok:true});assert.equal(h.c._pmStockUnlocked,false);h.product.name='Changed';h.reply({ok:true,granted:true,operation:'stock',productId:'p',grant:'synthetic-grant'});assert.equal(await p,false);assert.equal(h.c._pmStockUnlocked,false);});
test('timeout blocks repeated authorization; duplicate confirm never dispatches a second command',async()=>{const h=host(),p=h.c.requestStockUnlock();await h.ready();assert.equal(await h.c.confirmStockUnlock(),false);assert.equal(h.sent.length,1);h.reply({action:'committing'});[...h.timers.values()][0]();assert.equal(await p,false);assert.equal(await h.c.requestStockUnlock(),false);assert.equal(h.sent.length,1);});
test('rollback restores reviewed authorization entry points',async()=>{const h=host();h.c.MPosNativeEditorAuthorizationEnabled=false;await h.c.requestStockUnlock();await h.c.confirmStockUnlock();assert.deepEqual(h.events,['legacy','legacy-confirm']);assert.equal(h.sent.length,0);});

test('reopening the same product while native confirmation is pending rejects old authorization',async()=>{const h=host(),p=h.c.requestStockUnlock();await h.ready();h.c.openProductModal('p');h.reply({ok:true,granted:true,operation:'stock',productId:'p',grant:'synthetic-grant'});assert.equal(await p,false);assert.equal(h.c._pmStockUnlocked,false);});
