const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const adapter=fs.readFileSync('app/src/main/assets/pos/native-company-command.js','utf8');
function host(){const calls=[],events=[];let admin=true;
 const c={state:{company:{establishmentName:'Old',legalName:'',address:'',deliveryAddress:''}},document:{getElementById:id=>({value:' '+id+' '})},currentShiftEmployeeIsAdmin:()=>admin,currentShift:()=>({id:'s'}),openCompanyEditModal:()=>{},saveCompanySettings:()=>events.push('legacy'),canEditCompanySettings:()=>false,closeModal:()=>events.push('close'),render:()=>events.push('render'),flash:x=>events.push(x),markStorageBroken:()=>events.push('broken'),MPosCore:{CompanyCommands:{commit:input=>new Promise((resolve,reject)=>calls.push({input,resolve,reject}))}}};c.window=c;vm.createContext(c);vm.runInContext(adapter,c);return {c,calls,events,setAdmin:v=>admin=v};}
test('save trims four fields, binds expected shift and applies memory only after acknowledgement',async()=>{const h=host(),p=h.c.saveCompanySettings();assert.equal(h.c.state.company.establishmentName,'Old');assert.equal(h.calls[0].input.shiftId,'s');assert.equal(h.calls[0].input.expected.establishmentName,'Old');assert.equal(h.calls[0].input.fields.establishmentName,'company-establishment-name');assert.equal(Object.keys(h.calls[0].input.fields).length,4);assert.equal(await h.c.saveCompanySettings(),false);h.calls[0].resolve({company:{legalName:'Saved'}});assert.equal(await p,true);assert.equal(h.c.state.company.legalName,'Saved');assert.deepEqual(h.events.slice(0,2),['close','render']);});
test('stale document rejection keeps form and memory without labelling permission conflict as storage failure',async()=>{const h=host(),p=h.c.saveCompanySettings();h.calls[0].reject(Error('Реквизиты изменились. Откройте форму заново'));assert.equal(await p,false);assert.equal(h.c.state.company.establishmentName,'Old');assert.equal(h.events.includes('close'),false);assert.equal(h.events.includes('broken'),false);});
test('cached UI permission prevents dispatch while native commit remains responsible for live permission',async()=>{const h=host();assert.equal(h.c.canEditCompanySettings(),true);h.setAdmin(false);assert.equal(await h.c.saveCompanySettings(),false);assert.equal(h.calls.length,0);});
test('uncertain save blocks retry until restart and cannot apply a late acknowledgement',async()=>{const h=host(),p=h.c.saveCompanySettings();h.calls[0].reject(Error('commit status is uncertain'));assert.equal(await p,false);h.calls[0].resolve({company:{legalName:'Late'}});assert.equal(await h.c.saveCompanySettings(),false);assert.equal(h.calls.length,1);assert.equal(h.c.state.company.establishmentName,'Old');assert.equal(h.events.includes('broken'),true);});
test('rollback restores reviewed save and permission handlers',async()=>{const h=host();h.c.MPosNativeCompanyCommandsEnabled=false;assert.equal(h.c.canEditCompanySettings(),false);await h.c.saveCompanySettings();assert.deepEqual(h.events,['legacy']);assert.equal(h.calls.length,0);});

test('editing binds document and shift when form opens rather than at submission',async()=>{const h=host();h.c.openCompanyEditModal();h.c.state.company.legalName='Newer';h.c.currentShift=()=>({id:'replacement'});const p=h.c.saveCompanySettings();assert.equal(h.calls[0].input.expected.legalName,'');assert.equal(h.calls[0].input.shiftId,'s');h.calls[0].reject(Error('Реквизиты изменились. Откройте форму заново'));assert.equal(await p,false);assert.equal(h.c.state.company.legalName,'Newer');});
