const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const base='app/src/main/assets/pos/',source=fs.readFileSync(base+'Web/js/features/payment.js','utf8'),adapter=fs.readFileSync(base+'native-split-count.js','utf8'),cases=JSON.parse(fs.readFileSync('tests/fixtures/split-count.json'));
const plain=v=>JSON.parse(JSON.stringify(v));
function reference(input){const ctx={state:{_splitPayments:structuredClone(input.parts)},cartTotal:()=>input.total,flash:s=>ctx.reason=s};vm.createContext(ctx);vm.runInContext(source,ctx);ctx.renderSplitPayment=()=>ctx.rendered=true;ctx.adjustSplitCount(input.delta);return {allowed:!ctx.reason,changed:!!ctx.rendered,parts:plain(ctx.state._splitPayments),count:ctx.state._splitCount??null};}
test('count fixtures are actual reviewed source behavior, including paid greater than remaining and no-ops',()=>{for(const c of cases)assert.deepEqual(reference(c.input),c.expected)});
function host(){const calls=[],messages=[];const ctx={state:{cart:[{productId:'p',qty:1}],_splitPayments:[{amount:5.01,paid:true,method:'card',cashGiven:null,change:null},{amount:5,paid:false,method:'cash',cashGiven:null,change:null}],paymentPage:'split'},cartTotal:()=>10.01,flash:s=>messages.push(s),closeModal(){},closePaymentPage(){},returnFromSplitPayment(){},MPosCore:{SplitCount:{calculate:input=>new Promise((resolve,reject)=>calls.push({input,resolve,reject}))}}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(source,ctx);ctx.renderSplitPayment=()=>ctx.rendered=(ctx.rendered||0)+1;ctx.closeModal=()=>{};ctx.closePaymentPage=()=>{};ctx.returnFromSplitPayment=()=>{};vm.runInContext(adapter,ctx);return {ctx,calls,messages};}
function answer(call){const expected=reference(call.input),paid=call.input.parts.map((p,i)=>p.paid?i:null).filter(i=>i!==null),unpaid=call.input.parts.map((p,i)=>!p.paid?i:null).filter(i=>i!==null),next=Math.max(2,Math.min(10,call.input.parts.length+call.input.delta));while(unpaid.length<next-paid.length)unpaid.push(-1);unpaid.length=Math.min(unpaid.length,next-paid.length);return {...expected,indices:[...paid,...unpaid]};}
const tick=()=>new Promise(r=>setImmediate(r));
test('rapid count clicks serialize; paid object identity and native payment guard remain stable',async()=>{const h=host(),paid=h.ctx.state._splitPayments[0],first=h.ctx.adjustSplitCount(1),second=h.ctx.adjustSplitCount(1);assert.equal(h.ctx.MPosCore.SplitPayments.hasPending(),true);await tick();assert.equal(h.calls.length,1);h.calls[0].resolve(answer(h.calls[0]));await first;await tick();assert.equal(h.calls.length,2);assert.equal(h.calls[1].input.parts.length,3);h.calls[1].resolve(answer(h.calls[1]));await second;assert.equal(h.ctx.state._splitPayments.length,4);assert.equal(h.ctx.state._splitPayments[0],paid);assert.equal(paid.amount,5.01);assert.equal(h.ctx.MPosCore.SplitPayments.hasPending(),false)});
test('close, cart replacement, paid mutation and method edits discard late results',async()=>{for(const edit of [h=>h.ctx.closeModal(),h=>h.ctx.state.cart=[],h=>h.ctx.state._splitPayments[1].paid=true,h=>h.ctx.state._splitPayments[1].method='card']){const h=host(),p=h.ctx.adjustSplitCount(1);await tick();edit(h);const before=plain(h.ctx.state._splitPayments);h.calls[0].resolve(answer(h.calls[0]));await p;assert.deepEqual(plain(h.ctx.state._splitPayments),before);assert.equal(h.ctx.rendered,undefined)}});
test('native error and malformed paid result keep rows intact; rollback calls source synchronously',async()=>{for(const mode of ['error','paid']){const h=host(),before=plain(h.ctx.state._splitPayments),p=h.ctx.adjustSplitCount(1);await tick();if(mode==='error')h.calls[0].reject(Error('bridge'));else{const value=answer(h.calls[0]);value.parts[0].amount=100;h.calls[0].resolve(value)}await p;assert.deepEqual(plain(h.ctx.state._splitPayments),before);assert.equal(h.messages.length,1)}const h=host();h.ctx.MPosNativeSplitCountEnabled=false;h.ctx.adjustSplitCount(1);assert.equal(h.ctx.state._splitPayments.length,3);assert.equal(h.calls.length,0)});
