const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),tick=()=>new Promise(r=>setImmediate(r)),script=fs.readFileSync('app/src/main/assets/pos/native-loyalty-outbox.js','utf8'),source=fs.readFileSync('app/src/main/assets/pos/Web/js/features/loyalty.js','utf8'),fixtures=JSON.parse(fs.readFileSync('tests/fixtures/loyalty-journal.json'));
function host(){const calls=[],sent=[],events=[],timers=new Map();let timer=0;const order=structuredClone(fixtures[0].before);const c={state:{orders:[order]},criticalStorageRecoveryPending:false,networkConfigFromState:()=>({backendUrl:'https://example.invalid',deviceKey:'synthetic-test-key'}),markStorageBroken:()=>events.push('broken'),setTimeout:fn=>{timers.set(++timer,fn);return timer},clearTimeout:id=>timers.delete(id),webkit:{messageHandlers:{network:{postMessage:p=>sent.push(p)}}},MPosCore:{LoyaltyJournal:{execute:input=>new Promise((resolve,reject)=>calls.push({input,resolve,reject}))}}};c.window=c;vm.createContext(c);vm.runInContext(source,c);vm.runInContext(script,c);return{c,calls,sent,events,timers,order}}
function claimed(h,kind='sale'){return{send:true,kind,token:'t',payload:{orderId:'o',customerId:'c'},order:{...structuredClone(h.order),[kind==='sale'?'loyaltySync':'loyaltyReversal']:{status:'sending'}}}}
function reply(h,data={events:[]},ok=true){const request=h.sent.findLast(p=>p.action==='loyaltyMutation');h.c.__nativeNetworkResult({requestId:request.requestId,ok,authoritative:true,data,message:'offline'})}
test('send waits for durable sending and result waits for durable finish',async()=>{const h=host(),p=h.c.publishPaidOrderLoyalty(h.order);assert.equal(h.sent.length,0);h.calls[0].resolve(claimed(h));await tick();assert.equal(h.order.loyaltySync.status,'sending');assert.equal(h.sent[0].action,'loyaltyMutation');reply(h);await tick();assert.equal(h.order.loyaltySync.status,'sending');assert.equal(h.calls[1].input.operation,'finish');assert.equal(h.calls[1].input.success,true);h.calls[1].resolve({order:{...h.order,loyaltySync:{status:'synced'}}});await p;assert.equal(h.order.loyaltySync.status,'synced');assert.equal(h.timers.size,0)});
test('claim failure prohibits network and uncertain write blocks more work',async()=>{const h=host();const p=h.c.publishPaidOrderLoyalty(h.order);h.calls[0].reject(Error('commit status is uncertain'));await p;assert.equal(h.sent.length,0);assert.equal(h.order.loyaltySync.status,'pending');assert.equal(h.c.criticalStorageRecoveryPending,true);await h.c.publishPaidOrderLoyalty(h.order);assert.equal(h.calls.length,1)});
test('duplicate call shares active attempt and timeout persists pending for allowed retry',async()=>{const h=host(),a=h.c.publishPaidOrderLoyalty(h.order),b=h.c.publishPaidOrderLoyalty(h.order);assert.equal(a,b);assert.equal(h.calls.length,1);h.calls[0].resolve(claimed(h));await tick();h.timers.values().next().value();await tick();assert.equal(h.sent.at(-1).action,'loyaltyProfileCancel');assert.equal(h.calls[1].input.success,false);h.calls[1].resolve({order:{...h.order,loyaltySync:{status:'pending'}}});await a;assert.equal(h.order.loyaltySync.status,'pending')});
test('recovery protects live attempts and dispatches only native eligible actions',async()=>{const h=host(),p=h.c.publishPaidOrderLoyalty(h.order);h.calls[0].resolve(claimed(h));await tick();const recover=h.c.retryPendingLoyalty();assert.ok(h.calls[1].input.active.includes('sale:o'));h.calls[1].resolve({orders:[],actions:[]});await recover;assert.equal(h.sent.length,1);reply(h);await tick();h.calls[2].resolve({});await p});
test('sale finish preserves a concurrent return in memory and chains reversal only after ack',async()=>{const h=host(),p=h.c.publishPaidOrderLoyalty(h.order);h.calls[0].resolve(claimed(h));await tick();h.order.returnedAt=11;h.order.loyaltyReversal={status:'pending',at:11};reply(h);await tick();h.calls[1].resolve({reverseNext:true,order:{...h.order,loyaltySync:{status:'synced'}}});await tick();assert.equal(h.calls[2].input.kind,'reversal');assert.equal(h.order.returnedAt,11);h.calls[2].resolve(claimed(h,'reversal'));await tick();reply(h,null);await tick();h.calls[3].resolve({order:{...h.order,loyaltyReversal:{status:'synced'}}});await p;assert.equal(h.order.loyaltyReversal.status,'synced')});
test('source fixtures cover original status gates payload and finish metadata',async()=>{for(const f of fixtures){const order=structuredClone(f.before),writes=[],requests=[],c={state:{orders:[order]},Date:{now:()=>10},markStorageBroken(){},PrilavokCore:{Storage:{set:async(k,v)=>writes.push(structuredClone(v[0]))}}};c.window=c;vm.createContext(c);vm.runInContext(source,c);c.loyaltyApi=async(path,options)=>{requests.push({path,body:JSON.parse(options.body)});if(!f.success)throw Error('offline');return{events:['event']}};await c[f.kind==='sale'?'publishPaidOrderLoyalty':'reverseOrderLoyalty'](order);assert.deepEqual(JSON.parse(JSON.stringify(order)),f.after);assert.deepEqual(requests,f.requests);assert.deepEqual(writes,f.writes)}});
test('rollback preserves original sale persistence and API; no customer skips journal',async()=>{const h=host();await h.c.publishPaidOrderLoyalty({id:'none'});assert.equal(h.calls.length,0);h.c.MPosNativeLoyaltyOutboxEnabled=false;const persisted=[];h.c.PrilavokCore={Storage:{set:async()=>persisted.push('saved')}};h.c.loyaltyApi=async()=>({events:[]});await h.c.publishPaidOrderLoyalty(h.order);assert.equal(persisted.length,2);assert.equal(h.order.loyaltySync.status,'synced');assert.equal(h.sent.length,0)});
test('failed final acknowledgement keeps sending for restart recovery and never resends immediately',async()=>{const h=host(),p=h.c.publishPaidOrderLoyalty(h.order);h.calls[0].resolve(claimed(h));await tick();reply(h);await tick();h.calls[1].reject(Error('disk failure'));await p;assert.equal(h.order.loyaltySync.status,'sending');assert.equal(h.sent.length,1);assert.ok(h.events.includes('broken'))});
test('loyalty workers are bounded at four and drain remaining pending receipts',async()=>{const h=host(),tasks=[];for(let i=0;i<6;i++){const order={id:'o'+i,customer:{id:'c'}};h.c.state.orders.push(order);tasks.push(h.c.publishPaidOrderLoyalty(order))}assert.equal(h.calls.length,4);for(const call of h.calls.slice())call.resolve({send:false});await tick();assert.equal(h.calls.length,6);for(const call of h.calls.slice(4))call.resolve({send:false});await Promise.all(tasks);assert.equal(h.sent.length,0)});
