const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const base='app/src/main/assets/pos/',read=p=>fs.readFileSync(base+p,'utf8');
const source=read('Web/js/features/cart-presentation.js')+'\n'+read('Web/js/features/loyalty.js')+'\n'+read('pos.html').match(/function cartTotal\(\)\{[\s\S]*?\n\}/)[0];
const cases=JSON.parse(fs.readFileSync('tests/fixtures/cart-totals.json'));
function host(c=cases[0]){const requests=[],x=structuredClone(c.input),ctx={state:{cart:x.items,discounts:x.discounts,orderType:x.orderType,deliveryFee:x.deliveryFee,loyaltyPrograms:x.programs,loyaltyRedemptions:x.redemptions},MPosCore:{CartTotals:{calculate:input=>new Promise((resolve,reject)=>requests.push({input,resolve,reject}))}}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(source,ctx);vm.runInContext(read('native-cart-totals.js'),ctx);return {ctx,requests}}
const plain=x=>JSON.parse(JSON.stringify(x));
test('combined pricing/gifts/delivery golden quotes retain reviewed exact arithmetic',async()=>{for(const c of cases){const h=host(c),s=h.ctx.state;const allocation=h.ctx.loyaltyRewardAllocation();const expected={pricing:{lines:s.cart.map(i=>({discount:h.ctx.discountValue(i),total:h.ctx.itemTotal(i)})),subtotal:h.ctx.cartSubtotal(),total:h.ctx.cartTotal(),productDiscountTotal:Math.round(s.cart.reduce((n,i)=>n+h.ctx.discountValue(i),0)*100)/100,subtotalBeforeDiscounts:Math.round(s.cart.reduce((n,i)=>n+Number(i.price||0)*Number(i.qty||0),0)*100)/100},loyalty:{...allocation,snapshot:h.ctx.loyaltyReceiptSnapshot(allocation)}};assert.deepEqual(plain(expected),c.expected,c.name);const p=h.ctx.MPosCore.PaymentTotals.prepare();h.requests[0].resolve(structuredClone(c.expected));if(!c.valid){await assert.rejects(p,/invalid native/);continue;}assert.equal(await p,true);assert.equal(h.ctx.cartTotal(),c.expected.pricing.total);assert.equal(h.ctx.cartSubtotal(),c.expected.pricing.subtotal);assert.deepEqual(plain(h.ctx.loyaltyReceiptSnapshot()),c.expected.loyalty.snapshot);for(const [n,i] of s.cart.entries()){assert.equal(h.ctx.itemTotal(i),c.expected.pricing.lines[n].total);assert.equal(h.ctx.discountValue(i),c.expected.pricing.lines[n].discount)}}});
test('native amount is used only for matching inputs; edits and rollback invalidate cache',async()=>{const h=host(),value=structuredClone(cases[0].expected);value.pricing.total=123.45;const p=h.ctx.MPosCore.PaymentTotals.prepare();h.requests[0].resolve(value);await p;assert.equal(h.ctx.cartTotal(),123.45);h.ctx.MPosNativeCartTotalsEnabled=false;assert.notEqual(h.ctx.cartTotal(),123.45);h.ctx.MPosNativeCartTotalsEnabled=true;h.ctx.state.cart[0].qty++;assert.notEqual(h.ctx.cartTotal(),123.45)});
test('pending quote freezes input and ignores edits; failure does not cache a zero total',async()=>{const h=host(),p=h.ctx.MPosCore.PaymentTotals.prepare();const before=h.requests[0].input.items[0].qty;h.ctx.state.cart[0].qty++;assert.equal(h.requests[0].input.items[0].qty,before);h.requests[0].resolve(structuredClone(cases[0].expected));assert.equal(await p,false);const bad=h.ctx.MPosCore.PaymentTotals.prepare();h.requests[1].resolve({pricing:{total:0}});await assert.rejects(bad,/invalid native/);const fail=h.ctx.MPosCore.PaymentTotals.prepare();h.requests[2].reject(Error('offline bridge'));await assert.rejects(fail,/offline bridge/)});
test('loyalty cache returns independent objects and explicit allocation retains reference helper',async()=>{const c=cases.find(c=>c.expected.loyalty.discount>0),h=host(c),p=h.ctx.MPosCore.PaymentTotals.prepare();h.requests[0].resolve(structuredClone(c.expected));await p;const a=h.ctx.loyaltyRewardAllocation();a.discount=999;assert.equal(h.ctx.loyaltyRewardDiscount(),c.expected.loyalty.discount);const snapshot=h.ctx.loyaltyReceiptSnapshot();snapshot.programs.length=0;assert.deepEqual(plain(h.ctx.loyaltyReceiptSnapshot()),c.expected.loyalty.snapshot);assert.equal(h.ctx.loyaltyReceiptSnapshot({discount:0,allocations:{},programDiscounts:{}}).discount,0)});

test('non-finite JS numbers cannot be serialized to null and become a zero quote',async()=>{for(const value of [NaN,Infinity,-Infinity]){const h=host();h.ctx.state.cart[0].price=value;await assert.rejects(h.ctx.MPosCore.PaymentTotals.prepare(),/non-finite/);assert.equal(h.requests.length,0)}});
