const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),tick=()=>new Promise(r=>setImmediate(r));
const source=fs.readFileSync('app/src/main/assets/pos/Web/js/features/loyalty.js','utf8'),adapter=fs.readFileSync('app/src/main/assets/pos/native-customer-command.js','utf8'),queue=fs.readFileSync('app/src/main/assets/pos/native-order-context-queue.js','utf8'),cases=JSON.parse(fs.readFileSync('tests/fixtures/customer-context.json'));
function host(){const calls=[],writes=[],network=[],events=[];const session=structuredClone(cases[4].input.session),state={cart:session.items,customer:session.customer,loyaltyPrograms:session.loyaltyPrograms,loyaltyRedemptions:session.loyaltyRedemptions,loyaltyCustomerId:session.loyaltyCustomerId};const c={state,criticalStorageRecoveryPending:false,document:{querySelector(){return null}},currentOrderSessionSnapshot:()=>({...structuredClone(session),customer:structuredClone(state.customer),loyaltyPrograms:structuredClone(state.loyaltyPrograms),loyaltyRedemptions:structuredClone(state.loyaltyRedemptions),loyaltyCustomerId:state.loyaltyCustomerId}),saveCurrentOrderSession:()=>events.push('legacy-save'),closeModal:()=>events.push('close'),render:()=>events.push('render'),flash:s=>events.push(s),markStorageBroken:()=>events.push('broken'),MPosCore:{CustomerContext:{calculate:input=>new Promise((resolve,reject)=>calls.push({input,resolve,reject}))},Storage:{set:(key,value)=>new Promise((resolve,reject)=>writes.push({key,value,resolve,reject}))}}};c.window=c;vm.createContext(c);vm.runInContext(source,c);c.loyaltyApi=path=>new Promise((resolve,reject)=>network.push({path,resolve,reject}));vm.runInContext(queue,c);vm.runInContext(adapter,c);return{c,calls,writes,network,events}}
function model(input){const s=structuredClone(input.session);if(input.operation==='select'){s.customer={...s.customer,...input.customer};s.loyaltyPrograms=[];s.loyaltyRedemptions={};s.loyaltyCustomerId=''}else if(input.operation==='remove'){s.customer={name:'',phone:'',address:s.customer.address||''};s.loyaltyPrograms=[];s.loyaltyRedemptions={};s.loyaltyCustomerId=''}else {s.customer={...s.customer,id:input.data.customer.id,name:input.data.customer.name,phone:input.data.customer.normalized_phone};s.loyaltyPrograms=input.data.programs||[];s.loyaltyRedemptions={};s.loyaltyCustomerId=input.customerId}return{session:s}}
test('customer is durable before screen update and loyalty request',async()=>{const h=host(),p=h.c.selectCustomer('new','Name','+123');await tick();h.calls[0].resolve(model(h.calls[0].input));await tick();assert.equal(h.c.state.customer.id,'old');assert.equal(h.network.length,0);assert.equal(h.writes[0].key,'currentOrderSession');h.writes[0].resolve();await tick();assert.equal(h.c.state.customer.id,'new');assert.equal(h.network.length,1);h.network[0].reject(Error('offline'));await p;assert.ok(h.events.includes('Клиент выбран, но loyalty недоступна'));assert.equal(h.events.includes('legacy-save'),false)});
test('storage failure preserves customer and does not start network',async()=>{const h=host(),p=h.c.selectCustomer('new','Name','p');await tick();h.calls[0].resolve(model(h.calls[0].input));await tick();h.writes[0].reject(Error('commit status is uncertain'));await p;assert.equal(h.c.state.customer.id,'old');assert.equal(h.c.criticalStorageRecoveryPending,true);assert.equal(h.network.length,0)});
test('closing modal cancels pure result without marking storage uncertain',async()=>{const h=host(),p=h.c.removeOrderCustomer();await tick();h.c.closeModal();h.calls[0].reject(Error('commit status is uncertain'));await p;assert.equal(h.writes.length,0);assert.equal(h.c.state.customer.id,'old');assert.equal(h.c.criticalStorageRecoveryPending,false)});
test('late loyalty response after customer replacement does not write',async()=>{const h=host(),p=h.c.loadCustomerLoyalty('old');h.c.state.customer={id:'other'};h.network[0].resolve({customer:{id:'old',name:'Late',normalized_phone:'p'},programs:[]});await p;assert.equal(h.calls.length,0);assert.equal(h.c.state.customer.id,'other')});
test('removal preserves address and is acknowledged before rendering',async()=>{const h=host(),p=h.c.removeOrderCustomer();await tick();h.calls[0].resolve(model(h.calls[0].input));await tick();assert.equal(h.c.state.customer.id,'old');h.writes[0].resolve();await p;assert.equal(h.c.state.customer.address,'Street');assert.equal('id' in h.c.state.customer,false);assert.equal('extra' in h.c.state.customer,false);assert.deepEqual(JSON.parse(JSON.stringify(h.c.state.loyaltyPrograms)),[])});
test('rollback invokes source association and storage flow',async()=>{const h=host();h.c.MPosNativeCustomerCommandsEnabled=false;h.c.loadCustomerLoyalty=async()=>{};await h.c.selectCustomer('new','Name','p');assert.equal(h.calls.length,0);assert.equal(h.c.state.customer.id,'new');assert.ok(h.events.includes('legacy-save'))});
test('customer fixtures retain reviewed source policy',async()=>{for(const c of cases){const out=structuredClone(c.input.session),state={customer:structuredClone(out.customer),loyaltyPrograms:out.loyaltyPrograms,loyaltyRedemptions:out.loyaltyRedemptions,loyaltyCustomerId:out.loyaltyCustomerId},ctx={state,document:{querySelector(){return null}},saveCurrentOrderSession(){for(const k of ['customer','loyaltyPrograms','loyaltyRedemptions','loyaltyCustomerId'])out[k]=structuredClone(state[k])},closeModal(){},render(){},flash(){}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(source,ctx);if(c.input.operation==='profile'){ctx.loyaltyApi=async()=>c.input.data;await ctx.loadCustomerLoyalty(c.input.customerId)}else if(c.input.operation==='remove')ctx.removeOrderCustomer();else{ctx.loadCustomerLoyalty=async()=>{};await ctx.selectCustomer(c.input.customer.id,c.input.customer.name,c.input.customer.phone)}assert.deepEqual(out,c.expected)}});
test('profile updates and programs wait for persisted session acknowledgement',async()=>{const h=host(),p=h.c.loadCustomerLoyalty('old');h.network[0].resolve({customer:{id:'old',name:'Updated',normalized_phone:'+375'},programs:[{id:'gift',rewards:1}]});await tick();h.calls[0].resolve(model(h.calls[0].input));await tick();assert.equal(h.c.state.customer.name,'Old');h.writes[0].resolve();await p;assert.equal(h.c.state.customer.name,'Updated');assert.equal(h.c.state.customer.extra.v,7);assert.equal(h.c.state.loyaltyLoadingCustomerId,'');assert.equal(h.c.state.loyaltyCustomerId,'old')});
test('profile persistence refusal clears loading without changing saved profile',async()=>{const h=host(),p=h.c.loadCustomerLoyalty('old');h.network[0].resolve({customer:{id:'old',name:'Updated',normalized_phone:'p'},programs:[]});await tick();h.calls[0].resolve(model(h.calls[0].input));await tick();h.writes[0].reject(Error('disk failure'));await p;assert.equal(h.c.state.customer.name,'Old');assert.equal(h.c.state.loyaltyLoadingCustomerId,'');assert.ok(h.c.state.loyaltyLoadError)});
