const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const adapter=fs.readFileSync('app/src/main/assets/pos/native-catalog-delete.js','utf8');
const clone=x=>JSON.parse(JSON.stringify(x));
function host(){const sent=[],events=[],timers=new Map();let tick=0;
 const state={products:[{id:'p',name:'Coffee'}],categoryOrder:['Empty'],categoryColors:{Empty:'#fff'},categorySymbols:{},categoryOnlineOrder:{},categoryOnlineMenu:{},layoutTiles:[{type:'product',id:'p'}],posNavigation:{categories:[{category:'Empty'}]},theme:'light'};
 const docs={products:clone(state.products),layout:{categoryOrder:['Empty'],tiles:clone(state.layoutTiles)},posNavigation:clone(state.posNavigation)};
 const c={state,criticalStorageRecoveryPending:false,currentShiftEmployeeIsAdmin:()=>true,categoryLayoutSnapshot:()=>({categoryOrder:state.categoryOrder,tiles:state.layoutTiles}),requestDelete:()=>events.push('legacy'),confirmDelete:()=>events.push('legacy-confirm'),document:{getElementById:()=>null},closeModal:()=>events.push('close'),render:()=>events.push('render'),flash:x=>events.push(x),markStorageBroken:()=>events.push('broken'),finishProductEditor:()=>events.push('finish'),setTimeout:fn=>{timers.set(++tick,fn);return tick},clearTimeout:id=>timers.delete(id),MPosCore:{Storage:{get:async(k,f)=>k in docs?clone(docs[k]):f}},webkit:{messageHandlers:{settingsScreen:{postMessage:p=>sent.push(p)}}}};c.window=c;vm.createContext(c);vm.runInContext(adapter,c);
 const ready=async()=>{for(let i=0;i<15;i++)await Promise.resolve()};
 const reply=(extra={})=>c.__mposCatalogDeleteResult({requestId:sent[0].requestId,...extra});
 const success=()=>({ok:true,products:[],layout:{tiles:[],categoryOrder:[],categoryColors:{},categorySymbols:{},categoryOnlineOrder:{},categoryOnlineMenu:{}},posNavigation:{categories:[]}});
 return {c,sent,events,timers,ready,reply,success};}
test('product confirmation sends no credential, prevents duplicates and applies only durable result',async()=>{const h=host(),p=h.c.requestDelete('product','p');await h.ready();assert.equal(h.sent.length,1);assert.equal(h.sent[0].command.passwordRequired,false);assert.equal(h.c.state.products.length,1);assert.equal(await h.c.requestDelete('product','p'),false);h.reply(h.success());assert.equal(await p,true);assert.equal(h.c.state.products.length,0);assert.deepEqual(h.events.slice(-3),['close','render','Товар удалён']);assert.equal(JSON.stringify(h.sent).includes('password"'),false);});
test('category requires credential even for admin and updates every returned category projection',async()=>{const h=host(),p=h.c.requestDelete('category','Empty');await h.ready();assert.equal(h.sent[0].command.passwordRequired,true);h.reply(h.success());assert.equal(await p,true);assert.equal(h.c.state.categoryOrder.length,0);assert.equal(h.c.state.posNavigation.categories.length,0);});
test('cancel and native guard rejection preserve products and do not mark storage broken',async()=>{for(const result of [{cancelled:true},{ok:false,message:'Товар нужен для возврата ранее проданных чеков'}]){const h=host(),p=h.c.requestDelete('product','p');await h.ready();h.reply(result);assert.equal(await p,false);assert.equal(h.c.state.products.length,1);assert.equal(h.events.includes('broken'),false);}});
test('typing has no deadline; retry resets commit deadline; timeout prevents resubmission and late update',async()=>{const h=host(),p=h.c.requestDelete('category','Empty');await h.ready();assert.equal(h.timers.size,0);h.reply({action:'committing'});assert.equal(h.timers.size,1);h.reply({action:'retry'});assert.equal(h.timers.size,0);h.reply({action:'committing'});[...h.timers.values()][0]();assert.equal(await p,false);h.reply(h.success());assert.equal(h.c.state.products.length,1);assert.equal(h.c.criticalStorageRecoveryPending,true);await h.c.requestDelete('product','p');assert.equal(h.sent.length,1);});
test('projection changes during confirmation cannot overwrite current UI with an old result',async()=>{const h=host(),p=h.c.requestDelete('product','p');await h.ready();h.c.state.products[0].name='Changed';h.reply(h.success());assert.equal(await p,false);assert.equal(h.c.state.products[0].name,'Changed');assert.equal(h.c.criticalStorageRecoveryPending,true);});
test('rollback preserves reviewed handlers',async()=>{const h=host();h.c.MPosNativeCatalogDeleteEnabled=false;await h.c.requestDelete('product','p');h.c.confirmDelete('product','p');assert.deepEqual(h.events,['legacy','legacy-confirm']);assert.equal(h.sent.length,0);});
