const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),tick=()=>new Promise(r=>setImmediate(r)),read=n=>fs.readFileSync('app/src/main/assets/pos/'+n,'utf8');
function host(){const calls=[],sent=[],writes=[],callbacks={},state={loaded:true,orders:[{id:'r1'}]},network={backendUrl:'https://example.invalid/prefix',deviceKey:'synthetic-test-key'};const ctx={state,document:{hidden:false,addEventListener:(n,fn)=>callbacks[n]=fn},storageBroken:false,AbortController,Date,Map,Set,Object,String,Array,Promise,setTimeout,clearTimeout,console,localStorage:{setItem:()=>{}},MPosCore:{AvailabilityGate:{prepare:input=>new Promise((resolve,reject)=>calls.push({input,resolve,reject}))}},PrilavokCore:{Storage:{get:async k=>k==='network'?network:0,set:async(k,v)=>writes.push([k,v])}},webkit:{messageHandlers:{network:{postMessage:p=>{sent.push(p);return true}}}}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(read('Web/js/features/availability.js'),ctx);vm.runInContext(read('native-availability.js'),ctx);return{ctx,calls,sent,writes,reply:(r,success=true)=>ctx.__nativeNetworkResult({requestId:r.requestId,ok:true,authoritative:true,sent:success})}}
function prepared(){return{send:true,token:'test-ticket',body:{version:1,revision:7,sampledAt:'2026-01-01T00:00:00.000Z',items:[{externalId:'z',quantity:null},{externalId:'a',quantity:3}],settledWebOrderIds:['w']}}}
test('native snapshot/receipt permit precedes revision and socket, failures never block local payment',async()=>{const h=host(),p=h.ctx.publishAvailability(['w']);await tick();assert.equal(h.calls[0].input.id,'r1');assert.equal(h.sent.length,0);h.calls[0].resolve(prepared());await tick();assert.deepEqual(h.writes,[['webAvailabilityRevision',7]]);assert.equal(h.sent[0].action,'availabilityPublish');assert.equal(h.sent[0].body.items[0].externalId,'a');h.reply(h.sent[0],false);assert.equal(await p,false);assert.equal(await h.ctx.publishAvailability(),false);assert.equal(h.sent.length,1);h.ctx.state.orders.push({id:'r2'});const next=h.ctx.publishAvailability([]);await tick();assert.equal(h.calls[1].input.id,'r2');h.calls[1].reject(Error('local read failed'));assert.equal(await next,false);assert.equal(h.sent.length,1)});
test('background abort cancels the socket and foreground/reconnect do not resend',async()=>{const h=host(),p=h.ctx.publishAvailability([]);await tick();h.calls[0].resolve(prepared());await tick();h.ctx.onAvailabilityAppState(false);assert.equal(await p,false);assert.equal(h.sent[1].action,'availabilityCancel');h.ctx.onAvailabilityAppState(true);h.ctx.startAvailabilityRecovery();assert.equal(h.sent.length,2);h.reply(h.sent[0]);assert.equal(h.sent.length,2)});
test('revision write failure prevents HTTP and repeated native receipt denial is safe',async()=>{for(const mode of ['revision','denied']){const h=host();if(mode==='revision')h.ctx.PrilavokCore.Storage.set=async()=>{throw Error('disk')};const p=h.ctx.publishAvailability([]);await tick();h.calls[0].resolve(mode==='denied'?{send:false}:prepared());assert.equal(await p,false);assert.equal(h.sent.length,0)}});
test('reviewed recipe/availability fixtures remain source-generated',()=>{const html=read('pos.html'),ctx={getProduct:()=>null};vm.createContext(ctx);vm.runInContext(html.slice(html.indexOf('function productIngredients('),html.indexOf('function stockConsumptionFor('))+html.slice(html.indexOf('function availableStock('),html.indexOf('let compositeCostCache'))+'\nfunction productTracksStock(p){return !!p&&p.type===\'simple\'&&!p.noStockTracking}\n'+read('Web/js/features/availability.js').split('async function sendAvailabilitySnapshot')[0],ctx);const cases=JSON.parse(fs.readFileSync('tests/fixtures/availability-native.json'));for(const c of cases)assert.deepEqual(JSON.parse(JSON.stringify(ctx.buildAvailabilityItems(c.products))),c.expected,c.label)});
test('two saved payments during a successful send coalesce to latest receipt; failure drops queued triggers',async()=>{for(const success of [true,false]){const h=host(),p=h.ctx.publishAvailability([]);await tick();h.calls[0].resolve(prepared());await tick();h.ctx.state.orders.push({id:'r2'});h.ctx.publishAvailability([]);h.ctx.state.orders.push({id:'r3'});h.ctx.publishAvailability([]);h.reply(h.sent[0],success);await tick();if(success){assert.equal(h.calls[1].input.id,'r3');h.calls[1].resolve(prepared());await tick();h.reply(h.sent[1]);assert.equal(await p,true)}else{assert.equal(await p,false);assert.equal(h.calls.length,1)}}});

test('transport rollback keeps native receipt authorization and reviewed body',async()=>{const h=host();let consumed=0,fetched=0;h.ctx.MPosNativeAvailabilityTransportEnabled=false;h.ctx.MPosCore.AvailabilityGate.consume=async input=>{consumed++;assert.equal(input.token,'test-ticket');return{network:{backendUrl:'https://example.invalid',deviceKey:'synthetic-test-key'},body:input.body}};h.ctx.fetch=async(url,options)=>{fetched++;assert.equal(url,'https://example.invalid/api/availability/snapshot');assert.equal(JSON.parse(options.body).items[0].externalId,'a');return{ok:true}};const p=h.ctx.publishAvailability([]);await tick();h.calls[0].resolve(prepared());assert.equal(await p,true);assert.equal(consumed,1);assert.equal(fetched,1);assert.equal(h.sent.length,0);assert.equal(await h.ctx.publishAvailability(),false)});
