const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const read=name=>fs.readFileSync('app/src/main/assets/pos/'+name,'utf8');
function host(order=false,untracked=false){
 const products=[{id:'p',name:'Milk',type:'simple',stockUnit:'l',stock:4,cost:10,noStockTracking:untracked,extension:{v:7}}];
 const draft={orderId:order?'o':null,supplierId:'s',invoiceNumber:'  invoice  ',invoiceDate:'2026-10-07',lines:[{productId:'p',qtyInput:'3',totalInput:'60',unit:'bottle',packSize:'500',contentUnit:'ml'}]};
 const orders=order?[{id:'o',status:'pending',supplierId:'s',supplierName:'Supplier',items:[{productId:'p',expectedQty:2,qty:2}],receivingDraftV2:draft,receivingIncomplete:true,extension:9}]:[];
 const state={products,purchaseOrders:orders,receivings:[],suppliers:[{id:'s',name:'Supplier'}],receivingCart:[{productId:'p'}]},calls=[],events=[];
 const ctx={state,Date:class extends Date{static now(){return 123}},getProduct:id=>state.products.find(p=>p.id===id),storageSnapshot:structuredClone,uid:()=> 'receiving-id',criticalOperationBusy:false,criticalStorageRecoveryPending:false,publishAvailability:()=>events.push('publish-noop'),finishReceivingPage:()=>events.push('finish'),closeModal:()=>{},render:()=>{},flash:x=>events.push(x),markStorageBroken:()=>events.push('broken'),commitCriticalStorage:async()=>events.push('legacy'),MPosCore:{ReceivingCommands:{commit:c=>new Promise((resolve,reject)=>calls.push({c,resolve,reject}))}},loadKey:()=>null,PrilavokCore:{Storage:{get:async()=>null}}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(read('Web/js/features/product-configuration.js'),ctx);ctx.roundStockQty=value=>{const r=Math.round((Number(value)+Number.EPSILON)*1000)/1000;return Object.is(r,-0)?0:r};vm.runInContext(read('Web/js/features/receiving.js'),ctx);vm.runInContext(read('native-receiving-command.js'),ctx);ctx._receivingPending={draft,orderId:order?'o':null,updates:[{id:'p',stock:999,cost:999}]};return{ctx,calls,events};
}
test('receiving recalculates stock after preview and changes memory only after native ack',async()=>{const h=host();h.ctx.state.products[0].stock=2;const pending=h.ctx.applyReceivingDocument();assert.equal(h.calls.length,1);assert.equal(h.ctx.state.products[0].stock,2);assert.equal(h.calls[0].c.writes.products[0].stock,3.5);assert.equal(h.calls[0].c.writes.products[0].cost,80/3.5);assert.equal(await h.ctx.applyReceivingDocument(),false);h.calls[0].resolve({ok:true});assert.equal(await pending,true);assert.equal(h.ctx.state.products[0].stock,3.5);assert.equal(h.ctx._receivingPending,null)});
test('native failure keeps cart, draft, stock and order unchanged',async()=>{const h=host(true),before=JSON.stringify(h.ctx.state);const pending=h.ctx.applyReceivingDocument();h.calls[0].reject(Error('storage failed'));assert.equal(await pending,false);assert.equal(JSON.stringify(h.ctx.state),before);assert.ok(h.ctx._receivingPending);assert.equal(h.ctx._receivingSaving,false);assert.ok(h.events.includes('broken'))});
test('rollback delegates receiving command and already received order cannot commit',async()=>{const h=host();h.ctx.MPosNativeReceivingCommandsEnabled=false;assert.equal(await h.ctx.applyReceivingDocument(),true);assert.ok(h.events.includes('legacy'));const x=host(true);x.ctx.state.purchaseOrders[0].status='received';assert.equal(await x.ctx.applyReceivingDocument(),false);assert.equal(x.calls.length,0)});
if(process.env.MPOS_WRITE_RECEIVING_FIXTURES)(async()=>{const result={};for(const [name,order,untracked]of[['standalone',false,false],['ordered',true,false],['untracked',false,true]]){const h=host(order,untracked),p=h.ctx.applyReceivingDocument();result[name]=h.calls[0].c;h.calls[0].resolve({ok:true});await p}fs.writeFileSync('tests/fixtures/receiving-commands.json',JSON.stringify(result,null,2)+'\n')})();
module.exports={host};
test('stored native command fixtures come from actual receiving operation',async()=>{const fixtures=JSON.parse(fs.readFileSync('tests/fixtures/receiving-commands.json','utf8'));for(const [name,order,untracked]of[['standalone',false,false],['ordered',true,false],['untracked',false,true]]){const h=host(order,untracked),pending=h.ctx.applyReceivingDocument();assert.deepEqual(JSON.parse(JSON.stringify(h.calls[0].c)),fixtures[name]);h.calls[0].resolve({ok:true});await pending}});
test('arithmetic fixtures independently match reviewed receiving source',()=>{const fixtures=JSON.parse(fs.readFileSync('tests/fixtures/receiving-arithmetic.json','utf8'));for(const f of fixtures){const h=host(true);h.ctx.state.products=structuredClone(f.products);let actual;try{const items=h.ctx.invoiceReceivingItems(f.draft),updates=h.ctx.receivingStockUpdates(items),products=structuredClone(f.products);for(const u of updates){const p=products.find(x=>x.id===u.id);p.stock=h.ctx.roundStockQty(u.stock);p.cost=u.cost}actual={allowed:true,items,products,shortage:h.ctx.receivingDiscrepancy(f.order,items)}}catch(e){actual={allowed:false,message:e.message}}assert.deepEqual(JSON.parse(JSON.stringify(actual)),f.expected,f.label)}});
