const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');const read=n=>fs.readFileSync('app/src/main/assets/pos/'+n,'utf8');
function host(){const state={products:[{id:'p',name:'Milk',type:'simple',stockUnit:'l',stock:10,cost:4,extension:8}],inventoryConfig:{enabled:true,frequency:'monthly',productIds:['p'],lastCompletedAt:null,customDates:[],extension:9},inventoryDraft:{id:'i',type:'scheduled',startedAt:100,scheduledDate:100,items:[{productId:'p',name:'Milk',unit:'l',expected:12,actual:8}],extension:7},inventoryHistory:[],tab:'inventoryWork'},calls=[],events=[];
 const ctx={state,Date:class extends Date{static now(){return 123}},storageSnapshot:structuredClone,getProduct:id=>state.products.find(p=>p.id===id),productTracksStock:p=>!!p&&p.type==='simple'&&!p.noStockTracking,roundStockQty:x=>{const n=Number(x);if(!Number.isFinite(n))return n;const r=Math.round((n+Number.EPSILON)*1000)/1000;return Object.is(r,-0)?0:r},criticalOperationBusy:false,criticalStorageRecoveryPending:false,MPosCore:{InventoryCommands:{commit:c=>new Promise((resolve,reject)=>calls.push({c,resolve,reject}))}},commitCriticalStorage:async()=>events.push('legacy'),publishAvailability:()=>events.push('publish-noop'),render:()=>{},closeModal:()=>{},flash:m=>events.push(m),markStorageBroken:()=>events.push('broken'),currentShiftEmployeeIsAdmin:()=>true,saveKey:()=>{},loadKey:()=>null,PrilavokCore:{Storage:{get:async()=>null}}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(read('Web/js/features/inventory.js'),ctx);vm.runInContext(read('native-inventory-command.js'),ctx);return{ctx,calls,events}}
async function fixtures(){const result={};for(const name of ['fix','complete','adhoc','normalized-config','unsaved-frequency']){const h=host();if(name==='fix'){const p=h.ctx.fixInventoryItem('p');result[name]=h.calls[0].c;h.calls[0].resolve({ok:true});await p;continue}const row=h.ctx.state.inventoryDraft.items[0];row.expected=10;row.actual=8;row.difference=-2;row.fixedAt=120;h.ctx.state.products[0].stock=7;if(name==='adhoc')h.ctx.state.inventoryDraft.type='adhoc';if(name==='unsaved-frequency')h.ctx.state.inventoryConfig.frequency='weekly';const p=h.ctx.confirmCompleteInventory();result[name]=h.calls[0].c;h.calls[0].resolve({ok:true});await p}return result}
test('inventory fix waits for atomic native stock/draft acknowledgement and current stock',async()=>{const h=host(),p=h.ctx.fixInventoryItem('p');assert.equal(h.calls.length,1);assert.equal(h.calls[0].c.writes.inventoryDraft.items[0].expected,10);assert.equal(h.calls[0].c.writes.inventoryDraft.items[0].difference,-2);assert.equal(h.ctx.state.products[0].stock,10);assert.equal(await h.ctx.fixInventoryItem('p'),false);h.calls[0].resolve({ok:true});assert.equal(await p,true);assert.equal(h.ctx.state.products[0].stock,8)});
test('failed inventory fix leaves stock/input unfixed and permits retry',async()=>{const h=host(),before=JSON.stringify(h.ctx.state),p=h.ctx.fixInventoryItem('p');h.calls[0].reject(Error('disk failure'));assert.equal(await p,false);assert.equal(JSON.stringify(h.ctx.state),before);assert.equal(h.ctx.criticalOperationBusy,false);assert.ok(h.events.includes('broken'))});
test('completion preserves sales after fixation and clears draft only after commit',async()=>{const h=host(),row=h.ctx.state.inventoryDraft.items[0];row.fixedAt=120;row.difference=-2;h.ctx.state.products[0].stock=7;const p=h.ctx.confirmCompleteInventory();assert.ok(h.ctx.state.inventoryDraft);assert.equal(h.calls[0].c.writes.products[0].stock,7);assert.equal(h.calls[0].c.writes.inventoryHistory[0].estimatedLoss,8);assert.equal(await h.ctx.confirmCompleteInventory(),false);h.calls[0].resolve({ok:true});assert.equal(await p,true);assert.equal(h.ctx.state.inventoryDraft,null);assert.equal(h.ctx.state.products[0].stock,7);assert.equal(h.ctx.state.inventoryConfig.lastCompletedAt,123)});
test('invalid/null/untracked/already fixed rows cannot change stock and rollback delegates',async()=>{for(const edit of [h=>h.ctx.state.inventoryDraft.items[0].actual=null,h=>h.ctx.state.products[0].noStockTracking=true,h=>h.ctx.state.inventoryDraft.items[0].fixedAt=100]){const h=host();edit(h);assert.equal(await h.ctx.fixInventoryItem('p'),false);assert.equal(h.calls.length,0)}const h=host();h.ctx.MPosNativeInventoryCommandsEnabled=false;assert.equal(await h.ctx.fixInventoryItem('p'),true);assert.ok(h.events.includes('legacy'))});
test('native candidates match independently captured actual inventory source',async()=>{const actual=JSON.parse(JSON.stringify(await fixtures()));if(process.env.MPOS_WRITE_INVENTORY_FIXTURES)fs.writeFileSync('tests/fixtures/inventory-commands.json',JSON.stringify(actual,null,2)+'\n');assert.deepEqual(actual,JSON.parse(fs.readFileSync('tests/fixtures/inventory-commands.json','utf8')))});
