const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {dom}=require('./helpers/product-editor-dom.cjs');
const read=n=>fs.readFileSync('app/src/main/assets/pos/'+n,'utf8');
const configuration=read('Web/js/features/product-configuration.js');
// Auth is outside this test's scope: do not load or copy private verifier handlers.
const source=configuration.slice(0,configuration.indexOf('function requestNoStockUnlock('));
function host(){
 const sent=[],events=[],timers=[];let resolve;
 const h={state:{loaded:true,tab:'products',products:[{id:'milk',name:'Молоко',type:'simple',stockUnit:'l',stockDisplayUnit:'l',stock:5,cost:10,price:20,category:'Продукты'}],categoryOrder:['Продукты'],orders:[],parked:[],currency:'BYN'},currentShiftEmployeeIsAdmin:()=>true,canEditProductWebSetting:()=>true,productDependsOn:()=>false,productIngredients:()=>new Map(),clearCompositeCostCache:()=>{},uid:(()=>{let n=0;return()=> 'test-'+(++n)})(),escapeHtml:s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;'),escapeAttr:s=>h.escapeHtml(s),fullMoney:v=>Number(v).toFixed(2)+' BYN',money:v=>Number(v).toFixed(2),compositeCost:p=>Number(p?.cost||0),compositeCostForQuantity:(p,q)=>Number(p?.cost||0)*q,purchaseUnitOptions:(p,v)=>'<option value="'+(v||'')+'">'+(v||'Не задана')+'</option>',innerWidth:1000,innerHeight:800,addEventListener:()=>{},setTimeout:f=>timers.push(f),Event:class{constructor(type){this.type=type}},webkit:{messageHandlers:{settingsScreen:{postMessage:p=>{sent.push(JSON.parse(JSON.stringify(p)));return true}},photoPicker:{postMessage:p=>events.push(p)}}},flash:m=>events.push(m),saveProduct:async()=>{events.push('save');return new Promise(r=>resolve=r)},showModal:html=>{h.document.getElementById('modal-root').innerHTML='<div class="modal">'+html+'</div>'},closeModal:()=>{h.document.getElementById('modal-root').innerHTML=''},toggleProductModalOnline:()=>{h._pmOnline=!h._pmOnline;h.document.getElementById('pf-web-toggle').setAttribute('aria-checked',h._pmOnline)},toggleProductModalMenu:()=>{},pickProductImage:()=>events.push('photo')};
 const fixture=dom(h);Object.assign(h,fixture);h.window=h;h.getProduct=id=>h.state.products.find(p=>p.id===id);h.convertProductQty=(v)=>Number(v);vm.createContext(h);vm.runInContext(source+'\n'+read('Web/js/features/product-editor.js')+'\n'+read('Web/js/features/product-photo.js'),h);vm.runInContext(read('native-settings-ui.js'),h);
 const pump=()=>{while(timers.length)timers.shift()();fixture.pump()};const flat=items=>items.flatMap(i=>[i,...(i.items?flat(i.items):[])]);
 const model=()=>sent.filter(p=>p.action==='formShow'||p.action==='formPatch').at(-1);const entries=()=>flat(model().items);
 const action=(label,fields={})=>h.__nativeSettingsAction({action:'click',token:sent.filter(p=>p.action==='formShow').at(-1).token,key:entries().find(i=>i.kind==='button'&&i.label===label)?.key,fields});
 const change=values=>h.__nativeSettingsAction({action:'change',token:sent.filter(p=>p.action==='formShow').at(-1).token,fields:Object.fromEntries(Object.entries(values).map(([label,v])=>[entries().find(i=>i.kind==='field'&&i.label===label)?.key,v]))});
 h.openProductModal('milk');pump();return{h,sent,events,pump,model,entries,action,change,reply:v=>resolve(v)};
}
test('reviewed standalone product editor presents native sections, permissions and readonly cost',async()=>{const h=host();assert.equal(h.model().expanded,true);assert.ok(h.entries().some(i=>i.text==='Основная информация'));assert.ok(h.entries().some(i=>i.kind==='image'));assert.equal(h.h.document.querySelector('.product-editor').style.opacity,'0');await h.action('Состав и остатки');h.pump();assert.equal(h.entries().find(i=>i.label==='Себестоимость за 1 л').readOnly,true);h.h.currentShiftEmployeeIsAdmin=()=>false;h.h.openProductModal('milk');h.pump();await h.action('Состав и остатки');h.pump();assert.equal(h.entries().find(i=>i.label==='Текущий остаток, л').readOnly,true)});
test('draft fields flush before switching sections; unit conversion never drops current input',async()=>{const h=host();const name=h.entries().find(i=>i.label==='Название товара');await h.action('Состав и остатки',{[name.key]:'Кефир'});h.pump();assert.equal(h.h.document.getElementById('pf-name').value,'Кефир');await h.change({'Текущий остаток, л':'7','Единица ввода остатка и себестоимости':'ml'});h.pump();assert.equal(h.h.document.getElementById('pf-stock').value,'7000');assert.equal(h.h._pmBaseUnit,'l');assert.equal(h.h._pmUnit,'ml');assert.equal(h.h.state.products[0].stock,5)});
test('actual ingredient search/add/quantity/remove and inferred yield update native actions',async()=>{const h=host();h.h.openProductModal();h.pump();await h.action('Составной');h.pump();await h.action('Состав и остатки');h.pump();assert.ok(h.entries().some(i=>i.text?.includes('Состав пока пуст')));await h.change({'Добавить в состав':'моло'});h.pump();const add=h.entries().find(i=>i.kind==='button'&&i.label.includes('Молоко'));await h.action(add.label);h.pump();assert.equal(h.h._pmComponents[0].qty,1);await h.change({'Количество: Молоко':'2,5'});h.pump();assert.equal(h.h._pmComponents[0].qty,2.5);assert.equal(h.h._pmRecipeYield,2500);const old=h.entries().find(i=>i.label==='Удалить компонент');await h.action('Удалить компонент');h.pump();assert.equal(h.h._pmComponents.length,0);await h.h.__nativeSettingsAction({action:'click',token:h.sent.filter(p=>p.action==='formShow').at(-1).token,key:old.key});assert.equal(h.h._pmComponents.length,0)});
test('reviewed modifier group/options fields execute input/change handlers before picker and preserve drafts',async()=>{const h=host();h.h.openProductModal();h.pump();await h.action('Модификаторы');h.pump();await h.action('+ Группа');h.pump();await h.change({'Название группы':'Добавки'});h.pump();await h.action('Добавить вариант');h.pump();await h.change({'Название в POS':'Порция молока','Количество для списания':'0,5','Доплата к цене':'3'});h.pump();assert.equal(h.h._pmModifierGroups[0].options[0].qty,0.5);assert.equal(h.h._pmModifierGroups[0].options[0].posName,'Порция молока');await h.action('Выберите товар');h.pump();assert.ok(h.entries().some(i=>i.text==='Выберите товар'));await h.change({'Поиск':'моло'});h.pump();const choice=h.entries().find(i=>i.kind==='button'&&i.label.includes('Молоко'));await h.action(choice.label);h.pump();assert.equal(h.h._pmModifierGroups[0].options[0].productId,'milk');assert.equal(h.h._pmModifierGroups[0].name,'Добавки');assert.equal(h.h._pmModifierGroups[0].options[0].priceDelta,3)});
test('save awaits reviewed async boundary, rejects duplicate/stale commands and retains failed draft',async()=>{const h=host();const name=h.entries().find(i=>i.label==='Название товара');const p=h.action('Сохранить',{[name.key]:'Новый заголовок'});await h.action('Сохранить');assert.equal(h.events.filter(e=>e==='save').length,1);assert.ok(h.h.document.getElementById('pe-save'));h.reply(false);await p;h.pump();assert.equal(h.h.document.getElementById('pf-name').value,'Новый заголовок');assert.equal(h.sent.filter(p=>p.action==='formResult').at(-1).blocked,false);const oldToken=h.sent.find(p=>p.action==='formShow').token;h.h.openProductModal();h.pump();await h.h.__nativeSettingsAction({action:'click',token:oldToken,key:'1'});assert.equal(h.events.filter(e=>e==='save').length,1)});
test('native back transfers unsent edits into reviewed dirty-exit flow; stay and discard retain original decisions',async()=>{const h=host(),form=h.model(),name=h.entries().find(i=>i.label==='Название товара');await h.h.__nativeSettingsAction({action:'cancel',token:form.token,fields:{[name.key]:'Не сохранено'}});h.pump();assert.ok(h.entries().some(i=>i.text==='Сохранить изменения?'));await h.action('Остаться в карточке');h.pump();assert.equal(h.h.document.getElementById('pf-name').value,'Не сохранено');await h.h.__nativeSettingsAction({action:'cancel',token:h.sent.filter(p=>p.action==='formShow').at(-1).token,fields:{}});h.pump();await h.action('Не сохранять');h.pump();assert.equal(h.h.document.querySelector('.product-editor'),null);assert.equal(h.h.state.products[0].name,'Молоко')});
test('online switches preserve permissions and native toggle status; rollback restores reviewed presentation',async()=>{const h=host();await h.action('Онлайн-меню');h.pump();await h.action('Онлайн заказ · Включено');h.pump();assert.equal(h.h._pmOnline,false);assert.ok(h.entries().some(i=>i.label==='Онлайн заказ · Выключено'));h.h.MPosNativeProductEditorEnabled=false;h.pump();assert.equal(h.h.document.querySelector('.product-editor').style.opacity,undefined);assert.equal(h.h.document.querySelector('.product-editor').style.pointerEvents,undefined)});

test('dirty-exit save carries pending lock across modal removal until rejected local save completes',async()=>{
 const h=host(),name=h.entries().find(i=>i.label==='Название товара');await h.change({'Название товара':'Изменённый товар'});h.pump();
 await h.h.__nativeSettingsAction({action:'cancel',token:h.sent.filter(p=>p.action==='formShow').at(-1).token,fields:{}});h.pump();
 const pending=h.action('Сохранить и продолжить');h.pump();const editor=h.sent.filter(p=>p.action==='formShow').at(-1);assert.equal(editor.pending,true);
 await h.h.__nativeSettingsAction({action:'change',token:editor.token,fields:{[name.key]:'Перезапись во время сохранения'}});
 await h.h.__nativeSettingsAction({action:'cancel',token:editor.token});assert.equal(h.h.document.getElementById('pf-name').value,'Изменённый товар');
 assert.ok(h.h.document.querySelector('.product-editor'));h.h.criticalStorageRecoveryPending=true;h.h.flash('Не удалось сохранить товар');h.reply(false);await pending;h.pump();assert.equal(h.sent.filter(p=>p.action==='formResult').at(-1).blocked,true);assert.equal(h.sent.filter(p=>p.action==='formResult').at(-1).message,'Не удалось сохранить товар');assert.equal(h.model().pending,false);assert.ok(h.entries().some(i=>i.label==='Сохранить'&&!i.disabled));
});

test('rejected ingredient quantity reports reviewed validation in native form and keeps source component',async()=>{
 const h=host();h.h.openProductModal();h.pump();await h.action('Составной');h.pump();await h.action('Состав и остатки');h.pump();
 const add=h.entries().find(i=>i.kind==='button'&&i.label.includes('Молоко'));await h.action(add.label);h.pump();await h.change({'Количество: Молоко':'0'});h.pump();
 assert.equal(h.h._pmComponents[0].qty,1);assert.equal(h.sent.filter(p=>p.action==='formResult').at(-1).message,'Количество должно быть больше нуля');
 assert.equal(h.entries().find(i=>i.label==='Количество: Молоко').value,'1');
});

test('a pending search draft replacing the selected button cannot invoke its detached ingredient action',async()=>{
 const h=host();h.h.openProductModal();h.pump();await h.action('Составной');h.pump();await h.action('Состав и остатки');h.pump();
 const search=h.entries().find(i=>i.label==='Добавить в состав'),add=h.entries().find(i=>i.kind==='button'&&i.label.includes('Молоко'));
 await h.action(add.label,{[search.key]:'Не существующий ингредиент'});h.pump();assert.equal(h.h._pmComponents.length,0);
 assert.equal(h.sent.filter(p=>p.action==='formResult').at(-1).message,'Список обновился. Выберите действие ещё раз.');assert.ok(h.entries().some(i=>i.text==='Нет подходящих товаров.'));
});

test('native photo selection reuses its local file ID instead of resending JPEG bytes on form patches',async()=>{
 const h=host();await h.action('Выбрать фото');assert.ok(h.events.some(e=>e?.action==='pick'));
 h.h.handleNativeProductImage('data:image/jpeg;base64,c3ludGhldGlj','123e4567-e89b-12d3-a456-426614174000');h.pump();
 assert.equal(h.entries().find(i=>i.kind==='image').source,'mpos-image://123e4567-e89b-12d3-a456-426614174000');
 await h.action('Убрать фото');h.pump();assert.equal(h.h._pmRemoveImage,true);assert.equal(h.entries().find(i=>i.kind==='image').source,'');assert.ok(h.events.some(e=>e?.action==='remove'));
});
