const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('app/src/main/assets/pos/network-printer.js','utf8'),mirror=fs.readFileSync('app/src/main/assets/pos/native-settings.js','utf8'),adapter=fs.readFileSync('app/src/main/assets/pos/native-platform-settings.js','utf8');
const clone=x=>JSON.parse(JSON.stringify(x));
function host(saved=null,connections=false){
 const calls=[],prints=[],events=[],timers=new Map(),values=new Map([['printers',JSON.stringify([{id:'p',name:'Old',ip:'192.0.2.1',extension:{keep:true}}])]]);let timer=0;
 const elements={};const storage={getItem:k=>values.get(String(k))??null,setItem:(k,v)=>values.set(String(k),String(v)),removeItem:k=>values.delete(String(k)),key:i=>[...values.keys()][i]??null,get length(){return values.size}};
 const h={Date,console,localStorage:storage,state:{},document:{getElementById:id=>elements[id],querySelectorAll:()=>[]},setTimeout:fn=>{timers.set(++timer,fn);return timer},clearTimeout:id=>timers.delete(id),flash:s=>events.push(s),render:()=>events.push('render'),closeModal:()=>events.push('close'),loadAll:async()=>events.push('load'),webkit:{messageHandlers:{settings:{postMessage:p=>{calls.push(clone(p));return true}},printer:{postMessage:p=>prints.push(clone(p))}}}};
 h.window=h;vm.createContext(h);vm.runInContext(source,h);h.openPrintersManager=()=>events.push('manager');h.applyBackupData=async data=>{events.push('storage-import');h.__restorePrinterSettings(data)};vm.runInContext(mirror,h);vm.runInContext(adapter,h);if(connections)vm.runInContext(fs.readFileSync("app/src/main/assets/pos/native-connection-tests.js","utf8"),h);
 function answer(call,extra={}){h.__nativeSettingsResult({requestId:call.requestId,ok:true,...extra})}
 async function settle(){for(let i=0;i<10;i++)await Promise.resolve()}
 async function initialize(){const p=h.MPosCore.PlatformSettings.initialize();answer(calls.at(-1),saved?{authoritative:true,snapshot:{settings:saved}}:{authoritative:false});await settle();if(!saved)answer(calls.at(-1),{authoritative:true,snapshot:{settings:calls.at(-1).settings}});await p;return p}
 function edit(){for(const [id,value]of Object.entries({'mp-id':'p','mp-name':'New','mp-ip':'192.0.2.2','mp-paper':'80','mp-copies':'1','mp-mode':'graphic','mp-dpi':'203','mp-receipt-title':'M POS','mp-register-label':'Cash 1','mp-receipt-phrases':'Thanks'}))elements[id]={value};for(const id of ['mp-auto','mp-print-receipts','mp-payment-comments'])elements[id]={checked:true};elements['mp-print-orders']={checked:false}}
 return{h,calls,prints,events,timers,values,elements,answer,settle,initialize,edit};
}
test('cutover imports current reviewed snapshot; existing native authority ignores stale browser data',async()=>{
 const a=host();await a.initialize();assert.equal(a.calls[1].action,'platformSettingsInitialize');assert.equal(a.calls[1].settings.printers[0].extension.keep,true);
 const saved={printers:[{id:'native',name:'Native',ip:'192.0.2.9'}],posNotifications:{soundEnabled:false,sound:'soft'},future:{keep:true}},b=host(saved);await b.initialize();assert.equal(b.calls.length,1);assert.deepEqual(clone(b.h.__printerSettingsSnapshot()),saved);assert.equal(JSON.parse(b.h.localStorage.getItem('printers'))[0].id,'native');assert.equal(b.h.state.printers[0].id,'native');
});
test('loader waits for native initialization before source load; duplicate initialization shares one request',async()=>{const h=host();const a=h.h.loadAll(),b=h.h.MPosCore.PlatformSettings.initialize();assert.equal(h.calls.length,1);assert.deepEqual(h.events,[]);h.answer(h.calls[0],{authoritative:false});await h.settle();h.answer(h.calls.at(-1),{authoritative:true,snapshot:{settings:h.calls.at(-1).settings}});await Promise.all([a,b]);assert.deepEqual(h.events,['load'])});
test('save stages browser writes/state/UI, publishes only confirmed snapshot and preserves unknown fields',async()=>{const h=host();await h.initialize();h.edit();const before=clone(h.h.__printerSettingsSnapshot()),p=h.h.savePrinterFromPage();await h.settle();const call=h.calls.filter(c=>c.action==='platformSettingsWrite').at(-1);assert.ok(call);assert.deepEqual(call.expected,before);assert.equal(call.settings.printers[0].name,'New');assert.equal(h.h.state.printers[0].name,'Old');assert.deepEqual(h.events,[]);assert.equal(JSON.parse(h.values.get('printers'))[0].name,'Old');h.answer(call,{authoritative:true,snapshot:{settings:call.settings}});await p;assert.equal(h.h.state.printers[0].name,'New');assert.equal(h.h.__printerSettingsSnapshot().printers[0].extension.keep,true);assert.deepEqual(h.events,['Принтер сохранён','manager'])});
test('failure preserves previous cache/state and does not close editor or print',async()=>{for(const name of ['savePrinterFromPage','testPrinterFromPage']){const h=host();await h.initialize();h.edit();const p=h.h[name]();await h.settle();const call=h.calls.filter(c=>c.action==='platformSettingsWrite').at(-1);h.answer(call,{ok:false,message:'Disk failed'});await assert.rejects(p,/Disk failed/);assert.equal(h.h.state.printers[0].name,'Old');assert.equal(h.h.__printerSettingsSnapshot().printers[0].name,'Old');assert.equal(h.prints.length,0);assert.ok(!h.events.includes('manager'));assert.deepEqual(h.events,['Disk failed'])}});
test('test print is submitted only after disk acknowledgement and never retried',async()=>{const h=host();await h.initialize();h.edit();const p=h.h.testPrinterFromPage();await h.settle();assert.equal(h.prints.length,0);const call=h.calls.filter(c=>c.action==='platformSettingsWrite').at(-1);h.answer(call,{authoritative:true,snapshot:{settings:call.settings}});await p;assert.equal(h.prints.length,1);assert.equal(h.prints[0].order.__networkTest,true);h.h.__nativeSettingsResult({requestId:call.requestId,ok:true});assert.equal(h.prints.length,1)});
test('notification save waits for disk, removes modal only after success and sound preview remains manual',async()=>{const h=host();await h.initialize();h.elements['notify-enabled']={checked:false};h.elements['notify-sound']={value:'bell'};const p=h.h.saveNotificationSettings();await h.settle();assert.equal(h.h.state.posNotifications.sound,'default');assert.deepEqual(h.events,[]);const call=h.calls.filter(c=>c.action==='platformSettingsWrite').at(-1);h.answer(call,{authoritative:true,snapshot:{settings:call.settings}});await p;assert.equal(h.h.state.posNotifications.sound,'bell');assert.deepEqual(h.events,['close','Настройки уведомлений сохранены','render']);assert.equal(h.prints.length,0)});
test('owned facade refuses out-of-transaction writes, supports legacy key enumeration and delegates other keys',async()=>{const h=host();await h.initialize();assert.throws(()=>h.h.localStorage.setItem('printers','[]'),/Android/);assert.throws(()=>h.h.localStorage.removeItem('posNotificationSettings'),/Android/);h.h.localStorage.setItem('other','preserved');assert.equal(h.h.localStorage.getItem('other'),'preserved');assert.equal(h.h.localStorage.length,3);assert.equal(h.h.localStorage.key(3),null);assert.throws(()=>h.h.localStorage.clear(),/M POS/);assert.equal(h.h.__printerSettingsSnapshot().printers.length,1)});
test('backup waits for native restore, writes both keys in one snapshot and propagates failure',async()=>{for(const success of [true,false]){const h=host();await h.initialize();const data={printers:[],posNotifications:{soundEnabled:false,sound:'soft'}},p=h.h.applyBackupData(data);await h.settle();let done=false;p.then(()=>done=true,()=>{});assert.equal(done,false);const call=h.calls.filter(c=>c.action==='platformSettingsWrite').at(-1);assert.deepEqual(call.settings.printers,[]);assert.equal(call.settings.posNotifications.sound,'soft');h.answer(call,success?{authoritative:true,snapshot:{settings:call.settings}}:{ok:false,message:'restore failed'});if(success)await p;else await assert.rejects(p,/restore failed/);assert.equal(h.h.__printerSettingsSnapshot().printers.length,success?0:1)}});
test('uncertain acknowledgement blocks new writes; late success cannot publish or retry',async()=>{const h=host();await h.initialize();h.edit();const p=h.h.savePrinterFromPage();await h.settle();const call=h.calls.filter(c=>c.action==='platformSettingsWrite').at(-1);const timeout=[...h.timers.entries()].at(-1);h.timers.delete(timeout[0]);timeout[1]();await assert.rejects(p,/uncertain/);h.answer(call,{authoritative:true,snapshot:{settings:call.settings}});assert.equal(h.h.__printerSettingsSnapshot().printers[0].name,'Old');assert.equal(h.h.MPosCore.PlatformSettings.blocked,true);const count=h.calls.length;await assert.rejects(h.h.savePrinterFromPage(),/Перезапустите/);assert.equal(h.calls.length,count);assert.equal(h.prints.length,0)});
test('busy guard rejects overlapping save and disk failure in compatibility copy cannot undo native commit',async()=>{const h=host();await h.initialize();h.edit();const p=h.h.savePrinterFromPage();await h.settle();await assert.rejects(h.h.savePrinterFromPage(),/Дождитесь/);const call=h.calls.filter(c=>c.action==='platformSettingsWrite').at(-1);h.h.localStorage.getItem('other');const legacyWrite=h.values.set;h.values.set=()=>{throw Error('browser disabled')};h.answer(call,{authoritative:true,snapshot:{settings:call.settings}});await p;h.values.set=legacyWrite;assert.equal(h.h.__printerSettingsSnapshot().printers[0].name,'New');assert.equal(h.events.at(-1),'manager')});
test('snapshot is isolated and validation failure has no native write or success effect',async()=>{const h=host();await h.initialize();const before=h.calls.length,snapshot=h.h.__printerSettingsSnapshot();snapshot.printers.length=0;assert.equal(h.h.__printerSettingsSnapshot().printers.length,1);h.edit();h.elements['mp-ip'].value='';assert.equal(await h.h.savePrinterFromPage(),false);assert.equal(h.calls.length,before);assert.deepEqual(h.events,['Введите IP-адрес принтера'])});


test('correlated test print preserves real disk acknowledgement and waits for terminal transport result',async()=>{
 const x=host(null,true);await x.initialize();x.edit();const p=x.h.testPrinterFromPage();await x.settle();assert.equal(x.prints.length,0);
 const write=x.calls.filter(c=>c.action==='platformSettingsWrite').at(-1);x.answer(write,{authoritative:true,snapshot:{settings:write.settings}});await x.settle();assert.equal(x.prints.length,1);assert.equal(x.prints[0].order.__networkPrinterIp,'192.0.2.2');
 const requestId=x.prints[0].requestId;assert.match(requestId,/connection-test-printer/);let done=false;p.then(()=>done=true);x.h.__nativePrinterEvent({type:'printAdmission',requestId,ok:true,count:1});await x.settle();assert.equal(done,false);
 x.h.__nativePrinterEvent({type:'printed',requestId});assert.equal(await p,true);assert.match(x.events.at(-1),/Проверьте бумажный чек/);assert.equal(x.prints.length,1);
});

test('failed real settings commit never submits correlated print and releases test guard',async()=>{
 const x=host(null,true);await x.initialize();const initialTimers=x.timers.size;x.edit();const p=x.h.testPrinterFromPage();await x.settle();const write=x.calls.filter(c=>c.action==='platformSettingsWrite').at(-1);x.answer(write,{ok:false,message:'disk failure'});await assert.rejects(p,/disk failure/);assert.equal(x.prints.length,0);assert.equal(x.timers.size,initialTimers);
});
