const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {dom}=require('./helpers/product-editor-dom.cjs');
const read=n=>fs.readFileSync('app/src/main/assets/pos/'+n,'utf8'),clone=x=>JSON.parse(JSON.stringify(x));
function host(){
 const sent=[],calls=[],events=[],timers=[];
 const h={state:{loaded:true,tab:'bookings',hallTables:[{id:'t',number:1,name:'Окно',shape:'square',rotation:0,x:7,y:8},{id:'other',number:2,name:'Зал',shape:'rectangle',rotation:90,x:30,y:8}],bookings:[],selectedHallTableId:'t',bookingDate:'2026-10-07',bookingTime:'19:00',bookingDuration:120,hallEditMode:false},criticalStorageRecoveryPending:false,innerWidth:1040,innerHeight:640,addEventListener:()=>{},Event:class{constructor(type){this.type=type}},setTimeout:f=>timers.push(f),uid:()=> 'synthetic-new',escapeHtml:s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;'),escapeAttr:s=>h.escapeHtml(s),localDateString:d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,loadKey:()=>{},saveKey:()=>{throw Error('source persistence fallback forbidden')},flash:m=>events.push(m),showModal:html=>h.document.getElementById('modal-root').innerHTML='<div class="modal">'+html+'</div>',closeModal:()=>h.document.getElementById('modal-root').innerHTML='',render:()=>h.document.getElementById('app').innerHTML=h.renderBookingsScreen(),webkit:{messageHandlers:{settingsScreen:{postMessage:p=>{sent.push(clone(p));return true}}}},MPosCore:{Storage:{get:()=>{}},HallCommands:{commit:input=>new Promise((resolve,reject)=>calls.push({input:clone(input),resolve,reject}))}}};
 const fixture=dom(h);Object.assign(h,fixture);h.window=h;vm.createContext(h);for(const file of ['Web/js/features/hall-bookings.js','native-hall-command.js','native-settings-ui.js'])vm.runInContext(read(file),h);
 const flat=items=>items.flatMap(i=>[i,...(i.items?flat(i.items):[])]),model=()=>sent.filter(p=>['show','formShow','formPatch'].includes(p.action)).at(-1),entries=()=>flat(model().items),pump=()=>{while(timers.length)timers.shift()();fixture.pump()},action=(label,fields={})=>h.__nativeSettingsAction({action:'click',token:model().token,key:entries().find(i=>i.kind==='button'&&i.label===label)?.key,fields}),reply=(result,index=calls.length-1)=>calls[index].resolve({ok:true,authoritative:true,...clone(result)}),field=(label)=>entries().find(i=>i.kind==='field'&&i.label===label),move=(x,y,key)=>h.__nativeSettingsAction({action:'hallMove',token:model().token,key:key||entries().find(i=>i.kind==='hallMap').tables[0].key,x,y});
 h.render();pump();return{h,sent,calls,events,model,entries,pump,action,reply,field,move};
}
const booking={id:'b',tableId:'t',date:'2026-10-07',startAt:'2026-10-07T19:00:00Z',endAt:'2026-10-07T21:00:00Z',guestName:'Мария',guests:2,phone:'123',note:'У окна',status:'active'};
test('native map preserves shapes/rotation/booked/selection and normal mode refuses movement',async()=>{
 const t=host();let map=t.entries().find(i=>i.kind==='hallMap');assert.equal(map.tables[0].name,'Окно');assert.equal(map.tables[1].shape,'rectangle');assert.equal(map.tables[1].rotation,90);await t.move(25,30);assert.equal(t.calls.length,0);await t.h.__nativeSettingsAction({action:'click',token:t.model().token,key:map.tables[1].key});t.pump();assert.equal(t.h.state.selectedHallTableId,'other');t.h.state.bookings=[booking];t.h.render();t.pump();map=t.entries().find(i=>i.kind==='hallMap');assert.equal(map.tables[0].booked,true);assert.equal(map.tables[1].selected,true);assert.equal(t.calls.length,0);
});
test('table create waits for durable reply, duplicate taps/failure retain form and retry input',async()=>{
 const t=host();await t.action('Редактировать карту');t.pump();await t.action('＋ Квадратный стол');t.pump();const p=t.action('Добавить стол',{[t.field('Название стола').key]:'Новый'});await t.action('Добавить стол');assert.equal(t.calls.length,1);assert.equal(t.calls[0].input.operation,'table-create');assert.equal(t.h.state.hallTables.length,2);t.calls[0].reject(Error('disk failed'));await p;t.pump();assert.ok(t.h.document.querySelector('#new-hall-table-name'));assert.equal(t.h.state.hallTables.length,2);const retry=t.action('Добавить стол');assert.equal(t.calls[1].input.name,'Новый');t.reply({hallTables:[...t.h.state.hallTables,{id:'synthetic-new',number:3,name:'Новый',shape:'square',x:53,y:8}],bookings:[]});await retry;t.pump();assert.equal(t.h.state.hallTables.length,3);assert.equal(t.h.state.selectedHallTableId,'synthetic-new');
});
test('native drag uses original pointer/native command and restores baseline before save/failure',async()=>{
 const t=host();await t.action('Редактировать карту');t.pump();await t.action('Редактировать карту');t.pump();assert.equal(t.h.state.hallEditMode,true);const p=t.move(37,28);assert.equal(t.calls[0].input.operation,'table-move');assert.equal(t.calls[0].input.x,37);assert.equal(t.calls[0].input.expected.hallTables[0].x,7);assert.equal(t.h.state.hallTables[0].x,7);await t.move(50,50);assert.equal(t.calls.length,1);t.calls[0].reject(Error('failed move'));await p;t.pump();assert.equal(t.entries().find(i=>i.kind==='hallMap').tables[0].x,7);const retry=t.move(37,28);t.reply({hallTables:t.h.state.hallTables.map(x=>x.id==='t'?{...x,x:37,y:28}:x),bookings:[]});await retry;t.pump();assert.equal(t.h.state.hallTables[0].x,37);assert.equal(t.h.state._hallSuppressClick,false);await t.h.__nativeSettingsAction({action:'click',token:t.model().token,key:t.entries().find(i=>i.kind==='hallMap').tables[0].key});t.pump();assert.ok(t.h.document.querySelector('#edit-hall-table-name'));
});
test('booking time/duration/guest stepper stay source-owned and create changes nothing before acknowledgement',async()=>{
 const t=host();await t.action('Забронировать');t.pump();assert.equal(t.field('Время начала').type,'time');await t.action('+');t.pump();assert.ok(t.entries().some(i=>i.text==='Количество гостей: 3'));const p=t.action('Забронировать',{[t.field('Имя гостя').key]:'Мария',[t.field('Время начала').key]:'23:30',[t.field('Длительность').key]:'90',[t.field('Комментарий').key]:'У окна'});assert.equal(t.calls[0].input.guests,'3');assert.equal(t.calls[0].input.time,'23:30');assert.equal(t.calls[0].input.duration,90);assert.equal(t.h.state.bookings.length,0);t.reply({hallTables:t.h.state.hallTables,bookings:[{...booking,startAt:'2026-10-07T23:30:00Z',endAt:'2026-10-08T01:00:00Z',guests:3}]});await p;t.pump();assert.equal(t.h.state.bookings.length,1);assert.equal(t.h.state.bookingTime,'23:30');assert.equal(t.h.state.bookingDuration,90);
});
test('booking cancel does not also open editor; edit and table delete route separate acknowledged commands',async()=>{
 const t=host();t.h.state.bookings=[clone(booking)];t.h.render();t.pump();const p=t.action('Отменить');assert.equal(t.calls[0].input.operation,'booking-cancel');assert.equal(t.h.document.querySelector('#edit-booking-name'),null);t.reply({hallTables:t.h.state.hallTables,bookings:[{...booking,status:'cancelled'}]});await p;t.pump();assert.equal(t.entries().find(i=>i.kind==='hallMap').tables[0].booked,false);t.h.editBooking('b');t.pump();const edit=t.action('Сохранить',{[t.field('Имя гостя').key]:'Мария 2'});assert.equal(t.calls[1].input.operation,'booking-edit');assert.equal(t.calls[1].input.guestName,'Мария 2');t.reply({hallTables:t.h.state.hallTables,bookings:[{...booking,status:'cancelled',guestName:'Мария 2'}]});await edit;t.pump();t.h.deleteHallTable('t');t.pump();const deletion=t.action('Удалить');assert.equal(t.calls[2].input.operation,'table-delete');assert.equal(t.h.state.hallTables.length,2);t.reply({hallTables:t.h.state.hallTables.filter(x=>x.id!=='t'),bookings:[]});await deletion;t.pump();assert.equal(t.h.state.hallTables.length,1);assert.equal(t.h.state.bookings.length,0);
});
test('uncertain hall commit blocks another attempt, stale/rollback actions cannot change persisted data',async()=>{
 const t=host();t.h.openCreateHallTableModal('square');t.pump();const old=t.model(),p=t.action('Добавить стол');t.calls[0].reject(Error('commit status is uncertain'));await p;t.pump();await t.action('Добавить стол');assert.equal(t.calls.length,1);assert.equal(t.h.criticalStorageRecoveryPending,true);await t.h.__nativeSettingsAction({action:'click',token:'stale',key:old.items.at(-1)?.key});t.h.MPosNativeHallUiEnabled=false;t.pump();assert.notEqual(t.h.document.querySelector('#modal-root .modal').style.opacity,'0');assert.equal(t.h.state.hallTables.length,2);
});
