const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {dom}=require('./helpers/product-editor-dom.cjs');
const read=n=>fs.readFileSync('app/src/main/assets/pos/'+n,'utf8');
function host(tab='purchaseOrders'){
 const sent=[],events=[],timers=[],writes=[];let resolve,reject;
 const h={PRODUCT_UNITS:{l:{kind:'volume'},ml:{kind:'volume'}},state:{loaded:true,tab,products:[{id:'milk',type:'simple',name:'Молоко',category:'Напитки',stockUnit:'l',stock:10,cost:2}],suppliers:[{id:'sup',name:'Поставщик',productIds:['milk']}],purchaseOrderSupplierId:'sup',purchaseOrderCart:[],purchaseOrders:[],receivings:[],receivingCart:[],inventoryConfig:{enabled:true,frequency:'monthly',productIds:['milk']},inventoryDraft:null,inventoryHistory:[],orders:[],employees:[{id:'e',name:'Иван',isAdmin:true}],shifts:[{id:'s',employeeId:'e'}],currency:'BYN'},criticalOperationBusy:false,criticalStorageRecoveryPending:false,innerWidth:1040,innerHeight:640,_purchaseExpanded:true,addEventListener:()=>{},setTimeout:f=>timers.push(f),Event:class{constructor(type){this.type=type}},webkit:{messageHandlers:{settingsScreen:{postMessage:p=>{sent.push(JSON.parse(JSON.stringify(p)));return true}},printer:{postMessage:p=>events.push(['share',p])}}},flash:m=>events.push(['flash',m]),markStorageBroken:()=>{},currentShift:()=>h.state.shifts[0],currentShiftEmployeeIsAdmin:()=>true,canEditCompanySettings:()=>true,stockUnit:p=>p?.stockUnit||'l',unitLabel:u=>u==='l'?'л':u==='ml'?'мл':u,stockQtyText:n=>String(n),roundStockQty:n=>Math.round((Number(n)+Number.EPSILON)*1000)/1000,productTracksStock:p=>p?.type==='simple'&&!p.noStockTracking,getProduct:id=>h.state.products.find(p=>p.id===id),storageSnapshot:o=>JSON.parse(JSON.stringify(o)),uid:(()=>{let n=0;return()=> 'synthetic-'+(++n)})(),fullMoney:v=>Number(v).toFixed(2)+' BYN',money:v=>Number(v).toFixed(2),fmtDate:()=> '07.10.2026',localDateString:d=>d.toISOString().slice(0,10),escapeHtml:s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;'),escapeAttr:s=>h.escapeHtml(s),productUnitOptions:(base,chosen)=>['l','ml'].map(u=>`<option value="${u}" ${chosen===u?'selected':''}>${h.unitLabel(u)}</option>`).join(''),convertProductQty:(q,from,to)=>Number(q)*(from==='ml'?0.001:1)/(to==='ml'?0.001:1),saveKey:(key,value)=>events.push(['save-key',key,JSON.parse(JSON.stringify(value))]),loadKey:async()=>null,commitCriticalStorage:(type,data)=>{events.push(['commit',type,data]);return new Promise((yes,no)=>{resolve=yes;reject=no})},publishAvailability:()=>events.push(['availability-gate']),PrilavokCore:{Storage:{set:(key,value)=>new Promise((yes,no)=>writes.push({key,value,yes,no}))}},navigator:{clipboard:{writeText:async text=>events.push(['copy',text])}},showModal:html=>{h.document.getElementById('modal-root').innerHTML='<div class="modal">'+html+'</div>'},closeModal:()=>{h.document.getElementById('modal-root').innerHTML=''},render:()=>{const renderers={purchaseOrders:'renderPurchaseOrdersScreen',receiving:'renderReceivingScreen',inventory:'renderInventoryScreen',inventoryWork:'renderInventoryWorkScreen'};h.document.getElementById('app').innerHTML=renderers[h.state.tab]?h[renderers[h.state.tab]]():'<div class="screen active"></div>'}};
 const fixture=dom(h);Object.assign(h,fixture);for(const id of ['warehouse-root','receiving-page-root']){const root=new fixture.Node();root.id=id;fixture.document.body.appendChild(root)}h.window=h;vm.createContext(h);for(const file of ['suppliers','purchase-orders','receiving-drafts','receiving-ui','receiving','inventory','warehouse-reporting'])vm.runInContext(read('Web/js/features/'+file+'.js'),h);vm.runInContext(read('native-settings-ui.js'),h);
 const flat=items=>items.flatMap(i=>[i,...(i.items?flat(i.items):[])]),model=()=>sent.filter(p=>['show','formShow','formPatch'].includes(p.action)).at(-1),entries=()=>flat(model().items),pump=()=>{while(timers.length)timers.shift()();fixture.pump()},settle=async()=>{await new Promise(setImmediate);pump()};
 const action=(label,fields={})=>h.__nativeSettingsAction({action:'click',token:model().token,key:entries().find(i=>i.kind==='button'&&i.label===label)?.key,fields});
 const change=fields=>h.__nativeSettingsAction({action:'change',token:model().token,fields});
 h.render();pump();return{h,sent,events,writes,pump,settle,model,entries,action,change,reply:()=>resolve(),fail:e=>reject(e)};
}
test('purchase quantity role buttons use original keypad and preserve packing preview without changing stock',async()=>{
 const t=host();assert.equal(t.model().action,'show');await t.action('Количество · 0');t.pump();assert.ok(t.entries().some(i=>i.kind==='grid'&&i.columns===3));assert.equal(t.model().hideCancel,false);await t.action('2');await t.action(',');await t.action('5');t.pump();assert.ok(t.entries().some(i=>i.text==='2,5'));await t.action('Готово');t.pump();assert.equal(t.h.state.purchaseOrderCart[0].requestedQty,'2.5');assert.equal(t.h.state.products[0].stock,10);assert.ok(t.entries().some(i=>(i.text||'').includes('На склад поступит: 2.5')));
});
test('purchase commit awaits acknowledgement, suppresses duplicate gestures and retains failed cart',async()=>{
 const t=host();await t.action('Количество · 0');t.pump();await t.action('3');await t.action('Готово');t.pump();const p=t.action('Сформировать заказ');t.pump();await t.action('Сформировать заказ');assert.equal(t.events.filter(e=>e[0]==='commit').length,1);assert.equal(t.h.state.purchaseOrders.length,0);t.fail(Error('disk failed'));await p;t.pump();assert.equal(t.h.state.purchaseOrderCart.length,1);assert.match(t.sent.filter(p=>p.action==='formResult').at(-1).message,/Заказ не сформирован/);const retry=t.action('Сформировать заказ');t.reply();await retry;t.pump();assert.equal(t.h.state.purchaseOrders.length,1);assert.equal(t.h.state.products[0].stock,10);assert.equal(t.h.state.purchaseOrderCart.length,0);assert.ok(t.entries().some(i=>(i.text||'').includes('Заказ поставщику')));await t.action('Поделиться');assert.equal(t.events.filter(e=>e[0]==='share').at(-1)[1].action,'sharePurchaseOrder');
});
test('supplier filter retains hidden selected IDs and create/edit rights while deletion keeps admin gate',async()=>{
 const t=host();t.h.state.products.push({id:'bread',name:'Хлеб',type:'simple',category:'Выпечка'});t.h.canEditCompanySettings=()=>false;t.h.openSupplierModal();t.pump();const name=t.entries().find(i=>i.label==='Название поставщика'),checks=t.entries().filter(i=>i.type==='checkbox');await t.change(Object.fromEntries(checks.map(i=>[i.key,true])));t.h.filterSupplierProducts('Молоко');t.pump();assert.equal(t.entries().filter(i=>i.type==='checkbox').length,1);const p=t.action('Создать',{[name.key]:'Новый'});assert.deepEqual(Array.from(t.writes[0].value.at(-1).productIds),['milk','bread']);assert.equal(t.h.state.suppliers.length,1);t.writes[0].yes();await p;t.pump();assert.equal(t.h.state.suppliers.length,2);t.h.deleteSupplier('sup');assert.ok(t.events.some(e=>e[1].includes?.('только администратор')));assert.equal(t.writes.length,1);
});
test('receiving document fields keep simultaneous quantity/total drafts before unit rerender and confirm exact stock',async()=>{
 const t=host('receiving');t.h._receivingDraft={version:1,orderId:null,supplierId:'sup',invoiceNumber:'',invoiceDate:'2026-10-07',lines:[{productId:'milk',qtyInput:'',unit:'l',priceInput:'',totalInput:'',priceMode:'total'}]};t.h.renderReceivingDocument();t.pump();assert.ok(t.entries().some(i=>i.kind==='field'&&i.type==='date'));const qty=t.entries().find(i=>i.label==='Принято'),total=t.entries().find(i=>i.label==='Сумма строки'),unit=t.entries().find(i=>i.label==='Единица');await t.change({[qty.key]:'2,',[total.key]:'6',[unit.key]:'ml'});t.pump();assert.equal(t.h._receivingDraft.lines[0].qtyInput,2000);assert.equal(Number(t.h._receivingDraft.lines[0].totalInput),6);await t.action('Далее');t.pump();const p=t.action('Подтвердить приход');t.pump();await t.action('Подтвердить приход');assert.equal(t.h.state.products[0].stock,10);assert.equal(t.events.filter(e=>e[0]==='commit').length,1);t.reply();await p;t.pump();assert.equal(t.h.state.products[0].stock,12);assert.equal(t.h.state.receivings[0].totalCost,6);
});
test('ordered receiving Back saves draft before leaving and failed save retains document',async()=>{
 const t=host('receiving');t.h.state.purchaseOrders=[{id:'po',supplierId:'sup',supplierName:'Поставщик',status:'pending',items:[{productId:'milk',productName:'Молоко',requestedQty:3,expectedQty:3,qty:3,requestedUnit:'l',stockUnit:'l'}]}];const opening=t.h.openReceivingDocument('po');t.writes[0].yes();await opening;t.pump();assert.equal(t.model().deferCancel,true);assert.equal(t.model().action,'show');const token=t.model().token,back=t.h.__nativeSettingsAction({action:'cancel',token});t.writes[1].no(Error('disk failed'));await back;t.pump();assert.ok(t.h.document.querySelector('.receiving-page'));assert.match(t.sent.filter(p=>p.action==='formResult').at(-1).message,/Не удалось сохранить черновик/);const retry=t.h.__nativeSettingsAction({action:'cancel',token:t.model().token});t.writes[2].yes();await retry;t.pump();assert.equal(t.h.document.querySelector('.receiving-page'),null);assert.equal(t.h.state.purchaseOrders[0].receivingIncomplete,true);
});
test('inventory fixes current stock after acknowledgement and completion keeps later sales',async()=>{
 const t=host('inventoryWork');t.h.state.inventoryDraft={id:'inv',type:'adhoc',items:[{productId:'milk',name:'Молоко',unit:'l',expected:10,actual:null}]};t.h.render();t.pump();const field=t.entries().find(i=>i.kind==='field');assert.equal(field.label,'Остаток, л');await t.change({[field.key]:'8'});const p=t.action('Фиксировать');t.pump();await t.action('Фиксировать');assert.equal(t.h.state.products[0].stock,10);t.reply();await p;t.pump();assert.equal(t.h.state.products[0].stock,8);assert.equal(t.h.state.inventoryDraft.items[0].difference,-2);t.h.state.products[0].stock=7;await t.action('Завершить инвентаризацию');t.pump();assert.ok(t.entries().some(i=>i.label==='Примерный убыток'&&i.value==='4.00'));const completion=t.action('Завершить инвентаризацию');t.reply();await completion;t.pump();assert.equal(t.h.state.products[0].stock,7);assert.equal(t.h.state.inventoryDraft,null);assert.equal(t.h.state.inventoryHistory.length,1);
});
test('warehouse tables preserve source headers/rows, date descriptors and selected export sections',async()=>{
 const t=host();t.h._warehouseFilters={from:'2026-10-01',to:'2026-10-07'};t.h.openWarehousePage();t.pump();assert.ok(t.entries().filter(i=>i.kind==='table').length>=3);const table=t.entries().find(i=>i.kind==='table');assert.ok(table.headers.length>0);assert.ok(table.rows.some(row=>row.includes('Молоко')));assert.deepEqual(t.entries().filter(i=>i.type==='date').map(i=>i.value),['2026-10-01','2026-10-07']);await t.action('Сформировать отчёт');t.pump();const format=t.entries().find(i=>i.label==='Формат отчёта');await t.action('Сформировать',{[format.key]:'xlsx'});assert.equal(t.events.filter(e=>e[0]==='share').at(-1)[1].action,'shareWarehouseExcel');
});
test('warehouse presentation rollback and stale callbacks never create a purchase',async()=>{
 const t=host();const old=t.model();await t.action('Количество · 0');t.pump();await t.h.__nativeSettingsAction({action:'click',token:old.token,key:t.entries().find(i=>i.label==='Готово').key});assert.equal(t.h.state.purchaseOrderCart.length,0);t.h.MPosNativeWarehouseUiEnabled=false;t.pump();assert.notEqual(t.h.document.querySelector('#modal-root .modal').style.opacity,'0');assert.equal(t.h.state.purchaseOrders.length,0);
});
