const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');const read=n=>fs.readFileSync('app/src/main/assets/pos/'+n,'utf8');
const NOW=Date.parse('2026-10-07T12:00:00Z'),START=Date.parse('2026-10-01T00:00:00Z'),END=Date.parse('2026-10-03T00:00:00Z');
function source(state,zone='UTC'){
 const previous=process.env.TZ;process.env.TZ=zone;const ctx={state:structuredClone(state),Date:class extends Date{constructor(...args){super(...(args.length?args:[NOW]))}static now(){return NOW}},localDateString:d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,fmtDate:ts=>new Date(ts).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}),getProduct:id=>ctx.state.products.find(p=>p.id===id)};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(read('Web/js/features/product-configuration.js'),ctx);vm.runInContext(read('Web/js/features/warehouse-reporting.js'),ctx);return{ctx,restore:()=>{if(previous===undefined)delete process.env.TZ;else process.env.TZ=previous}};
}
const product={id:'p',name:'Молоко',type:'simple',stockUnit:'l',stock:8,cost:4,minStock:9,extension:7};
const incoming=(at,qty=2,unit='l',total=10,extra={})=>({id:'r'+at,timestamp:at,supplierName:'Поставщик',totalCost:total,items:[{productId:'p',productName:'Старое имя',qty,stockUnit:unit,totalCost:total}],...extra});
const sale=(at,qty=1,extra={})=>({id:'o'+at,timestamp:at,items:[{productId:'p',qty,cost:3}],stockConsumption:{version:1,items:[{productId:'p',qty}]},...extra});
const base={products:[product],receivings:[],orders:[],company:{},currency:'₽'};
const cases=[
 ['empty',base],
 ['period-boundaries',{...base,receivings:[incoming(START-1),incoming(START),incoming(END-1),incoming(END),incoming(NOW+1)],orders:[sale(START-1,1,{returnedAt:START}),sale(START,2,{returnedAt:END-1}),sale(END),sale(NOW+1)]}],
 ['unit-conversion-and-suppliers',{...base,receivings:[incoming(START,500,'ml',20,{supplierName:'Первый',shortage:true,invoiceNumber:'x',invoiceDate:'2020-01-01'}),incoming(START+1,1,'l',10,{supplierName:'Второй'}),incoming(START+2,1,'l',10,{supplierName:'Первый'})]}],
 ['deleted-and-untracked',{...base,products:[{...product,noStockTracking:true},{id:'recipe',name:'Рецепт',type:'complex'}],receivings:[incoming(START),{id:'deleted',timestamp:START,items:[{productId:'gone',productName:'Удалён',stockUnit:'g',qty:50,unitCost:2}],shortage:true}],orders:[sale(START,2,{stockConsumption:{version:1,items:[{productId:'gone',qty:3},{productId:'recipe',qty:2}]}})]}],
 ['missing-cost-and-legacy-receiving',{...base,products:[{id:'p',name:'Молоко',type:'simple',stockUnit:'l',stock:8}],receivings:[{id:'old',timestamp:START,productId:'p',qty:2,unitCost:3,supplierName:''}],orders:[sale(START,2,{items:[{qty:2},{qty:2,cost:null},{qty:2,cost:'bad'},{qty:2,cost:4}]})]}],
 ['invalid-and-legacy-snapshots',{...base,orders:[sale(START,1,{stockConsumption:null,returnedAt:END+1}),sale(END+1,1,{stockConsumption:{version:'1',items:[]}}),sale(START,1,{stockConsumption:{version:1,items:[{productId:'p',qty:1},{productId:'p',qty:2}]}}),sale(START,1,{stockConsumption:{version:1,items:[null]}}),sale(START,1,{stockConsumption:{version:1,items:[{productId:'p',qty:-1}]}})]}],
 ['invalid-receiving-and-admin-tombstone',{...base,receivings:[incoming(START,2,'kg',10),incoming(START,-1),incoming(START,'bad'),incoming(START,2,'l','bad'),incoming(START,2,'l',10,{adminDeleted:true}),{timestamp:START,items:[{productId:'p',qty:2}]}]}],
 ['null-zero-and-missing-fields',{...base,products:[{...product,cost:null,stock:null},{id:'missing',name:'Прочерк',type:'simple',stockUnit:'piece'}],receivings:[incoming(START,null),{timestamp:START,items:[{productId:'p',qty:1,unitCost:0}]},{timestamp:START,items:[{productId:'p',qty:0,totalCost:0,stockUnit:null}]}],orders:[sale(START,0,{items:[{cost:2,qty:null}]})]}],
 ['name-order',{...base,products:['Milk','milk','Ёж','Еж','Арбуз','яблоко'].map((name,i)=>({...product,id:'n'+i,name,stock:1,cost:1}))}],
 ['numeric-duplicate-snapshot',{...base,orders:[sale(START,1,{stockConsumption:{version:1,items:[{productId:1,qty:1},{productId:1.0,qty:2}]}})]}],
 ['moscow-local-days',{...base,receivings:[incoming(START-3*3600000-1),incoming(START-3*3600000),incoming(END-3*3600000-1),incoming(END-3*3600000)]},'Europe/Moscow'],
 ['dst-local-day',{...base,receivings:[incoming(Date.parse('2025-10-25T22:00:00Z')),incoming(Date.parse('2025-10-26T22:59:59Z')),incoming(Date.parse('2025-10-26T23:00:00Z'))]},'Europe/Berlin','2025-10-26','2025-10-26'],
 ['leap-day',base,'UTC','2024-02-29','2024-02-29'],
 ['bad-date',base,'UTC','2026-02-29','2026-03-01'],['bad-format',base,'UTC','2026-1-1','2026-01-02'],['reversed',base,'UTC','2026-10-03','2026-10-02'],['future',base,'UTC','2026-10-08','2026-10-08']
];
function fixture([label,state,zone='UTC',from='2026-10-01',to='2026-10-02']){
 const h=source(state,zone),request={version:1,from,to,now:NOW,validationNow:NOW,zone};let expected;
 try{const report=JSON.parse(JSON.stringify(h.ctx.warehouseReport(from,to,NOW)));delete report.generatedAt;for(const d of report.documents)delete d.received;report.generatedTimestamp=NOW;expected={allowed:true,report}}catch(e){expected={allowed:false,message:e.message}}finally{h.restore()}return{label,request,state,expected};
}
test('warehouse fixtures independently capture reviewed source periods, movements and warnings',()=>{const actual=cases.map(fixture);if(process.env.MPOS_WRITE_WAREHOUSE_FIXTURES)fs.writeFileSync('tests/fixtures/warehouse-reports.json',JSON.stringify(actual,null,2)+'\n');assert.deepEqual(actual,JSON.parse(fs.readFileSync('tests/fixtures/warehouse-reports.json','utf8')))});
function host(){
 const h=source(base),calls=[],events=[],sent=[],elements={'app':{inert:false},'warehouse-root':{innerHTML:''},'warehouse-from':{value:'2026-10-01'},'warehouse-to':{value:'2026-10-02'},'warehouse-report-format':{value:'xlsx'}};
 const c=h.ctx;Object.assign(c,{MPosCore:{Warehouse:{read:input=>new Promise((resolve,reject)=>calls.push({input,resolve,reject}))}},Intl,document:{getElementById:id=>elements[id]||null,querySelectorAll:()=>[{value:'0'},{value:'2'}]},currentShiftEmployeeIsAdmin:()=>true,flash:m=>events.push(m),closeModal:()=>events.push('close-modal'),console:{error:()=>{}},webkit:{messageHandlers:{printer:{postMessage:x=>sent.push(x)},telegram:{postMessage:x=>sent.push(x)}}},telegramConfigFromState:()=>({enabled:true,notifyMonthlyWarehouse:true,botToken:'fixture-only',chatId:'fixture-only'}),previousCalendarMonthRange:()=>({key:'2026-09',from:'2026-09-01',to:'2026-09-30'}),escapeHtml:String,escapeAttr:String,money:v=>String(v),unitLabel:v=>String(v)});
 c._warehouseFilters={from:'2026-10-01',to:'2026-10-02'};const originalMonthly=()=>{const p=c.previousCalendarMonthRange();c.webkit.messageHandlers.telegram.postMessage({action:'sendMonthlyWarehouseReport',report:c.warehouseExportPayload(c.warehouseReport(p.from,p.to))})};c.maybeSendMonthlyWarehouseReport=originalMonthly;vm.runInContext(read('native-warehouse.js'),c);
 return{...h,calls,events,sent,elements,result:JSON.parse(fs.readFileSync('tests/fixtures/warehouse-reports.json','utf8'))[0].expected.report};
}
function ack(h,index=0){h.calls[index].resolve({ok:true,authoritative:true,report:{...structuredClone(h.result),from:h.calls[index].input.from,to:h.calls[index].input.to}})}
test('warehouse page renders only authoritative report, stale filters and close cannot reopen page',async()=>{const h=host();try{const first=h.ctx.renderWarehousePage();assert.equal(h.elements.app.inert,false);h.ctx._warehouseFilters={from:'2026-10-02',to:'2026-10-02'};const second=h.ctx.renderWarehousePage();ack(h,1);assert.equal(await second,true);const html=h.elements['warehouse-root'].innerHTML;ack(h,0);assert.equal(await first,false);assert.equal(h.elements['warehouse-root'].innerHTML,html);const pending=h.ctx.renderWarehousePage();h.ctx.closeWarehousePage();ack(h,2);assert.equal(await pending,false);assert.equal(h.elements['warehouse-root'].innerHTML,'');assert.equal(h.elements.app.inert,false)}finally{h.restore()}});
test('read failure never falls back to JavaScript inventory calculations',async()=>{const h=host();try{const p=h.ctx.renderWarehousePage();h.calls[0].reject(Error('read failed'));assert.equal(await p,false);assert.equal(h.elements['warehouse-root'].innerHTML,'');assert.match(h.events[0],/read failed/);assert.throws(()=>h.ctx.warehouseReport('2026-10-01','2026-10-02'),/ещё не загружен/)}finally{h.restore()}});
test('export freezes section/format/date selection and prevents repeated dispatch while waiting',async()=>{const h=host();try{const p=h.ctx.generateWarehouseReport();assert.equal(h.sent.length,0);assert.equal(await h.ctx.generateWarehouseReport(),false);h.elements['warehouse-report-format'].value='pdf';h.elements['warehouse-from'].value='2026-10-02';ack(h);assert.equal(await p,true);assert.equal(h.sent[0].action,'shareWarehouseExcel');assert.equal(h.sent[0].report.sections.length,2);assert.equal(h.sent[0].report.period,'2026-10-01 — 2026-10-02');assert.ok(h.events.includes('close-modal'))}finally{h.restore()}});
test('PDF and monthly Telegram use native read; revoked UI access and rollback retain rules',async()=>{const h=host();try{const p=h.ctx.exportWarehousePDF(true);ack(h);assert.equal(await p,true);assert.equal(h.sent[0].action,'shareWarehouseReport');assert.equal(h.sent[0].report.sections.length,1);const monthly=h.ctx.maybeSendMonthlyWarehouseReport();assert.equal(h.calls[1].input.from,'2026-09-01');ack(h,1);assert.equal(await monthly,true);assert.equal(h.sent[1].action,'sendMonthlyWarehouseReport');h.ctx.currentShiftEmployeeIsAdmin=()=>false;assert.equal(await h.ctx.renderWarehousePage(),false);assert.equal(h.calls.length,2);h.ctx.currentShiftEmployeeIsAdmin=()=>true;h.ctx.MPosNativeWarehouseEnabled=false;await h.ctx.renderWarehousePage();assert.equal(h.calls.length,2);assert.ok(h.elements.app.inert)}finally{h.restore()}});
