const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {dom}=require('./helpers/product-editor-dom.cjs');
const read=n=>fs.readFileSync('app/src/main/assets/pos/'+n,'utf8');
function host(){
 const sent=[],events=[],timers=[],requests=[];let resolve,reject;
 const h={state:{loaded:true,tab:'pos',cart:[{productId:'milk',name:'Молоко',qty:1,price:12.5}],parked:[],products:[{id:'milk',name:'Молоко',category:'Напитки'}],customer:{name:'',phone:'',address:'Старый адрес'},loyaltyPrograms:[],loyaltyRedemptions:{},orderType:'На месте',orderLabel:'',employees:[{id:'e',name:'Иван'}],shifts:[{id:'s',employeeId:'e'}]},criticalOperationBusy:false,criticalStorageRecoveryPending:false,innerWidth:1000,innerHeight:800,addEventListener:()=>{},setTimeout:f=>timers.push(f),Event:class{constructor(type){this.type=type}},webkit:{messageHandlers:{settingsScreen:{postMessage:p=>{sent.push(JSON.parse(JSON.stringify(p)));return true}}}},flash:m=>events.push(['flash',m]),currentShift:()=>h.state.shifts[0],currentShiftEmployeeIsAdmin:()=>false,storageSnapshot:o=>JSON.parse(JSON.stringify(o)),cartTotal:()=>12.5,cartSubtotal:()=>12.5,getProduct:id=>h.state.products.find(p=>p.id===id),modifierSelectionSignature:()=>'',uid:()=> 'parked1',fullMoney:v=>Number(v).toFixed(2)+' BYN',fmtDate:()=> '07.10.2026',escapeHtml:s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;'),escapeAttr:s=>h.escapeHtml(s),emptyCurrentOrderSession:()=>({items:[]}),saveCurrentOrderSession:()=>events.push(['session']),resetCurrentOrderState:()=>{h.state.cart=[];h.state.orderLabel=''},commitCriticalStorage:(type,writes)=>{events.push(['commit',type,writes]);return new Promise((yes,no)=>{resolve=yes;reject=no})},showModal:html=>{h.document.getElementById('modal-root').innerHTML='<div class="modal">'+html+'</div>'},closeModal:()=>{h.document.getElementById('modal-root').innerHTML=''},render:()=>{events.push(['render']);if(h.state.loyaltyAdminScreen)h.document.getElementById('app').innerHTML=h.renderLoyaltyAdminScreen()},showAdminOnlyInfo:()=>events.push(['admin-refusal'])};
 const fixture=dom(h);Object.assign(h,fixture);h.window=h;vm.createContext(h);vm.runInContext(read('Web/js/features/parked-orders.js'),h);vm.runInContext(read('Web/js/features/loyalty.js'),h);h.loyaltyApi=(path,options)=>{events.push(['api',path,options]);return new Promise((yes,no)=>requests.push({path,yes,no}))};vm.runInContext(read('native-settings-ui.js'),h);
 const flat=items=>items.flatMap(i=>[i,...(i.items?flat(i.items):[])]),model=()=>sent.filter(p=>['show','formShow','formPatch'].includes(p.action)).at(-1),entries=()=>flat(model().items),pump=()=>{while(timers.length)timers.shift()();fixture.pump()},settle=async()=>{await new Promise(setImmediate);pump()};
 const action=(label,fields={})=>h.__nativeSettingsAction({action:'click',token:model().token,key:entries().find(i=>i.kind==='button'&&i.label===label)?.key,fields});
 const change=(id,value)=>h.__nativeSettingsAction({action:'change',token:model().token,fields:{[entries().find(i=>i.kind==='field'&&i.key&&h.document.getElementById(id)&&i.label=== (id==='customer-search'?'Номер телефона':id))?.key||entries().find(i=>i.kind==='field')?.key]:value}});
 return{h,sent,events,requests,pump,settle,model,entries,action,change,reply:()=>resolve(),fail:e=>reject(e)};
}
test('park label commit locks gestures, retains failure draft and saves before clearing cart',async()=>{
 const t=host();t.h.parkOrder();t.pump();assert.ok(t.entries().some(i=>i.label==='Подпись'));const label=t.entries().find(i=>i.kind==='field').key;const p=t.action('Отложить',{[label]:'Стол 7'});t.pump();await t.action('Отложить');assert.equal(t.events.filter(e=>e[0]==='commit').length,1);assert.equal(t.h.state.cart.length,1);t.fail(Error('disk failed'));await p;t.pump();assert.equal(t.h.state.cart.length,1);assert.equal(t.h.state.parked.length,0);assert.match(t.sent.filter(x=>x.action==='formResult').at(-1).message,/Чек не отложен/);const retry=t.action('Отложить',{[label]:'Стол 7'});t.reply();await retry;t.pump();assert.equal(t.h.state.cart.length,0);assert.equal(t.h.state.parked[0].orderLabel,'Стол 7');assert.equal(t.h.document.querySelector('#modal-root .modal'),null);
});
test('parked list preserves original current-cart refusal, mounted resume/delete and comments',async()=>{
 const t=host();t.h.state.parked=[{id:'old',orderLabel:'Стол 4',items:[{productId:'milk',qty:2}],total:25,createdAt:1,comment:'Без сахара',customer:{name:'Гость',address:'Адрес'},printedItems:[{key:'milk',qty:2}]}];t.h.openParkedModal();t.pump();assert.ok(t.entries().some(i=>(i.text||'').includes('Без сахара')));await t.action('Открыть');assert.match(t.sent.filter(x=>x.action==='formResult').at(-1).message,/завершите текущий заказ/);t.h.state.cart=[];const p=t.action('Открыть');t.reply();await p;t.pump();assert.equal(t.h.state.cart[0].qty,2);assert.equal(t.h.state.parked.length,0);assert.equal(t.h.__currentOrderPrintedItems[0].qty,2);assert.equal(t.events.filter(e=>e[0]==='commit').at(-1)[1],'resume-parked');
});
test('cashier customer live search remains editable and rejects stale responses',async()=>{
 const t=host();await t.h.openCustomerPicker();t.pump();const field=t.entries().find(i=>i.kind==='field');assert.equal(field.maxLength,9);await t.h.__nativeSettingsAction({action:'change',token:t.model().token,fields:{[field.key]:'2912'}});t.pump();assert.equal(t.h.document.getElementById('customer-search').value,'2912');assert.equal(t.model().pending,false);assert.ok(t.entries().some(i=>i.text==='Поиск…'));await t.h.__nativeSettingsAction({action:'change',token:t.model().token,fields:{[field.key]:'3312'}});t.requests[1].yes({customers:[{id:'new',name:'Новый',normalized_phone:'+375331234567'}]});await t.settle();t.requests[0].yes({customers:[{id:'old',name:'Старый',normalized_phone:'+375291234567'}]});await t.settle();assert.ok(t.entries().some(i=>i.label==='Новый · +375331234567 · Выбрать'));assert.ok(!t.entries().some(i=>(i.label||'').includes('Старый')));const p=t.action('Новый · +375331234567 · Выбрать');assert.equal(t.h.state.customer.id,'new');assert.equal(t.h.state.customer.address,'Старый адрес');t.requests.at(-1).yes({customer:{id:'new',name:'Новый',normalized_phone:'+375331234567'},programs:[]});await p;t.pump();assert.equal(t.h.document.querySelector('#modal-root .modal'),null);
});
test('customer profile gift selection and removal keep source semantics and explicit Done/back',async()=>{
 const t=host();t.h.state.customer={id:'c',name:'Гость',phone:'123',address:'Адрес'};t.h.state.loyaltyCustomerId='c';t.h.state.loyaltyPrograms=[{id:'gift',name:'Кофе',rewards:1,required_quantity:5}];t.h.openOrderCustomer();t.pump();assert.ok(t.entries().some(i=>i.label==='Убрать клиента из заказа'));assert.equal(t.model().hideCancel,true);assert.equal(t.entries().filter(i=>i.label==='Готово').length,1);const field=t.entries().find(i=>i.kind==='field');await t.h.__nativeSettingsAction({action:'change',token:t.model().token,fields:{[field.key]:'1'}});t.pump();assert.equal(t.h.state.loyaltyRedemptions.gift,1);await t.action('Убрать клиента из заказа');t.pump();assert.equal(t.h.state.customer.id,undefined);assert.equal(t.h.state.customer.address,'Адрес');assert.deepEqual(Object.keys(t.h.state.loyaltyRedemptions),[]);
});
test('customer search error and profile loading/retry keep reviewed messages',async()=>{
 const t=host();await t.h.openCustomerPicker();t.pump();const field=t.entries().find(i=>i.kind==='field');await t.h.__nativeSettingsAction({action:'change',token:t.model().token,fields:{[field.key]:'2912'}});t.requests[0].no(Error('offline'));await t.settle();assert.ok(t.entries().some(i=>i.text==='Нет связи с сервером. Повторите поиск.'));t.h.state.customer={id:'c',name:'Гость'};t.h.state.loyaltyLoadError='offline';t.h.state.loyaltyLoadingCustomerId='';t.h.renderOrderCustomerModal();t.pump();assert.ok(t.entries().some(i=>i.text==='Не удалось загрузить программы'));assert.ok(t.entries().some(i=>i.label==='Повторить'));
});
test('native loyalty editor submits original selected product IDs, waits and preserves server refusal',async()=>{
 const t=host();t.h.loyaltyProgramForm();t.pump();const fields=t.entries().filter(i=>i.kind==='field'),name=fields.find(i=>i.label==='Название программы'),quantity=fields.find(i=>i.label==='Купить товаров'),checks=fields.filter(i=>i.type==='checkbox');assert.equal(checks.length,2);const values={[name.key]:'Кофе',[quantity.key]:'5',...Object.fromEntries(checks.map(i=>[i.key,true]))};const p=t.action('Создать программу',values);t.pump();assert.equal(t.requests.length,1);const body=JSON.parse(t.events.find(e=>e[0]==='api')[2].body);assert.deepEqual(body.earningProductIds,['milk']);assert.deepEqual(body.rewardProductIds,['milk']);assert.equal(body.rewardQuantity,1);await t.action('Создать программу',values);assert.equal(t.requests.length,1);t.requests[0].no(Error('Программа уже существует'));await p;t.pump();assert.match(t.sent.filter(p=>p.action==='formResult').at(-1).message,/уже существует/);assert.equal(t.h.document.getElementById('lp-name').value,'Кофе');
});
test('administrator screen preserves entry permission and adjustment role check',async()=>{
 const t=host();t.h.openLoyaltyAdminScreen();assert.deepEqual(t.events,[['admin-refusal']]);t.h.state.tab='settings';t.h.state.settingsAdminPanel=true;t.h.openLoyaltyAdminScreen();t.pump();assert.equal(t.model().action,'show');assert.ok(t.entries().some(i=>i.text==='Программа лояльности'));t.h.openLoyaltyAdjustment('c','p','Кофе');t.pump();assert.ok(t.entries().some(i=>i.type==='password'));await t.action('Сохранить');assert.match(t.sent.filter(p=>p.action==='formResult').at(-1).message,/права администратора/);assert.equal(t.events.filter(e=>e[0]==='api').length,1);
});
test('presentation rollback and stale token cannot change customer or parked data',async()=>{
 const t=host();await t.h.openCustomerPicker();t.pump();const old=t.model();t.h.openCreateCustomer();t.pump();await t.h.__nativeSettingsAction({action:'click',token:old.token,key:t.entries().find(i=>i.label==='Создать').key});assert.equal(t.requests.length,0);t.h.MPosNativeCustomerUiEnabled=false;t.pump();assert.notEqual(t.h.document.querySelector('#modal-root .modal').style.opacity,'0');assert.equal(t.h.state.customer.id,undefined);assert.equal(t.h.state.parked.length,0);
});
test('async Back preserves source failed-navigation message and keeps the adjustment form open',async()=>{
 const t=host();t.h.openLoyaltyAdjustment('c','p','Кофе');t.pump();const token=t.model().token;const p=t.h.__nativeSettingsAction({action:'cancel',token});t.requests[0].no(Error('offline'));await p;t.pump();assert.equal(t.model().token,token);assert.match(t.sent.filter(p=>p.action==='formResult').at(-1).message,/Не удалось открыть клиента/);assert.ok(t.h.document.getElementById('la-admin-password'));
});
test('native administrator search patches geometry without hiding or replacing its mounted token',async()=>{
 const t=host();t.h.state.tab='settings';t.h.state.loyaltyAdminScreen=true;t.h.state.loyaltyAdminSection='clients';t.h.render();t.pump();const token=t.model().token;const field=t.entries().find(i=>i.kind==='field');assert.equal(field.label,'Найти клиента');t.h.innerWidth=900;t.pump();assert.equal(t.model().token,token);assert.equal(t.model().action,'formPatch');assert.equal(t.model().viewportWidth,900);assert.ok(!t.sent.some(p=>p.action==='hide'));assert.equal(t.entries().find(i=>i.kind==='field').key,field.key);
});
test('late native command replacement is awaited and duplicate gestures stay blocked',async()=>{
 const t=host();t.h.openCreateCustomer();t.pump();let finish,count=0;t.h.createCustomerFromPos=()=>{count++;return new Promise(resolve=>{finish=resolve})};const p=t.action('Создать');t.pump();await t.action('Создать');assert.equal(count,1);finish();await p;t.pump();assert.equal(count,1);
});
test('loyalty product filtering preserves checked hidden product IDs in the source save command',async()=>{
 const t=host();t.h.state.products.push({id:'bread',name:'Хлеб',category:'Выпечка'});t.h.loyaltyProgramForm();t.pump();const checks=t.entries().filter(i=>i.type==='checkbox');await t.h.__nativeSettingsAction({action:'change',token:t.model().token,fields:Object.fromEntries(checks.map(i=>[i.key,true]))});t.h.filterLoyaltyProducts('earning','Молоко');t.pump();assert.equal(t.entries().filter(i=>i.type==='checkbox').length,3);const name=t.entries().find(i=>i.label==='Название программы'),quantity=t.entries().find(i=>i.label==='Купить товаров');const p=t.action('Создать программу',{[name.key]:'Программа',[quantity.key]:'5'});const body=JSON.parse(t.events.find(e=>e[0]==='api')[2].body);assert.deepEqual(body.earningProductIds,['milk','bread']);assert.deepEqual(body.rewardProductIds,['milk','bread']);t.requests[0].no(Error('synthetic server refusal'));await p;
});
test('new customer form forwards entered values and awaits creation and profile replies once',async()=>{
 const t=host();t.h.openCreateCustomer();t.pump();const name=t.entries().find(i=>i.label==='Имя'),phone=t.entries().find(i=>i.label==='Телефон');const p=t.action('Создать',{[name.key]:'Гость',[phone.key]:'+375291234567'});await t.action('Создать');assert.equal(t.requests.length,1);assert.equal(t.h.state.customer.id,undefined);const event=t.events.find(e=>e[0]==='api');assert.deepEqual(JSON.parse(event[2].body),{name:'Гость',phone:'+375291234567'});t.requests[0].yes({customer:{id:'created',name:'Гость',normalized_phone:'+375291234567'}});await new Promise(setImmediate);assert.equal(t.requests[1].path,'/api/customers/created/loyalty');t.requests[1].yes({customer:{id:'created',name:'Гость',normalized_phone:'+375291234567'},programs:[]});await p;t.pump();assert.equal(t.h.state.customer.id,'created');assert.equal(t.h.state.customer.address,'Старый адрес');assert.equal(t.h.document.querySelector('#modal-root .modal'),null);
});
