const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const read=n=>fs.readFileSync('app/src/main/assets/pos/'+n,'utf8'),tick=()=>new Promise(r=>setImmediate(r));
function host(){const sent=[],fallback=[],events=[],state={network:{backendUrl:'https://example.invalid/prefix',deviceKey:'synthetic-test-key',deviceName:'test'},products:[],categoryOnlineOrder:{},categoryOnlineMenu:{}};const ctx={state,Date,Map,Set,Object,String,Number,Promise,Error,DOMException,AbortController,setTimeout,clearTimeout,queueMicrotask,console,networkConfigFromState:()=>state.network,fetch:async(...args)=>{fallback.push(args);return{ok:true}},webkit:{messageHandlers:{network:{postMessage:p=>{sent.push(p);events.push('network');return true}}}},saveNetworkSettings:()=>true,setNetworkStatus:()=>{},saveKey:()=>events.push('saved-status'),render:()=>{},flash:message=>events.push(message),publishAvailability:()=>events.push('availability-source-hook')};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(read('native-catalog-transport.js'),ctx);return{ctx,sent,fallback,events,reply:(request,data={},status=200)=>ctx.__nativeNetworkResult({requestId:request.requestId,ok:true,authoritative:true,httpOk:status>=200&&status<300,httpStatus:status,data})}}
test('manual sync retains actual source payload, server status and explicit trigger',async()=>{const h=host();const html=read('pos.html');vm.runInContext(html.slice(html.indexOf('function buildMenuSyncPayload(){'),html.indexOf('function renderNetworkScreen(){')),h.ctx);assert.equal(h.sent.length,0);h.ctx.state.products=[{id:'p',name:'Milk',price:5,category:'Dairy',availableOnline:true}];const p=h.ctx.syncMenuToBackend();assert.equal(h.sent.length,1);const request=h.sent[0],body=JSON.parse(request.body);assert.equal(request.kind,'menu');assert.equal(body.products[0].externalId,'p');assert.equal(body.categories[0].externalId,'category:Dairy');h.reply(request,{categories:1,products:1});await p;assert.match(h.ctx.state.network.lastSyncStatus,/1 категорий, 1 товаров/);assert.equal(h.fallback.length,0)});
test('sync HTTP failure remains manual and does not create retry timers',async()=>{const h=host(),html=read('pos.html');vm.runInContext(html.slice(html.indexOf('function buildMenuSyncPayload(){'),html.indexOf('function renderNetworkScreen(){')),h.ctx);const p=h.ctx.syncMenuToBackend();h.reply(h.sent[0],{error:'server refused'},503);await p;assert.match(h.ctx.state.network.lastSyncStatus,/server refused/);await tick();assert.equal(h.sent.length,1)});
test('abort cancels native call, ignores late result and leaves unrelated fetch delegated',async()=>{const h=host(),controller=new AbortController();const p=h.ctx.fetch('https://example.invalid/prefix/api/media/upload',{method:'POST',body:'{}',signal:controller.signal});const first=h.sent[0];controller.abort();await assert.rejects(p,e=>e.name==='AbortError');assert.equal(h.sent[1].action,'catalogCancel');h.reply(first,{url:'late'});await h.ctx.fetch('https://example.invalid/prefix/unrelated');assert.equal(h.fallback.length,1);h.ctx.MPosNativeCatalogTransportEnabled=false;await h.ctx.fetch('https://example.invalid/prefix/api/menu/sync',{method:'POST',body:'{}'});assert.equal(h.fallback.length,2)});
test('native timeout keeps media AbortError contract and already aborted signal sends nothing',async()=>{const h=host(),controller=new AbortController();controller.abort();await assert.rejects(h.ctx.fetch('https://example.invalid/prefix/api/media/upload',{method:'POST',body:'{}',signal:controller.signal}),e=>e.name==='AbortError');assert.equal(h.sent.length,0);const p=h.ctx.fetch('https://example.invalid/prefix/api/media/upload',{method:'POST',body:'{}'});h.ctx.__nativeNetworkResult({requestId:h.sent[0].requestId,ok:false,timeout:true});await assert.rejects(p,e=>e.name==='AbortError')});
test('actual product save persists before media and HTTP 413 retains local image for retry',async()=>{for(const status of [200,413]){const h=host(),nodes={};for(const [name,value]of Object.entries({name:'Milk',category:'Dairy',price:'5',cost:'1',stock:'3',description:'',symbol:''}))nodes['pf-'+name]={value};h.ctx.document={getElementById:id=>nodes[id],querySelector:()=>null};Object.assign(h.ctx,{_pmType:'simple',_pmLocalImageId:'new-image',_pmImageData:'data:image/png;base64,synthetic',currentShiftEmployeeIsAdmin:()=>true,limitTileSymbol:x=>x,getProduct:id=>h.ctx.state.products.find(p=>p.id===id),validateModifierGroups:()=>{},normalizeModifierGroup:x=>x,saveProductConfiguration:()=>{},storageSnapshot:x=>structuredClone(x),syncCategoryOrder:()=>{},closeModal:()=>h.events.push('close'),PrilavokCore:{Storage:{set:async()=>h.events.push('local-saved')}}});h.ctx.state.products=[{id:'p',name:'Old',type:'simple',category:'Dairy',price:2,cost:1,stock:3}];vm.runInContext(read('Web/js/features/product-persistence.js'),h.ctx);const p=h.ctx.saveProduct('p');await tick();assert.equal(h.sent.length,1);assert.ok(h.events.indexOf('local-saved')<h.events.indexOf('network'));assert.equal(JSON.parse(h.sent[0].body).productId,'p');h.reply(h.sent[0],status===200?{url:'https://example.invalid/image.png'}:{error:'too big'},status);assert.equal(await p,true);assert.equal(h.ctx.state.products[0].name,'Milk');assert.equal(h.ctx.state.products[0].localImageId,'new-image');if(status===413){assert.equal(h.ctx.state.products[0].imageUploadPending,true);assert.ok(h.events.some(x=>x.includes('фото слишком большое')))}else{assert.equal(h.ctx.state.products[0].imageUploadPending,undefined);assert.equal(h.ctx.state.products[0].imageUrl,'https://example.invalid/image.png')}}});

test('backend health, settings and report use native allowlist; HTTP failures are retained',async()=>{
 const h=host();for(const [path,method,kind]of [['/health','GET','health'],['/api/device/telegram-settings','PUT','telegramSettings'],['/api/orders/test','POST','testOrder'],['/api/orders/events?deviceKey=synthetic-test-key','GET','eventsProbe'],['/api/device/live-report/abcdefghijklmnopqrst','POST','liveReport']]){const p=h.ctx.fetch('https://example.invalid/prefix'+path,{method,body:method==='GET'?undefined:'{}'});const r=h.sent.at(-1);assert.equal(r.action,'backendExchange');assert.equal(r.kind,kind);h.reply(r,{},401);assert.equal((await p).status,401)}assert.equal(h.fallback.length,0);
});
test('manual registration completion reconnects order stream; refused sync does not',async()=>{
 const h=host();let restarts=0;h.ctx.startWebOrderEvents=()=>restarts++;for(const status of [401,200]){const p=h.ctx.fetch('https://example.invalid/prefix/api/menu/sync',{method:'POST',body:'{}'});h.reply(h.sent.at(-1),{},status);await p}assert.equal(restarts,1);
});
