const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {dom}=require('./helpers/product-editor-dom.cjs');
const read=n=>fs.readFileSync('app/src/main/assets/pos/'+n,'utf8');
function host(){
 const sent=[],events=[],timers=[];let resolve,reject;
 const h={state:{loaded:true,tab:'pos',cart:[{productId:'milk',name:'Молоко',qty:1,price:12.5}],discounts:[],loyaltyPrograms:[],loyaltyRedemptions:{},products:[{id:'milk',name:'Молоко',type:'simple',stock:20,cost:5}],orders:[],shifts:[{id:'s',employeeId:'e',cashMovements:[]}],employees:[{id:'e',name:'Иван'}],customer:{name:''},orderType:'На месте',deliveryFee:0,deliveryRates:[],currency:'BYN'},criticalOperationBusy:false,criticalStorageRecoveryPending:false,innerWidth:1000,innerHeight:800,addEventListener:()=>{},setTimeout:f=>timers.push(f),Event:class{constructor(type){this.type=type}},webkit:{messageHandlers:{settingsScreen:{postMessage:p=>{sent.push(JSON.parse(JSON.stringify(p)));return true}}}},flash:m=>events.push(['flash',m]),currentShift:()=>h.state.shifts[0],canFulfillCart:()=>true,cartTotal:()=>12.5,itemTotal:i=>i.price*i.qty,discountValue:()=>0,loyaltyReceiptSnapshot:()=>({discount:0,programs:[]}),loyaltyRewardAllocation:()=>({allocations:{}}),checkedStockConsumption:()=>({items:[{productId:'milk',qty:1}]}),storageSnapshot:o=>JSON.parse(JSON.stringify(o)),roundStockQty:n=>n,emptyCurrentOrderSession:()=>({version:1,cart:[]}),currentOrderSessionSnapshot:d=>({paymentDraft:d}),uid:(()=>{let i=0;return()=> 'synthetic-'+(++i)})(),getProduct:id=>h.state.products.find(p=>p.id===id),fullMoney:v=>Number(v).toFixed(2)+' BYN',money:v=>Number(v).toFixed(2),fmtDate:()=> '07.10.2026',escapeHtml:s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;'),escapeAttr:s=>h.escapeHtml(s),resetCurrentOrderState:()=>{h.state.cart=[]},commitCriticalStorage:(type,writes)=>{events.push(['commit',type,writes]);return new Promise((yes,no)=>{resolve=yes;reject=no})},publishAvailability:()=>events.push(['availability']),publishPaidOrderLoyalty:()=>events.push(['loyalty']),printCompletedOrder:()=>events.push(['print']),showModal:html=>{h.document.getElementById('modal-root').innerHTML='<div class="modal">'+html+'</div>'},closeModal:()=>{h.document.getElementById('modal-root').innerHTML=''},render:()=>events.push(['render']),openOrderSettings:()=>events.push(['delivery-settings']),printReceipt:id=>events.push(['manual-print',id])};
 const fixture=dom(h);Object.assign(h,fixture);h.window=h;vm.createContext(h);vm.runInContext(read('Web/js/features/payment.js'),h);vm.runInContext(read('native-settings-ui.js'),h);
 const flat=items=>items.flatMap(i=>[i,...(i.items?flat(i.items):[])]),model=()=>sent.filter(p=>p.action==='formShow'||p.action==='formPatch').at(-1),entries=()=>flat(model().items);
 const pump=()=>{while(timers.length)timers.shift()();fixture.pump()};
 const action=(label,fields={})=>h.__nativeSettingsAction({action:'click',token:sent.filter(p=>p.action==='formShow').at(-1).token,key:entries().find(i=>i.kind==='button'&&i.label===label)?.key,fields});
 const back=()=>h.__nativeSettingsAction({action:'cancel',token:sent.filter(p=>p.action==='formShow').at(-1).token});
 h.openPaymentModal();pump();return{h,sent,events,pump,model,entries,action,back,reply:()=>resolve(),fail:e=>reject(e)};
}
test('actual payment page models exact formatted receipt/tender/change and mounted amount role button',async()=>{const t=host();assert.equal(t.model().expanded,true);assert.equal(t.model().deferCancel,true);assert.ok(t.entries().some(i=>i.kind==='metric'&&i.label==='Молоко × 1'&&i.value==='12.50'));assert.ok(t.entries().some(i=>i.label==='К оплате'&&i.value==='12.50 BYN'));assert.ok(t.entries().some(i=>i.label==='Сдача'&&i.value==='0.00 BYN'));await t.action('20.00 BYN');t.pump();assert.equal(t.h.state._paymentCashGiven,20);assert.ok(t.entries().some(i=>i.label==='Сдача'&&i.value==='7.50 BYN'));await t.action('Сумма · 20.00 BYN');t.pump();assert.equal(t.h.state._paymentCashGiven,'');assert.ok(t.entries().some(i=>i.kind==='button'&&i.label==='1'))});
test('cash sale locks duplicate gestures and publishes/prints only after the reviewed commit succeeds',async()=>{const t=host();const paying=t.action('Оплатить');t.pump();await t.action('Оплатить');assert.equal(t.events.filter(e=>e[0]==='commit').length,1);assert.equal(t.h.state.orders.length,0);assert.equal(t.h.state.products[0].stock,20);assert.ok(!t.events.some(e=>e[0]==='availability'||e[0]==='print'));t.reply();await paying;t.pump();assert.equal(t.h.state.orders.length,1);assert.equal(t.h.state.products[0].stock,19);assert.equal(t.h.state.orders[0].method,'cash');assert.ok(t.entries().some(i=>i.text==='Чек оплачен'));assert.equal(t.events.filter(e=>e[0]==='availability').length,1);assert.equal(t.events.filter(e=>e[0]==='print').length,1);await t.action('Готово');t.pump();assert.equal(t.h.state.paymentPage,'');assert.equal(t.h.document.getElementById('payment-page-root'),null)});
test('card remains an explicit terminal confirmation and cancelled confirmation does not record a sale',async()=>{const t=host();await t.action('Оплата картой');t.pump();assert.ok(t.entries().some(i=>i.text==='Проведите оплату на терминале'));assert.equal(t.events.filter(e=>e[0]==='commit').length,0);await t.back();t.pump();assert.equal(t.events.filter(e=>e[0]==='commit').length,0);assert.equal(t.h.state.paymentPage,'split');await t.back();t.pump();await t.action('Оплата картой');t.pump();const p=t.action('Оплата прошла');t.pump();assert.equal(t.events.filter(e=>e[0]==='commit').length,1);t.reply();await p;t.pump();assert.equal(t.h.state.orders[0].method,'card')});
test('paid split parts stay locked and reviewed back refusal keeps the native form and explains why',async()=>{const t=host();await t.action('Разделить');t.pump();assert.equal(t.h.state._splitPayments.length,2);assert.ok(t.entries().some(i=>i.text==='Количество платежей: 2'));t.h.state._splitPayments[0].paid=true;t.h.renderSplitPayment();t.pump();assert.ok(t.entries().some(i=>i.label==='Сумма части · 6,25'&&i.disabled));const token=t.sent.filter(p=>p.action==='formShow').at(-1).token,key=t.entries().find(i=>i.label==='Сумма части · 6,25').key;await t.h.__nativeSettingsAction({action:'click',token,key});assert.equal(t.h.state._activeSplitKeypad,undefined);await t.back();t.pump();assert.equal(t.h.state.paymentPage,'split');assert.equal(t.sent.filter(p=>p.action==='formResult').at(-1).message,'Сначала завершите раздельную оплату')});
test('failed or uncertain commit keeps unpaid sale state and native recovery feedback without sending anything',async()=>{const t=host();const p=t.action('Оплатить');t.h.criticalStorageRecoveryPending=true;t.fail(Error('commit status unknown'));await p;t.pump();assert.equal(t.h.state.orders.length,0);assert.equal(t.h.state.products[0].stock,20);assert.ok(!t.events.some(e=>e[0]==='availability'||e[0]==='print'));assert.equal(t.sent.filter(p=>p.action==='formResult').at(-1).blocked,true);assert.match(t.sent.filter(p=>p.action==='formResult').at(-1).message,/Оплата не завершена/)});
test('stale token and presentation rollback cannot pay a different page or change settlement ownership',async()=>{const t=host();const old=t.model();t.h.renderPaymentScreen();t.pump();await t.h.__nativeSettingsAction({action:'click',token:old.token,key:'1'});assert.equal(t.events.filter(e=>e[0]==='commit').length,0);t.h.MPosNativePaymentUiEnabled=false;t.pump();assert.equal(t.h.document.getElementById('payment-page-root').style.opacity,undefined);assert.equal(t.h.state.cart.length,1)});

test('payment completion back invokes reviewed Done rather than revealing the stale payment page',async()=>{
 const t=host(),p=t.action('Оплатить');t.reply();await p;t.pump();assert.equal(t.model().hideCancel,true);assert.equal(t.entries().filter(i=>i.label==='Готово').length,1);
 await t.back();t.pump();assert.equal(t.h.state.paymentPage,'');assert.equal(t.h.document.getElementById('payment-page-root'),null);assert.equal(t.h.state.orders.length,1);
});
test('offline reward back invokes the original cancel and clears its pending continuation',async()=>{
 const t=host();t.h.state.customer.id='customer';t.h.state.loyaltyRedemptions={gift:1};t.h.loyaltyApi=async()=>{throw Error('offline')};
 await t.action('Оплатить');t.pump();assert.ok(t.entries().some(i=>i.text==='Нет связи с программой лояльности'));assert.equal(typeof t.h.__offlinePaymentAction,'function');
 await t.back();t.pump();assert.equal(t.h.__offlinePaymentAction,null);assert.equal(t.h.state.loyaltyRedemptions.gift,1);assert.equal(t.events.filter(e=>e[0]==='commit').length,0);
});
