const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');const read=n=>fs.readFileSync('app/src/main/assets/pos/'+n,'utf8');const NOW=Date.parse('2026-10-07T12:00:00Z'),START=Date.parse('2026-10-01T00:00:00Z'),END=Date.parse('2026-10-03T00:00:00Z');
const product={id:'p',name:'Current name',type:'simple',stock:10,cost:2,category:'Current category'},shift={id:'s',employeeName:'Employee'};
const order=(id,at,total=100,extra={})=>({id,timestamp:at,shiftId:'s',total,method:'cash',items:[{productId:'p',name:'Historical name',category:'Historical category',qty:2,price:40,cost:3}],...extra});
const base={orders:[],products:[product],shifts:[shift],analyticsFrom:'2026-10-01',analyticsTo:'2026-10-02',tab:'analytics',loyaltyAnalytics:null};
function source(state,zone='UTC'){
 const previous=process.env.TZ;process.env.TZ=zone;const ctx={state:structuredClone(state),Date:class extends Date{constructor(...args){super(...(args.length?args:[NOW]))}static now(){return NOW}},Intl,localDateString:d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,getProduct:id=>ctx.state.products.find(p=>p.id===id),money:v=>'Money'+String(v),stockQtyText:String,escapeHtml:String,escapeAttr:String,flash:()=>{},currentShiftEmployeeIsAdmin:()=>true,closeModal:()=>{},render:()=>{}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(read('Web/js/features/analytics.js'),ctx);return{ctx,restore:()=>{if(previous===undefined)delete process.env.TZ;else process.env.TZ=previous}};
}
const cases=[
 ['empty',base],['bounds',{...base,orders:[order('a',START-1),order('b',START),order('c',END-1),order('d',END)]}],
 ['payment-arrays',{...base,orders:[order('a',START,100,{payments:[{method:'cash',amount:30},{method:'card',amount:70},{method:'other',amount:5}]}),order('b',START+1,200,{payments:[]}),order('c',START+2,300,{method:'card'}),order('d',START+3,400,{payments:null,method:'other'})]}],
 ['returns-independent-of-date',{...base,orders:[order('a',START,100,{returnedAt:NOW}),order('b',START+1,200,{returnedAt:'0'}),order('c',START+2,300,{returnedAt:0})]}],
 ['group-names-and-current-category',{...base,products:[],shifts:[],orders:[order('a',START,100,{items:[{productId:'gone1',productName:'Same',category:'Old',qty:1,price:20,cost:2},{productId:'gone2',name:'Same',qty:2,price:30,cost:4},{qty:1,price:10}]}),order('b',START+1,100,{items:[{productId:'p',qty:2,price:10}]})]}],
 ['legacy-numbers-and-stock-value',{...base,products:[{...product,stock:-2,cost:3},{id:'q',type:'simple',stock:4,cost:-1},{id:'u',type:'simple',stock:100,cost:5,noStockTracking:true},{id:'c',type:'composite',stock:100,cost:5},{id:'ok',type:'simple',stock:'4',cost:'3'}],orders:[order('a',START,'0x64',{items:[{productId:'p',qty:'2',price:'bad',cost:null},{productId:'p',qty:'bad',price:10,cost:2}]})]}],
 ['numeric-group-ties',{...base,shifts:[{id:'s10',employeeName:'10'},{id:'s2',employeeName:'2'}],orders:[order('a',START,10,{shiftId:'s10',items:[{name:'10',category:'10',qty:1,price:10}]}),order('b',START,10,{shiftId:'s2',items:[{name:'2',category:'2',qty:1,price:10}]})]}],
 ['default-today',{...base,analyticsFrom:'',analyticsTo:'',orders:[order('a',NOW),order('b',START)]}],
 ['moscow-bounds',{...base,orders:[order('a',START-3*3600000-1),order('b',START-3*3600000),order('c',END-3*3600000-1),order('d',END-3*3600000)]},'Europe/Moscow'],
 ['dst-day',{...base,analyticsFrom:'2025-10-26',analyticsTo:'2025-10-26',orders:[order('a',Date.parse('2025-10-25T22:00:00Z')),order('b',Date.parse('2025-10-26T22:59:59.999Z')),order('c',Date.parse('2025-10-26T23:00:00Z'))]},'Europe/Berlin'],
 ['reversed-range',{...base,analyticsFrom:'2026-10-03',analyticsTo:'2026-10-01',orders:[order('a',START)]}],
 ['invalid-range',{...base,analyticsFrom:'bad',orders:[order('a',START)]}],
 ['normalized-short-month',{...base,analyticsFrom:'2026-02-29',analyticsTo:'2026-02-29',orders:[order('a',Date.parse('2026-03-01T12:00:00Z'))]}],
 ['future-range',{...base,analyticsFrom:'2026-10-08',analyticsTo:'2026-10-08',orders:[order('future',Date.parse('2026-10-08T12:00:00Z'))]}],
 ['invalid-day32',{...base,analyticsFrom:'2026-02-32',orders:[order('a',START)]}]
];
function fixture([label,state,zone='UTC']){const h=source(state,zone);try{const data=h.ctx.analyticsData();const expected={...data,orderCount:data.orders.length,inventoryValue:h.ctx.inventoryCostValue(),range:h.ctx.analyticsRange()};delete expected.orders;return{label,request:{version:1,from:state.analyticsFrom||'',to:state.analyticsTo||'',now:NOW,zone},state,expected:JSON.parse(JSON.stringify(expected))}}finally{h.restore()}}
test('native analytics fixtures independently reproduce actual source sales, payments, refunds and periods',()=>{const actual=cases.map(fixture);if(process.env.MPOS_WRITE_ANALYTICS_FIXTURES)fs.writeFileSync('tests/fixtures/analytics-reports.json',JSON.stringify(actual,null,2)+'\n');assert.deepEqual(actual,JSON.parse(fs.readFileSync('tests/fixtures/analytics-reports.json','utf8')))});
function host(){const h=source({...base,orders:[order('a',START)]}),calls=[],events=[],node={scrollTop:31,outerHTML:'',contains:()=>false},ctx=h.ctx;ctx.document={querySelector:()=>node,activeElement:null};ctx.MPosCore={Analytics:{read:input=>new Promise((resolve,reject)=>calls.push({input,resolve,reject}))}};ctx.loadLoyaltyAnalytics=()=>events.push('loyalty');vm.runInContext(read('native-analytics.js'),ctx);return{...h,calls,events,node,data:fixture(['host',ctx.state]).expected}}
const ack=(h,index=0)=>h.calls[index].resolve({ok:true,authoritative:true,data:structuredClone(h.data)}),flush=()=>new Promise(r=>setImmediate(r));
test('hidden analytics has no native read or loyalty prefetch; active view applies native data',async()=>{const h=host();try{h.ctx.state.tab='pos';assert.doesNotMatch(h.ctx.renderAnalyticsScreen(),/Money/);assert.equal(h.calls.length,0);assert.equal(h.events.length,0);h.ctx.state.tab='analytics';assert.match(h.ctx.renderAnalyticsScreen(),/Загрузка аналитики/);ack(h);await flush();assert.match(h.node.outerHTML,/Money100/);assert.match(h.node.outerHTML,/Money20/);assert.equal(h.events.length,1);assert.equal(h.node.scrollTop,31)}finally{h.restore()}});
test('stale period/tab callbacks cannot update screen; read failure shows retry and no JS fallback',async()=>{const h=host();try{h.ctx.renderAnalyticsScreen();h.ctx.state.analyticsFrom='2026-10-02';h.ctx.renderAnalyticsScreen();ack(h,0);await flush();assert.equal(h.node.outerHTML,'');h.calls[1].reject(Error('read failure'));await flush();assert.match(h.node.outerHTML,/Повторить/);assert.doesNotMatch(h.node.outerHTML,/Money/);assert.throws(()=>h.ctx.analyticsData(),/ещё не загружена/);h.ctx.renderAnalyticsScreen();h.ctx.state.tab='pos';ack(h,2);await flush();assert.match(h.node.outerHTML,/Повторить/)}finally{h.restore()}});
test('native callback waits for date input blur and retains source non-admin visibility',async()=>{const h=host();try{let blur;const input={matches:()=>true,addEventListener:(_name,fn)=>{blur=fn}};h.node.contains=()=>true;h.ctx.document.activeElement=input;h.ctx.currentShiftEmployeeIsAdmin=()=>false;h.ctx.renderAnalyticsScreen();ack(h);await flush();assert.equal(h.node.outerHTML,'');assert.equal(typeof blur,'function');h.ctx.document.activeElement=null;blur();assert.doesNotMatch(h.node.outerHTML,/Валовая прибыль/);assert.doesNotMatch(h.node.outerHTML,/Стоимость остатков/);assert.equal(h.events.length,0)}finally{h.restore()}});
test('rollback keeps synchronous reviewed calculations and source markup',()=>{const h=host();try{h.ctx.MPosNativeAnalyticsEnabled=false;const html=h.ctx.renderAnalyticsScreen();assert.match(html,/Money100/);assert.equal(h.ctx.analyticsData().orders.length,1);assert.equal(h.ctx.inventoryCostValue(),20);assert.equal(h.calls.length,0)}finally{h.restore()}});

test('non-finite native financial data shows error instead of plausible zero statistics',async()=>{const h=host();try{h.ctx.renderAnalyticsScreen();h.calls[0].resolve({ok:true,authoritative:true,data:{...h.data,revenue:null}});await flush();assert.match(h.node.outerHTML,/некорректные суммы/);assert.match(h.node.outerHTML,/Повторить/);assert.doesNotMatch(h.node.outerHTML,/Money0/)}finally{h.restore()}});
