const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {dom}=require('./helpers/product-editor-dom.cjs');
const read=n=>fs.readFileSync('app/src/main/assets/pos/'+n,'utf8');
function host({count=60,pageError=false,reverseAdapters=false}={}){
 const sent=[],events=[],timers=[];let resolve,reject;
 const orders=Array.from({length:count},(_,i)=>({id:'r'+i,receiptDisplayNumber:String(i+1),timestamp:1000-i,total:12.5,method:'cash',cashGiven:20,change:7.5,shiftId:'old',items:[{productId:'milk',name:'Молоко',qty:1,price:12.5,comment:'Без пакета'}],stockConsumption:{version:1,items:[{productId:'milk',qty:1}]}}));
 const h={state:{loaded:true,tab:'receipts',orders,products:[{id:'milk',type:'simple',stock:20}],shifts:[{id:'now',cashMovements:[]}]},criticalOperationBusy:false,criticalStorageRecoveryPending:false,innerWidth:1000,innerHeight:800,addEventListener:()=>{},Event:class{constructor(type){this.type=type}},setTimeout:f=>timers.push(f),webkit:{messageHandlers:{settingsScreen:{postMessage:p=>{sent.push(JSON.parse(JSON.stringify(p)));return true}}}},MPosCore:{Receipts:{page:async(offset,limit)=>{events.push(['page',offset,limit]);if(pageError)throw Error('offline storage');return{rows:h.state.orders.slice(offset,offset+limit),total:h.state.orders.length}}}},flash:m=>events.push(['flash',m]),console:{error:()=>{}},currentShift:()=>h.state.shifts[0],shiftTotals:()=>({}),cashDrawerBalance:()=>100,storageSnapshot:o=>JSON.parse(JSON.stringify(o)),roundStockQty:n=>n,uid:()=> 'movement',fullMoney:v=>Number(v).toFixed(2)+' BYN',money:v=>Number(v).toFixed(2),fmtDate:()=> '07.10.2026',escapeHtml:s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;'),escapeAttr:s=>h.escapeHtml(s),receiptItemDiscount:()=>0,receiptItemTotal:i=>i.price*i.qty,receiptProductDiscountTotal:()=>0,receiptLoyaltyPrograms:()=>[],commitCriticalStorage:(type,writes)=>{events.push(['commit',type,writes]);return new Promise((yes,no)=>{resolve=yes;reject=no})},publishAvailability:()=>events.push(['availability-gate']),settleReturnedOrderLoyalty:()=>events.push(['loyalty']),sendOrderToPrint:o=>events.push(['print',o.id]),showModal:html=>{h.document.getElementById('modal-root').innerHTML='<div class="modal">'+html+'</div>'},closeModal:()=>{h.document.getElementById('modal-root').innerHTML=''},render:()=>{h.document.getElementById('app').innerHTML=h.renderReceiptsScreen()}};
 const fixture=dom(h);Object.assign(h,fixture);h.window=h;vm.createContext(h);vm.runInContext(read('Web/js/features/payment.js'),h);vm.runInContext(read('Web/js/features/receipts.js'),h);h.sendOrderToPrint=o=>events.push(['print',o.id]);for(const adapter of reverseAdapters?['native-settings-ui.js','native-receipts-history.js']:['native-receipts-history.js','native-settings-ui.js'])vm.runInContext(read(adapter),h);
 const flat=items=>items.flatMap(i=>[i,...(i.items?flat(i.items):[])]),model=()=>sent.filter(p=>['show','formShow','formPatch'].includes(p.action)).at(-1),entries=()=>flat(model().items);
 const pump=()=>{while(timers.length)timers.shift()();fixture.pump()};
 const settle=async()=>{await new Promise(setImmediate);pump()};
 const action=label=>h.__nativeSettingsAction({action:'click',token:model().token,key:entries().find(i=>i.kind==='button'&&i.label===label)?.key});
 h.render();pump();return{h,sent,events,pump,settle,model,entries,action,reply:()=>resolve(),fail:e=>reject(e),recoverPage:()=>{pageError=false}};
}
test('native history retains native 50-row paging, formatted details, selected rows and manual print',async()=>{
 const t=host();await t.settle();assert.equal(t.entries().filter(i=>i.kind==='button'&&i.label.startsWith('Чек ')).length,50);assert.ok(t.entries().some(i=>i.kind==='columns'));assert.ok(t.entries().some(i=>i.label==='Итого'&&i.value==='12.50 BYN'));assert.ok(t.entries().some(i=>(i.text||'').includes('Комментарий:')&&(i.text||'').includes('Без пакета')));await t.action('Печать');assert.deepEqual(t.events.filter(e=>e[0]==='print'),[['print','r0']]);await t.action('Далее');await t.settle();assert.equal(t.entries().filter(i=>i.kind==='button'&&i.label.startsWith('Чек ')).length,10);assert.equal(t.h.state.selectedReceiptId,'r50');assert.equal(t.h.state.orders.length,60);assert.ok(t.events.some(e=>e[0]==='page'&&e[1]===50));
});
test('history loading error exposes original retry and empty state stays native',async()=>{
 const t=host({pageError:true});await t.settle();assert.ok(t.entries().some(i=>i.text==='Не удалось загрузить историю'));assert.ok(t.entries().some(i=>i.label==='Повторить'));t.recoverPage();await t.action('Повторить');await t.settle();assert.ok(t.entries().some(i=>i.label==='Далее'));const empty=host({count:0});await empty.settle();assert.ok(empty.entries().some(i=>/Чеков пока нет/.test(i.text||'')));
});
test('full return is locked until local commit, restores saved stock and uses current shift',async()=>{
 const t=host();await t.settle();await t.action('Вернуть');t.pump();assert.equal(t.model().action,'formShow');assert.ok(t.entries().some(i=>i.value==='12.50 BYN'));const returning=t.action('Вернуть 12.50 BYN');t.pump();await t.action('Вернуть 12.50 BYN');assert.equal(t.events.filter(e=>e[0]==='commit').length,1);assert.equal(t.h.state.products[0].stock,20);assert.equal(t.h.state.orders[0].returnedAt,undefined);assert.equal(t.events.filter(e=>e[0]==='availability-gate').length,0);t.reply();await returning;t.pump();assert.equal(t.h.state.products[0].stock,21);assert.equal(t.h.state.orders[0].shiftId,'old');assert.equal(t.h.state.orders[0].returnedShiftId,'now');assert.equal(t.h.state.shifts[0].cashMovements[0].amount,12.5);assert.ok(t.entries().some(i=>i.text==='Возврат выполнен'));await t.action('Открыть чек');t.pump();assert.ok(t.entries().some(i=>/Возврат/.test(i.text||'')));assert.ok(!t.entries().some(i=>i.label==='Вернуть'));
});
test('failed or uncertain return leaves data unchanged, reports error and blocks recovery resubmit',async()=>{
 const t=host();await t.settle();await t.action('Вернуть');t.pump();const p=t.action('Вернуть 12.50 BYN');t.h.criticalStorageRecoveryPending=true;t.fail(Error('commit status is uncertain'));await p;t.pump();assert.equal(t.h.state.products[0].stock,20);assert.equal(t.h.state.orders[0].returnedAt,undefined);assert.equal(t.h.state.shifts[0].cashMovements.length,0);assert.equal(t.events.filter(e=>e[0]==='availability-gate').length,0);assert.match(t.sent.filter(p=>p.action==='formResult').at(-1).message,/Не удалось выполнить возврат/);assert.equal(t.sent.filter(p=>p.action==='formResult').at(-1).blocked,true);
});
test('closed shift, insufficient cash and duplicate return preserve source refusals',async()=>{
 const t=host();await t.settle();t.h.currentShift=()=>null;await t.action('Вернуть');assert.equal(t.events.filter(e=>e[0]==='commit').length,0);assert.ok(t.events.some(e=>e[1]==='Для возврата откройте кассовую смену'));t.h.currentShift=()=>t.h.state.shifts[0];await t.action('Вернуть');t.pump();t.h.cashDrawerBalance=()=>1;await t.action('Вернуть 12.50 BYN');assert.match(t.sent.filter(p=>p.action==='formResult').at(-1).message,/Недостаточно наличных/);t.h.state.orders[0].returnedAt=1;await t.action('Вернуть 12.50 BYN');assert.match(t.sent.filter(p=>p.action==='formResult').at(-1).message,/уже возвращён/);assert.equal(t.events.filter(e=>e[0]==='commit').length,0);
});
test('modal closes once, stale tokens cannot print another receipt and rollback restores source',async()=>{
 const t=host();await t.settle();const old=t.model();t.h.viewReceiptModal('r1');t.pump();await t.h.__nativeSettingsAction({action:'click',token:old.token,key:t.entries().find(i=>i.label==='Печать').key});assert.equal(t.events.filter(e=>e[0]==='print').length,0);await t.h.__nativeSettingsAction({action:'cancel',token:t.model().token});t.pump();assert.equal(t.h.document.querySelector('#modal-root .modal'),null);t.h.MPosNativeReceiptUiEnabled=false;t.pump();assert.notEqual(t.h.document.querySelector('.screen').style.opacity,'0');assert.equal(t.h.state.orders.length,60);
});
test('split refund withdraws only cash component and card-only refund leaves drawer untouched',async()=>{
 for(const method of ['split','card']){
  const t=host();await t.settle();const order=t.h.state.orders[0];order.method=method;if(method==='split')order.payments=[{method:'cash',amount:5},{method:'card',amount:7.5}];t.h.cashDrawerBalance=()=>6;t.h.render();t.pump();await t.action('Вернуть');t.pump();const p=t.action('Вернуть 12.50 BYN');t.reply();await p;t.pump();assert.equal(t.h.state.shifts[0].cashMovements.length,method==='split'?1:0);if(method==='split')assert.equal(t.h.state.shifts[0].cashMovements[0].amount,5);assert.ok(t.entries().some(i=>(i.text||'').includes('через банковский терминал')));
 }
});
test('history selection targets mounted receipt identity and preserves detailed modifiers and customer',async()=>{
 const t=host();await t.settle();Object.assign(t.h.state.orders[1],{customer:{name:'Гость',phone:'123',address:'Адрес'},deliveryFee:2,orderLabel:'Стол 7'});t.h.state.orders[1].items[0].selectedModifiers=[{name:'Сироп',priceDelta:1}];t.h.render();t.pump();const label=t.entries().find(i=>i.kind==='button'&&i.label.startsWith('Чек 2\n')||i.kind==='button'&&i.label.startsWith('Чек 2 '))?.label;assert.ok(label);await t.action(label);t.pump();assert.equal(t.h.state.selectedReceiptId,'r1');assert.ok(t.entries().some(i=>(i.text||'').includes('Сироп')));assert.ok(t.entries().some(i=>(i.text||'').includes('Гость')));assert.ok(t.entries().some(i=>i.label==='Доставка'&&i.value==='2.00 BYN'));await t.action('Печать');assert.equal(t.events.filter(e=>e[0]==='print').at(-1)[1],'r1');
});

test('asset-sync adapter ordering keeps native history paging and action identities',async()=>{const t=host({reverseAdapters:true});await t.settle();assert.equal(t.entries().filter(i=>i.receiptRow).length,50);await t.action('Далее');await t.settle();assert.equal(t.entries().filter(i=>i.receiptRow).length,10);assert.equal(t.h.state.selectedReceiptId,'r50');await t.action('Печать');assert.equal(t.events.filter(e=>e[0]==='print').at(-1)[1],'r50')});
