const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const read=name=>fs.readFileSync('app/src/main/assets/pos/'+name,'utf8');
function host(input={},native=true){
 const state={products:[{id:'p',name:'Milk',type:'simple',stockUnit:'l',stock:5,cost:10}],purchaseOrders:[],receivingCart:[],...structuredClone(input.state||{})},calls=[],events=[],buttons=[{disabled:false}],stored=structuredClone(input.saved??null);
 const ctx={state,storageSnapshot:structuredClone,getProduct:id=>state.products.find(p=>p.id===id),criticalStorageRecoveryPending:false,document:{querySelector:()=>({scrollTop:41}),querySelectorAll:()=>buttons},loadKey:async()=>stored,PrilavokCore:{Storage:{set:async(key,value)=>calls.push({key,value:structuredClone(value)})}},MPosCore:{ReceivingDraft:{execute:c=>new Promise((resolve,reject)=>calls.push({c,resolve,reject}))}},receivingDocumentInput:()=>events.push('input'),renderReceivingDocument:()=>events.push('document'),finishReceivingPage:()=>events.push('finish'),render:()=>events.push('render'),closeModal:()=>events.push('close'),flash:m=>events.push(m),markStorageBroken:()=>events.push('broken')};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(read('Web/js/features/product-configuration.js'),ctx);vm.runInContext(read('Web/js/features/receiving-drafts.js'),ctx);if(native)vm.runInContext(read('native-receiving-draft.js'),ctx);if(input.draft)ctx._receivingDraft=structuredClone(input.draft);return{ctx,calls,events,buttons};
}
const baseOrder={id:'o',status:'pending',supplierId:'s',items:[{productId:'p',requestedQty:3,requestedUnit:'bottle',packSize:500,contentUnit:'ml',stockUnit:'l',expectedQty:1.5,qty:1.5}],extension:9};
const savedDraft={version:1,orderId:'old',supplierId:'s',invoiceNumber:' partial ',invoiceDate:'',lines:[{productId:'p',qtyInput:'',totalInput:'',priceMode:'total',unit:'l'}],extension:{v:8}};
const scenarios=[
 {name:'new-order',operation:'open',orderId:'o',state:{purchaseOrders:[baseOrder]}},
 {name:'legacy-order',operation:'open',orderId:'o',state:{purchaseOrders:[{...baseOrder,receivingDraft:{p:{qty:0,totalCost:0}}}]}},
 {name:'unknown-package',operation:'open',orderId:'o',state:{purchaseOrders:[{...baseOrder,items:[{...baseOrder.items[0],expectedQty:null,qty:0}]}]}},
 {name:'saved-order',operation:'open',orderId:'o',state:{purchaseOrders:[{...baseOrder,receivingDraftV2:savedDraft,receivingIncomplete:true}]}},
 {name:'saved-order-mark-incomplete',operation:'open',orderId:'o',state:{purchaseOrders:[{...baseOrder,receivingDraftV2:savedDraft,receivingIncomplete:false}]}},
 {name:'cart',operation:'open',state:{receivingCart:[{productId:'p',qty:2,totalCost:20,stockUnit:'l'}]}},
 {name:'null-cart-fields',operation:'open',state:{receivingCart:[{productId:'p',qty:null,totalCost:null}]}},
 {name:'saved-standalone',operation:'open',saved:savedDraft},
 {name:'empty-standalone',operation:'open'},
 {name:'save-ordered-partial',operation:'save',draft:{...savedDraft,orderId:'o'},state:{purchaseOrders:[baseOrder]}},
 {name:'save-standalone-partial',operation:'save',draft:{...savedDraft,orderId:null}}
];
async function fixture(s){const h=host(s,false),before=structuredClone(h.ctx.state.purchaseOrders),command={version:1,operation:s.operation,expectedOrders:before};if(s.operation==='open'){command.orderId=s.orderId??null;command.cart=structuredClone(h.ctx.state.receivingCart)}else command.draft=structuredClone(s.draft);const success=s.operation==='open'?await h.ctx.openReceivingDocument(s.orderId??null):await h.ctx.saveReceivingDraft();assert.equal(success,true,s.name);const write=h.calls.find(c=>c.key==='purchaseOrders'),draft=s.operation==='open'?h.ctx._receivingDraft:s.draft;return{name:s.name,command,products:h.ctx.state.products,saved:s.saved??null,result:{draft,orders:h.ctx.state.purchaseOrders,changed:!!write}}}
async function fixtures(){return Promise.all(scenarios.map(fixture))}
test('native restoration fixtures independently reproduce reviewed receiving-drafts source',async()=>{const actual=await fixtures();if(process.env.MPOS_WRITE_DRAFT_FIXTURES)fs.writeFileSync('tests/fixtures/receiving-drafts.json',JSON.stringify(actual,null,2)+'\n');assert.deepEqual(JSON.parse(JSON.stringify(actual)),JSON.parse(fs.readFileSync('tests/fixtures/receiving-drafts.json','utf8')))});
test('open waits for native persistence, prevents double tap and renders restored result',async()=>{const s=scenarios[0],h=host(s),before=JSON.stringify(h.ctx.state.purchaseOrders),p=h.ctx.openReceivingDocument('o');assert.equal(h.calls.length,1);assert.equal(h.ctx._receivingDraft,undefined);assert.equal(JSON.stringify(h.ctx.state.purchaseOrders),before);assert.equal(await h.ctx.openReceivingDocument('o'),false);const f=await fixture(s);h.calls[0].resolve(f.result);assert.equal(await p,true);assert.equal(h.ctx._receivingPageScroll,41);assert.equal(h.ctx.state.purchaseOrders[0].receivingIncomplete,true);assert.ok(h.events.includes('document'))});
test('incomplete ordered draft saves only after native ack; failures retain draft and buttons',async()=>{const s=scenarios.at(-2),h=host(s),p=h.ctx.saveReceivingDraft();assert.equal(h.buttons[0].disabled,true);assert.ok(h.ctx._receivingDraft);assert.equal(await h.ctx.saveReceivingDraft(),false);h.calls[0].reject(Error('disk failure'));assert.equal(await p,false);assert.equal(h.buttons[0].disabled,false);assert.ok(h.ctx._receivingDraft);assert.equal(h.ctx.state.purchaseOrders[0].receivingIncomplete,undefined);assert.equal(h.ctx._receivingDraftSaveBusy,false);const retry=h.ctx.saveReceivingDraft();h.calls[1].resolve((await fixture(s)).result);assert.equal(await retry,true);assert.equal(h.ctx._receivingDraft,null);assert.equal(h.ctx.state.purchaseOrders[0].receivingDraftV2.lines[0].qtyInput,'')});
test('standalone restores with native source and stays editable after save',async()=>{const s=scenarios.at(-1),h=host(s),p=h.ctx.saveReceivingDraft();h.calls[0].resolve((await fixture(s)).result);assert.equal(await p,true);assert.ok(h.ctx._receivingDraft);assert.equal(h.ctx.state.products[0].stock,5)});
test('received/deleted orders and uncertain command results block further draft work',async()=>{const h=host(scenarios[0]);h.ctx.state.purchaseOrders[0].status='received';assert.equal(await h.ctx.openReceivingDocument('o'),false);assert.equal(h.calls.length,0);h.ctx.state.purchaseOrders[0].status='pending';const p=h.ctx.openReceivingDocument('o');h.calls[0].reject(Error('commit status is uncertain'));assert.equal(await p,false);assert.equal(h.ctx.criticalStorageRecoveryPending,true);assert.equal(await h.ctx.openReceivingDocument('o'),false);assert.equal(h.calls.length,1)});
test('rollback invokes reviewed source retaining native-compatible storage interface',async()=>{const h=host(scenarios[0]);h.ctx.MPosNativeReceivingDraftEnabled=false;assert.equal(await h.ctx.openReceivingDocument('o'),true);assert.equal(h.calls[0].key,'purchaseOrders');assert.equal(h.ctx.state.purchaseOrders[0].receivingIncomplete,true)});
