const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('app/src/main/assets/pos/Web/js/features/hall-bookings.js','utf8'),adapter=fs.readFileSync('app/src/main/assets/pos/native-hall-command.js','utf8');
const clone=v=>JSON.parse(JSON.stringify(v));
function host(fixture,native=false){
 const state={...clone(fixture.expected),bookingDate:fixture.date||'2026-10-07',bookingTime:'19:00',bookingDuration:120,selectedHallTableId:'t',hallEditMode:true},events=[],calls=[],fields={};
 const c=fixture.command;
 for(const [key,val]of Object.entries({'new-hall-table-name':c.name,'edit-hall-table-name':c.name,'booking-name-input':c.guestName,'booking-phone-input':c.phone,'booking-guests-input':c.guests,'booking-note-input':c.note,'booking-time-input':c.time,'booking-duration-input':c.duration,'edit-booking-name':c.guestName,'edit-booking-phone':c.phone,'edit-booking-guests':c.guests,'edit-booking-note':c.note,'edit-booking-time':c.time,'edit-booking-duration':c.duration}))if(val!==undefined)fields[key]={value:String(val)};
 const context={state,Date:class extends Date{static now(){return 123}},Intl,Math,document:{getElementById:id=>fields[id]},uid:()=>c.id,localDateString:d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,saveKey:(key,value)=>calls.push({key,value:clone(value)}),flash:m=>events.push(m),closeModal:()=>events.push('close'),render:()=>events.push('render'),criticalStorageRecoveryPending:false};
 context.window=context;vm.createContext(context);vm.runInContext(source,context);
 if(native){context.MPosCore={HallCommands:{commit:input=>{calls.push(clone(input));return new Promise((resolve,reject)=>context.pending={resolve,reject})}}};vm.runInContext(adapter,context)}
 return {context,state,events,calls,fields};
}
function invoke(h,c){const names={'table-create':'createHallTable','table-edit':'saveHallTableEdits','table-rotate':'rotateHallTable','table-delete':'confirmDeleteHallTable','booking-create':'saveNewBooking','booking-edit':'saveEditedBooking','booking-cancel':'cancelBooking'};return h.context[names[c.operation]](c.operation==='table-create'?c.shape:c.operation==='booking-create'?c.tableId:c.id,c.delta)}
const fixtures=JSON.parse(fs.readFileSync('tests/fixtures/hall-commands.json','utf8'));
test('reviewed source independently verifies every table and booking fixture',()=>{for(const f of fixtures){const old=process.env.TZ;process.env.TZ=f.command.zone||'UTC';try{const h=host(f);invoke(h,f.command);if(f.refused)assert.ok(h.events.includes(f.refused),f.name);else assert.deepEqual({hallTables:clone(h.state.hallTables),bookings:clone(h.state.bookings)},f.result,f.name)}finally{if(old===undefined)delete process.env.TZ;else process.env.TZ=old}}});
test('native commands capture forms before await and publish memory only after durable acknowledgement',async()=>{const f=fixtures.find(f=>f.name==='create'),h=host(f,true),p=invoke(h,f.command);assert.deepEqual(clone(h.state.hallTables),f.expected.hallTables);h.fields['new-hall-table-name'].value='changed';assert.equal(h.calls[0].name,'Cafe');assert.equal(h.events.length,0);h.context.pending.resolve({ok:true,authoritative:true,...clone(f.result)});assert.equal(await p,true);assert.deepEqual(clone(h.state.hallTables),f.result.hallTables);assert.ok(h.events.includes('Стол добавлен'));assert.equal(h.state.selectedHallTableId,'new')});
test('failure and double tap keep persisted state, uncertain commit prevents another command',async()=>{const f=fixtures.find(f=>f.name==='delete'),h=host(f,true),p=invoke(h,f.command);await invoke(h,f.command);assert.equal(h.calls.length,1);h.context.pending.reject(Error('commit status is uncertain'));assert.equal(await p,false);assert.deepEqual(clone(h.state.hallTables),f.expected.hallTables);assert.deepEqual(clone(h.state.bookings),f.expected.bookings);assert.ok(!h.events.includes('close'));await invoke(h,f.command);assert.equal(h.calls.length,1);assert.equal(h.context.criticalStorageRecoveryPending,true)});
test('empty edited name cannot mutate an existing booking and native conflict has no JS fallback',async()=>{const f=fixtures.find(f=>f.name==='edit-booking'),h=host(f,true);h.fields['edit-booking-name'].value=' ';await invoke(h,f.command);assert.equal(h.calls.length,0);assert.deepEqual(clone(h.state.bookings),f.expected.bookings);h.fields['edit-booking-name'].value='N';const p=invoke(h,f.command);h.context.pending.reject(Error('На выбранное время стол уже забронирован'));await p;assert.deepEqual(clone(h.state.bookings),f.expected.bookings);assert.ok(h.events.some(e=>e.includes('уже забронирован')))});
test('drag preview restores durable baseline before native move, failure keeps original coordinates',async()=>{const f=fixtures.find(f=>f.name==='edit'),h=host(f,true);h.fields.bookingsMap={clientWidth:100,clientHeight:100};const event={clientX:0,clientY:0,preventDefault(){},stopPropagation(){}};const el={dataset:{id:'t'},style:{}};h.context.hallPointerStart(event,el);h.context.hallPointerMove({...event,clientX:30,clientY:20},el);assert.equal(h.state.hallTables[0].x,37);const p=h.context.hallPointerEnd(event);assert.equal(h.state.hallTables[0].x,7);assert.equal(h.calls[0].x,37);assert.equal(h.calls[0].expected.hallTables[0].x,7);h.context.pending.reject(Error('failed'));await p;assert.equal(h.state.hallTables[0].x,7);assert.equal(h.state._hallDrag,null)});
test('rollback delegates to reviewed handlers while native owned storage remains unchanged',()=>{const f=fixtures.find(f=>f.name==='create'),h=host(f,true);h.context.MPosNativeHallCommandsEnabled=false;invoke(h,f.command);assert.deepEqual(clone(h.state.hallTables),f.result.hallTables);assert.equal(h.calls[0].key,'hallTables')});
module.exports={host,invoke};
