const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {dom}=require('./helpers/product-editor-dom.cjs');
const read=name=>fs.readFileSync('app/src/main/assets/pos/'+name,'utf8');
function host(admin=true){
 const sent=[],reads=[],network=[],events=[],timers=[];
 const h={state:{loaded:true,tab:'analytics',analyticsFrom:'2026-10-01',analyticsTo:'2026-10-07',products:[],orders:[],shifts:[],loyaltyAnalyticsKey:'',loyaltyAnalytics:null},innerWidth:1040,innerHeight:640,setTimeout:f=>timers.push(f),Event:class{constructor(type){this.type=type}},addEventListener:()=>{},currentShiftEmployeeIsAdmin:()=>admin,money:v=>Number(v).toFixed(2)+' BYN',stockQtyText:String,localDateString:d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-'),escapeHtml:s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;'),escapeAttr:s=>h.escapeHtml(s),flash:m=>events.push(m),loyaltyApi:url=>new Promise((resolve,reject)=>network.push({url,resolve,reject})),showModal:html=>h.document.getElementById('modal-root').innerHTML='<div class="modal">'+html+'</div>',closeModal:()=>h.document.getElementById('modal-root').innerHTML='',render:()=>h.document.getElementById('app').innerHTML=h.state.tab==='analytics'?h.renderAnalyticsScreen():'<div class="screen active"></div>',webkit:{messageHandlers:{settingsScreen:{postMessage:p=>{sent.push(JSON.parse(JSON.stringify(p)));return true}}}},MPosCore:{Analytics:{read:input=>new Promise((resolve,reject)=>reads.push({input,resolve,reject}))}}};
 const fixture=dom(h);Object.assign(h,fixture);h.window=h;vm.createContext(h);
 // Execute reviewed report/presentation helpers only; authentication is outside this scope.
 const source=read('Web/js/features/analytics.js');vm.runInContext(source.slice(0,source.indexOf('function unlockAnalyticsSensitive'))+source.slice(source.indexOf('function inventoryCostValue')),h);
 vm.runInContext(read('native-analytics.js'),h);vm.runInContext(read('native-settings-ui.js'),h);
 const data={revenue:123,cash:23,card:100,cost:30,profit:93,avg:61.5,orderCount:2,inventoryValue:44,employees:[{name:'Иван',value:123}],categories:[{name:'Напитки',qty:5}],products:Array.from({length:12},(_,n)=>({name:'Товар '+n,qty:12-n}))};
 const flat=items=>items.flatMap(i=>[i,...(i.items?flat(i.items):[])]),model=()=>sent.filter(p=>['show','formShow','formPatch'].includes(p.action)).at(-1),entries=()=>flat(model().items),pump=()=>{while(timers.length)timers.shift()();fixture.pump()},settle=async()=>{await new Promise(setImmediate);pump()},reply=(i=0,value=data)=>reads[i].resolve({ok:true,authoritative:true,data:structuredClone(value)}),action=label=>h.__nativeSettingsAction({action:'click',token:model().token,key:entries().find(i=>i.kind==='button'&&i.label===label)?.key}),change=fields=>h.__nativeSettingsAction({action:'change',token:model().token,fields});
 h.render();pump();return {h,sent,reads,network,events,data,model,entries,pump,settle,reply,action,change};
}
test('native analytics renders native-authoritative admin metrics, all charts, source order and top ten',async()=>{
 const t=host();assert.ok(t.entries().some(i=>i.text?.includes('Загрузка аналитики')));assert.equal(t.network.length,0);t.reply();await t.settle();assert.ok(t.entries().some(i=>i.kind==='metric'&&i.label==='Выручка'&&i.value==='123.00 BYN'));const bars=t.entries().filter(i=>i.kind==='bars');assert.equal(bars.length,4);assert.deepEqual(bars[0].rows,[{name:'Иван',value:'123.00 BYN',width:100}]);assert.equal(bars[3].rows.length,10);assert.equal(bars[3].rows[0].name,'Товар 0');assert.equal(t.network.length,1);assert.ok(t.entries().some(i=>i.type==='date'&&i.value==='2026-10-01'));assert.ok(t.entries().some(i=>i.kind==='grid'&&i.minCellWidth===380));
});
test('cashier native model and accessibility data contain no hidden employee money or financial KPI',async()=>{
 const t=host(false);t.reply();await t.settle();const bars=t.entries().filter(i=>i.kind==='bars');assert.equal(bars[0].rows[0].value,'');assert.equal(bars[1].rows[0].value,'18,7%');assert.equal(bars[1].rows[1].value,'81,3%');assert.equal(t.entries().some(i=>i.kind==='metric'),false);assert.doesNotMatch(JSON.stringify(t.model()),/123\.00 BYN|100\.00 BYN|Валовая прибыль|Стоимость остатков/);assert.equal(t.network.length,0);
});
test('period modal preserves required/reversed validation and successful original apply',async()=>{
 const t=host();t.reply();await t.settle();t.h.openAnalyticsPeriodModal();t.pump();assert.equal(t.model().action,'formShow');const fields=t.entries().filter(i=>i.kind==='field');await t.h.__nativeSettingsAction({action:'click',token:t.model().token,key:t.entries().find(i=>i.label==='Применить').key,fields:{[fields[0].key]:'2026-10-08',[fields[1].key]:'2026-10-07'}});t.pump();assert.equal(t.h.state.analyticsFrom,'2026-10-01');assert.ok(t.h.document.querySelector('#modal-root .modal'));assert.match(t.sent.filter(p=>p.action==='formResult').at(-1).message,/не может быть позже/);await t.h.__nativeSettingsAction({action:'click',token:t.model().token,key:t.entries().find(i=>i.label==='Применить').key,fields:{[fields[0].key]:'2026-10-02',[fields[1].key]:'2026-10-03'}});t.pump();assert.equal(t.h.state.analyticsFrom,'2026-10-02');assert.equal(t.h.state.analyticsTo,'2026-10-03');assert.equal(t.h.document.querySelector('#modal-root .modal'),null);assert.equal(t.reads.at(-1).input.to,'2026-10-03');
});
test('presets, empty results and user-confirmed reversed inline-date state remain compatible',async()=>{
 const t=host(false);t.reply();await t.settle();await t.action('7 дней');t.pump();assert.equal(t.reads.at(-1).input.from,t.h.state.analyticsFrom);assert.equal(t.reads.at(-1).input.to,t.h.state.analyticsTo);t.reply(1,{...t.data,employees:[],categories:[],products:[],revenue:0,cash:0,card:0,avg:0,profit:0,cost:0,orderCount:0});await t.settle();assert.ok(t.entries().some(i=>i.text==='Нет продаж за выбранный период.'));const from=t.entries().find(i=>i.type==='date'&&i.label==='От');const reads=t.reads.length;await t.change({[from.key]:'2099-01-01'});assert.equal(t.h.state.analyticsFrom,'2099-01-01');assert.equal(t.reads.length,reads);assert.ok(t.events.includes('Дата начала не может быть позже даты окончания'));
});
test('native picker defers async replacement until close and rejects stale period after selection',async()=>{
 const t=host(false);t.reply();await t.settle();t.h.render();t.pump();const before=t.h.document.querySelector('[data-mpos-native-analytics]'),model=t.model(),date=t.entries().find(i=>i.type==='date');await t.h.__nativeSettingsAction({action:'dateEditing',token:model.token,key:date.key,editing:true});t.reply(1,{...t.data,employees:[{name:'Поздний сотрудник',value:123}]});await t.settle();assert.equal(t.h.document.querySelector('[data-mpos-native-analytics]'),before);await t.h.__nativeSettingsAction({action:'dateEditing',token:model.token,key:date.key,editing:false});t.pump();assert.notEqual(t.h.document.querySelector('[data-mpos-native-analytics]'),before);assert.ok(t.entries().filter(i=>i.kind==='bars')[0].rows.some(r=>r.name==='Поздний сотрудник'));
 t.h.render();t.pump();const next=t.model(),start=t.entries().find(i=>i.type==='date'&&i.label==='От');await t.h.__nativeSettingsAction({action:'dateEditing',token:next.token,key:start.key,editing:true});t.reply(2,{...t.data,employees:[{name:'Устаревший',value:123}]});await t.settle();await t.change({[start.key]:'2026-10-02'});t.pump();await t.h.__nativeSettingsAction({action:'dateEditing',token:next.token,key:start.key,editing:false});assert.equal(t.h.MPosCore.AnalyticsUi.dateEditing,false);assert.equal(t.entries().filter(i=>i.kind==='bars').some(i=>i.rows.some(r=>r.name==='Устаревший')),false);
});
test('read failure retries without JS calculation, late tab results and old mounted actions do not apply',async()=>{
 const t=host(false);t.reads[0].reject(Error('native read failed'));await t.settle();assert.ok(t.entries().some(i=>i.label==='Повторить'));await t.action('Повторить');t.pump();assert.equal(t.reads.length,2);const old=t.model();t.h.state.tab='pos';t.h.render();t.pump();t.reply(1);await t.settle();assert.equal(t.h.document.querySelector('[data-mpos-native-analytics]'),null);await t.h.__nativeSettingsAction({action:'click',token:old.token,key:'1'});assert.equal(t.reads.length,2);
});
test('presentation-only rollback restores DOM but keeps native read authority and guards',async()=>{
 const t=host(false);t.reply();await t.settle();t.h.MPosNativeAnalyticsUiEnabled=false;t.pump();assert.notEqual(t.h.document.querySelector('[data-mpos-native-analytics]').style.opacity,'0');const before=t.reads.length;t.h.render();t.pump();assert.equal(t.reads.length,before+1);assert.throws(()=>t.h.analyticsData(),/ещё не загружена/);
});
